#ifndef NUMBER_VTABLE_DEFS_H
#define NUMBER_VTABLE_DEFS_H

#include "number_internal.h"

number_t *number_abs_double(const number_t *number);
number_t *number_abs_mcomplex(const number_t *number);
number_t *number_abs_mfloat(const number_t *number);
number_t *number_abs_mint(const number_t *number);
number_t *number_abs_mrational(const number_t *number);
number_t *number_abs_qcomplex(const number_t *number);
number_t *number_abs_qfloat(const number_t *number);
number_t *number_add_same_double(const number_t *a, const number_t *b);
number_t *number_add_same_mcomplex(const number_t *a, const number_t *b);
number_t *number_add_same_mfloat(const number_t *a, const number_t *b);
number_t *number_add_same_mint(const number_t *a, const number_t *b);
number_t *number_add_same_mrational(const number_t *a, const number_t *b);
number_t *number_add_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_add_same_qfloat(const number_t *a, const number_t *b);
number_t *number_arg_double(const number_t *number);
number_t *number_arg_mcomplex(const number_t *number);
number_t *number_arg_qcomplex(const number_t *number);
number_t *number_arg_qfloat(const number_t *number);
number_t *number_clone_double(const number_t *number);
number_t *number_clone_mcomplex(const number_t *number);
number_t *number_clone_mfloat(const number_t *number);
number_t *number_clone_mint(const number_t *number);
number_t *number_clone_mrational(const number_t *number);
number_t *number_clone_qcomplex(const number_t *number);
number_t *number_clone_qfloat(const number_t *number);
number_t *number_const_prec_double(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mcomplex(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mfloat(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mint(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mrational(const number_t *number, size_t precision_bits);
number_t *number_const_prec_qcomplex(const number_t *number, size_t precision_bits);
number_t *number_const_prec_qfloat(const number_t *number, size_t precision_bits);
int number_cmp_same_double(const number_t *a, const number_t *b);
int number_cmp_same_mcomplex(const number_t *a, const number_t *b);
int number_cmp_same_mfloat(const number_t *a, const number_t *b);
int number_cmp_same_mint(const number_t *a, const number_t *b);
int number_cmp_same_mrational(const number_t *a, const number_t *b);
int number_cmp_same_qcomplex(const number_t *a, const number_t *b);
int number_cmp_same_qfloat(const number_t *a, const number_t *b);
number_t *number_conj_mcomplex(const number_t *number);
number_t *number_conj_qcomplex(const number_t *number);
number_t number_const_like_double(const number_t *like, number_const_id_t id);
number_t number_const_like_mcomplex(const number_t *like, number_const_id_t id);
number_t number_const_like_mexact(const number_t *like, number_const_id_t id);
number_t number_const_like_mfloat(const number_t *like, number_const_id_t id);
number_t number_const_like_qcomplex(const number_t *like, number_const_id_t id);
number_t number_const_like_qfloat(const number_t *like, number_const_id_t id);
void number_destroy_mcomplex(number_t *number);
void number_destroy_mfloat(number_t *number);
void number_destroy_mint(number_t *number);
void number_destroy_mrational(number_t *number);
void number_destroy_none(number_t *number);
void number_destroy_scope_mcomplex(void *payload);
void number_destroy_scope_mfloat(void *payload);
void number_destroy_scope_mint(void *payload);
void number_destroy_scope_mrational(void *payload);
void number_destroy_scope_none(void *payload);
number_t *number_div_same_double(const number_t *a, const number_t *b);
number_t *number_div_same_mcomplex(const number_t *a, const number_t *b);
number_t *number_div_same_mfloat(const number_t *a, const number_t *b);
number_t *number_div_same_mrational(const number_t *a, const number_t *b);
number_t *number_div_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_div_same_qfloat(const number_t *a, const number_t *b);
bool number_eq_same_double(const number_t *a, const number_t *b);
bool number_eq_same_mcomplex(const number_t *a, const number_t *b);
bool number_eq_same_mfloat(const number_t *a, const number_t *b);
bool number_eq_same_mint(const number_t *a, const number_t *b);
bool number_eq_same_mrational(const number_t *a, const number_t *b);
bool number_eq_same_qcomplex(const number_t *a, const number_t *b);
bool number_eq_same_qfloat(const number_t *a, const number_t *b);
bool number_eq_same_tol_double(const number_t *a, const number_t *b);
bool number_eq_same_tol_mcomplex(const number_t *a, const number_t *b);
bool number_eq_same_tol_mfloat(const number_t *a, const number_t *b);
bool number_eq_same_tol_mint(const number_t *a, const number_t *b);
bool number_eq_same_tol_mrational(const number_t *a, const number_t *b);
bool number_eq_same_tol_qcomplex(const number_t *a, const number_t *b);
bool number_eq_same_tol_qfloat(const number_t *a, const number_t *b);
number_t *number_exp_same_double(const number_t *number);
number_t *number_exp_same_mcomplex(const number_t *number);
number_t *number_exp_same_mfloat(const number_t *number);
number_t *number_exp_same_qcomplex(const number_t *number);
number_t *number_exp_same_qfloat(const number_t *number);
number_t *number_floor_double(const number_t *number);
number_t *number_floor_mcomplex(const number_t *number);
number_t *number_floor_mfloat(const number_t *number);
number_t *number_floor_qcomplex(const number_t *number);
number_t *number_floor_qfloat(const number_t *number);
long number_get_exponent2_double(const number_t *number);
long number_get_exponent2_mfloat(const number_t *number);
long number_get_exponent2_mint(const number_t *number);
long number_get_exponent2_mrational(const number_t *number);
long number_get_exponent2_qfloat(const number_t *number);
long number_get_exponent2_zero(const number_t *number);
size_t number_get_mantissa_bits_double(const number_t *number);
size_t number_get_mantissa_bits_mcomplex(const number_t *number);
size_t number_get_mantissa_bits_mfloat(const number_t *number);
size_t number_get_mantissa_bits_qfloat(const number_t *number);
size_t number_get_mantissa_bits_zero(const number_t *number);
bool number_get_mantissa_u64_false(const number_t *number, uint64_t *out);
bool number_get_mantissa_u64_mcomplex(const number_t *number, uint64_t *out);
bool number_get_mantissa_u64_mfloat(const number_t *number, uint64_t *out);
size_t number_get_precision_mcomplex(const number_t *number);
size_t number_get_precision_mfloat(const number_t *number);
number_t *number_imag_double_zero(const number_t *number);
number_t *number_imag_mcomplex(const number_t *number);
number_t *number_imag_mfloat_zero(const number_t *number);
number_t *number_imag_mint_zero(const number_t *number);
number_t *number_imag_mrational_zero(const number_t *number);
number_t *number_imag_qcomplex(const number_t *number);
number_t *number_imag_qfloat_zero(const number_t *number);
number_t number_imag_const_like_mreal(const number_t *like, number_const_id_t id);
number_t number_imag_const_like_qreal(const number_t *like, number_const_id_t id);
number_t *number_inv_double(const number_t *number);
number_t *number_inv_mcomplex(const number_t *number);
number_t *number_inv_mfloat(const number_t *number);
number_t *number_inv_mrational(const number_t *number);
number_t *number_inv_qcomplex(const number_t *number);
number_t *number_inv_qfloat(const number_t *number);
bool number_is_finite_double(const number_t *number);
bool number_is_finite_exact(const number_t *number);
bool number_is_finite_mcomplex(const number_t *number);
bool number_is_finite_mfloat(const number_t *number);
bool number_is_finite_qcomplex(const number_t *number);
bool number_is_finite_qfloat(const number_t *number);
bool number_is_inf_double(const number_t *number);
bool number_is_inf_exact(const number_t *number);
bool number_is_inf_mcomplex(const number_t *number);
bool number_is_inf_mfloat(const number_t *number);
bool number_is_inf_qcomplex(const number_t *number);
bool number_is_inf_qfloat(const number_t *number);
bool number_is_integer_double(const number_t *number);
bool number_is_integer_mcomplex(const number_t *number);
bool number_is_integer_mfloat(const number_t *number);
bool number_is_integer_mint(const number_t *number);
bool number_is_integer_mrational(const number_t *number);
bool number_is_integer_qcomplex(const number_t *number);
bool number_is_integer_qfloat(const number_t *number);
bool number_is_nan_double(const number_t *number);
bool number_is_nan_exact(const number_t *number);
bool number_is_nan_mcomplex(const number_t *number);
bool number_is_nan_mfloat(const number_t *number);
bool number_is_nan_qcomplex(const number_t *number);
bool number_is_nan_qfloat(const number_t *number);
bool number_is_one_double(const number_t *number);
bool number_is_one_mcomplex(const number_t *number);
bool number_is_one_mfloat(const number_t *number);
bool number_is_one_mint(const number_t *number);
bool number_is_one_mrational(const number_t *number);
bool number_is_one_qcomplex(const number_t *number);
bool number_is_one_qfloat(const number_t *number);
bool number_is_real_default(const number_t *number);
bool number_is_real_mcomplex(const number_t *number);
bool number_is_real_qcomplex(const number_t *number);
bool number_is_zero_double(const number_t *number);
bool number_is_zero_mcomplex(const number_t *number);
bool number_is_zero_mfloat(const number_t *number);
bool number_is_zero_mint(const number_t *number);
bool number_is_zero_mrational(const number_t *number);
bool number_is_zero_qcomplex(const number_t *number);
bool number_is_zero_qfloat(const number_t *number);
number_t *number_ldexp_double(const number_t *number, int exponent2);
number_t *number_ldexp_mcomplex(const number_t *number, int exponent2);
number_t *number_ldexp_mfloat(const number_t *number, int exponent2);
number_t *number_ldexp_qcomplex(const number_t *number, int exponent2);
number_t *number_ldexp_qfloat(const number_t *number, int exponent2);
number_t *number_log_same_double(const number_t *number);
number_t *number_log_same_mcomplex(const number_t *number);
number_t *number_log_same_mfloat(const number_t *number);
number_t *number_log_same_qcomplex(const number_t *number);
number_t *number_log_same_qfloat(const number_t *number);
number_t *number_mul_pow10_double(const number_t *number, int exponent10);
number_t *number_mul_pow10_mfloat(const number_t *number, int exponent10);
number_t *number_mul_pow10_qfloat(const number_t *number, int exponent10);
number_t *number_mul_same_double(const number_t *a, const number_t *b);
number_t *number_mul_same_mcomplex(const number_t *a, const number_t *b);
number_t *number_mul_same_mfloat(const number_t *a, const number_t *b);
number_t *number_mul_same_mint(const number_t *a, const number_t *b);
number_t *number_mul_same_mrational(const number_t *a, const number_t *b);
number_t *number_mul_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_mul_same_qfloat(const number_t *a, const number_t *b);
number_t *number_neg_double(const number_t *number);
number_t *number_neg_mcomplex(const number_t *number);
number_t *number_neg_mfloat(const number_t *number);
number_t *number_neg_mint(const number_t *number);
number_t *number_neg_mrational(const number_t *number);
number_t *number_neg_qcomplex(const number_t *number);
number_t *number_neg_qfloat(const number_t *number);
number_t *number_pow_int_double(const number_t *number, int exponent);
number_t *number_pow_int_mcomplex(const number_t *number, int exponent);
number_t *number_pow_int_mfloat(const number_t *number, int exponent);
number_t *number_pow_int_mint(const number_t *number, int exponent);
number_t *number_pow_int_qcomplex(const number_t *number, int exponent);
number_t *number_pow_int_qfloat(const number_t *number, int exponent);
size_t number_precision_fixed106(const number_t *number);
size_t number_precision_fixed53(const number_t *number);
size_t number_precision_zero(const number_t *number);
number_t *number_real_mcomplex(const number_t *number);
number_t *number_real_qcomplex(const number_t *number);
int number_set_precision_mcomplex(number_t *number, size_t precision_bits);
int number_set_precision_mfloat(number_t *number, size_t precision_bits);
int number_set_precision_noop(number_t *number, size_t precision_bits);
int number_sign_double(const number_t *number);
int number_sign_mfloat(const number_t *number);
int number_sign_mint(const number_t *number);
int number_sign_mrational(const number_t *number);
int number_sign_qfloat(const number_t *number);
int number_sign_zero(const number_t *number);
int number_sincos_double(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_mfloat(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_qfloat(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_real_mfloat(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sinhcosh_double(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_mfloat(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_qfloat(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_real_mfloat(const number_t *number, number_t *sinh_out, number_t *cosh_out);
void *number_scope_payload_mcomplex(const number_t *number);
void *number_scope_payload_mfloat(const number_t *number);
void *number_scope_payload_mint(const number_t *number);
void *number_scope_payload_mrational(const number_t *number);
void *number_scope_payload_none(const number_t *number);
number_t *number_sqrt_same_double(const number_t *number);
number_t *number_sqrt_same_mcomplex(const number_t *number);
number_t *number_sqrt_same_mfloat(const number_t *number);
number_t *number_sqrt_same_qcomplex(const number_t *number);
number_t *number_sqrt_same_qfloat(const number_t *number);
number_t *number_sub_same_double(const number_t *a, const number_t *b);
number_t *number_sub_same_mcomplex(const number_t *a, const number_t *b);
number_t *number_sub_same_mfloat(const number_t *a, const number_t *b);
number_t *number_sub_same_mint(const number_t *a, const number_t *b);
number_t *number_sub_same_mrational(const number_t *a, const number_t *b);
number_t *number_sub_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_sub_same_qfloat(const number_t *a, const number_t *b);
double number_to_double_double(const number_t *number);
double number_to_double_mfloat(const number_t *number);
double number_to_double_qfloat(const number_t *number);
qfloat_t number_to_qfloat_double(const number_t *number);
qfloat_t number_to_qfloat_mfloat(const number_t *number);
qfloat_t number_to_qfloat_qfloat(const number_t *number);
char *number_to_string_double(const number_t *number);
char *number_to_string_mcomplex(const number_t *number);
char *number_to_string_mfloat(const number_t *number);
char *number_to_string_mint(const number_t *number);
char *number_to_string_mrational(const number_t *number);
char *number_to_string_qcomplex(const number_t *number);
char *number_to_string_qfloat(const number_t *number);
bool number_value_is_immortal_double(const number_t *number);
bool number_value_is_immortal_mcomplex(const number_t *number);
bool number_value_is_immortal_mfloat(const number_t *number);
bool number_value_is_immortal_mint(const number_t *number);
bool number_value_is_immortal_mrational(const number_t *number);
bool number_value_is_immortal_qcomplex(const number_t *number);
bool number_value_is_immortal_qfloat(const number_t *number);

#endif
