#ifndef NUMBER_VTABLE_DEFS_H
#define NUMBER_VTABLE_DEFS_H

#include "number_internal.h"

number_t *number_abs_double(const number_t *number);
number_t *number_abs_mpfr(const number_t *number);
number_t *number_abs_mpz(const number_t *number);
number_t *number_abs_mpq(const number_t *number);
number_t *number_abs_qcomplex(const number_t *number);
number_t *number_abs_qfloat(const number_t *number);
number_t *number_add_same_double(const number_t *a, const number_t *b);
number_t *number_add_same_mpfr(const number_t *a, const number_t *b);
number_t *number_add_same_mpz(const number_t *a, const number_t *b);
number_t *number_add_same_mpq(const number_t *a, const number_t *b);
number_t *number_add_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_add_same_qfloat(const number_t *a, const number_t *b);
number_t *number_arg_double(const number_t *number);
number_t *number_arg_qcomplex(const number_t *number);
number_t *number_arg_qfloat(const number_t *number);
number_t *number_clone_double(const number_t *number);
number_t *number_clone_mpfr(const number_t *number);
number_t *number_clone_mpz(const number_t *number);
number_t *number_clone_mpq(const number_t *number);
number_t *number_clone_qcomplex(const number_t *number);
number_t *number_clone_qfloat(const number_t *number);
number_t *number_const_prec_double(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mpfr(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mpz(const number_t *number, size_t precision_bits);
number_t *number_const_prec_mpq(const number_t *number, size_t precision_bits);
number_t *number_const_prec_qcomplex(const number_t *number, size_t precision_bits);
number_t *number_const_prec_qfloat(const number_t *number, size_t precision_bits);
int number_cmp_same_double(const number_t *a, const number_t *b);
int number_cmp_same_mpfr(const number_t *a, const number_t *b);
int number_cmp_same_mpz(const number_t *a, const number_t *b);
int number_cmp_same_mpq(const number_t *a, const number_t *b);
int number_cmp_same_qcomplex(const number_t *a, const number_t *b);
int number_cmp_same_qfloat(const number_t *a, const number_t *b);
number_t *number_conj_qcomplex(const number_t *number);
number_t number_const_like_double(const number_t *like, number_const_id_t id);
number_t number_const_like_mexact(const number_t *like, number_const_id_t id);
number_t number_const_like_mpfr(const number_t *like, number_const_id_t id);
number_t number_const_like_qcomplex(const number_t *like, number_const_id_t id);
number_t number_const_like_qfloat(const number_t *like, number_const_id_t id);
void number_destroy_mpfr(number_t *number);
void number_destroy_mpz(number_t *number);
void number_destroy_mpq(number_t *number);
void number_destroy_none(number_t *number);
void number_destroy_scope_mpfr(void *payload);
void number_destroy_scope_mpz(void *payload);
void number_destroy_scope_mpq(void *payload);
void number_destroy_scope_none(void *payload);
number_t *number_div_same_double(const number_t *a, const number_t *b);
number_t *number_div_same_mpfr(const number_t *a, const number_t *b);
number_t *number_div_same_mpq(const number_t *a, const number_t *b);
number_t *number_div_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_div_same_qfloat(const number_t *a, const number_t *b);
bool number_eq_same_double(const number_t *a, const number_t *b);
bool number_eq_same_mpfr(const number_t *a, const number_t *b);
bool number_eq_same_mpz(const number_t *a, const number_t *b);
bool number_eq_same_mpq(const number_t *a, const number_t *b);
bool number_eq_same_qcomplex(const number_t *a, const number_t *b);
bool number_eq_same_qfloat(const number_t *a, const number_t *b);
bool number_eq_same_tol_double(const number_t *a, const number_t *b);
bool number_eq_same_tol_mpfr(const number_t *a, const number_t *b);
bool number_eq_same_tol_mpz(const number_t *a, const number_t *b);
bool number_eq_same_tol_mpq(const number_t *a, const number_t *b);
bool number_eq_same_tol_qcomplex(const number_t *a, const number_t *b);
bool number_eq_same_tol_qfloat(const number_t *a, const number_t *b);
number_t *number_exp_same_double(const number_t *number);
number_t *number_exp_same_mpfr(const number_t *number);
number_t *number_exp_same_qcomplex(const number_t *number);
number_t *number_exp_same_qfloat(const number_t *number);
number_t *number_floor_double(const number_t *number);
number_t *number_floor_mpfr(const number_t *number);
number_t *number_floor_qcomplex(const number_t *number);
number_t *number_floor_qfloat(const number_t *number);
long number_get_exponent2_double(const number_t *number);
long number_get_exponent2_mpfr(const number_t *number);
long number_get_exponent2_mpz(const number_t *number);
long number_get_exponent2_mpq(const number_t *number);
long number_get_exponent2_qfloat(const number_t *number);
long number_get_exponent2_zero(const number_t *number);
size_t number_get_mantissa_bits_double(const number_t *number);
size_t number_get_mantissa_bits_mpfr(const number_t *number);
size_t number_get_mantissa_bits_qfloat(const number_t *number);
size_t number_get_mantissa_bits_zero(const number_t *number);
bool number_get_mantissa_u64_false(const number_t *number, uint64_t *out);
bool number_get_mantissa_u64_mpfr(const number_t *number, uint64_t *out);
size_t number_get_precision_mpfr(const number_t *number);
size_t number_get_effective_precision_dynamic106(const number_t *number);
number_t *number_imag_double_zero(const number_t *number);
number_t *number_imag_mpfr_zero(const number_t *number);
number_t *number_imag_mpz_zero(const number_t *number);
number_t *number_imag_mpq_zero(const number_t *number);
number_t *number_imag_qcomplex(const number_t *number);
number_t *number_imag_qfloat_zero(const number_t *number);
number_t number_imag_const_like_mpfr(const number_t *like, number_const_id_t id);
number_t number_imag_const_like_qreal(const number_t *like, number_const_id_t id);
number_t *number_inv_double(const number_t *number);
number_t *number_inv_mpfr(const number_t *number);
number_t *number_inv_mpq(const number_t *number);
number_t *number_inv_qcomplex(const number_t *number);
number_t *number_inv_qfloat(const number_t *number);
bool number_is_finite_double(const number_t *number);
bool number_is_finite_exact(const number_t *number);
bool number_is_finite_mpfr(const number_t *number);
bool number_is_finite_qcomplex(const number_t *number);
bool number_is_finite_qfloat(const number_t *number);
bool number_is_inf_double(const number_t *number);
bool number_is_inf_exact(const number_t *number);
bool number_is_inf_mpfr(const number_t *number);
bool number_is_inf_qcomplex(const number_t *number);
bool number_is_inf_qfloat(const number_t *number);
bool number_is_integer_double(const number_t *number);
bool number_is_integer_mpfr(const number_t *number);
bool number_is_integer_mpz(const number_t *number);
bool number_is_integer_mpq(const number_t *number);
bool number_is_integer_qcomplex(const number_t *number);
bool number_is_integer_qfloat(const number_t *number);
bool number_is_nan_double(const number_t *number);
bool number_is_nan_exact(const number_t *number);
bool number_is_nan_mpfr(const number_t *number);
bool number_is_nan_qcomplex(const number_t *number);
bool number_is_nan_qfloat(const number_t *number);
bool number_is_one_double(const number_t *number);
bool number_is_one_mpfr(const number_t *number);
bool number_is_one_mpz(const number_t *number);
bool number_is_one_mpq(const number_t *number);
bool number_is_one_qcomplex(const number_t *number);
bool number_is_one_qfloat(const number_t *number);
bool number_is_real_default(const number_t *number);
bool number_is_real_qcomplex(const number_t *number);
bool number_is_zero_double(const number_t *number);
bool number_is_zero_mpfr(const number_t *number);
bool number_is_zero_mpz(const number_t *number);
bool number_is_zero_mpq(const number_t *number);
bool number_is_zero_qcomplex(const number_t *number);
bool number_is_zero_qfloat(const number_t *number);
number_t *number_ldexp_double(const number_t *number, int exponent2);
number_t *number_ldexp_mpfr(const number_t *number, int exponent2);
number_t *number_ldexp_qcomplex(const number_t *number, int exponent2);
number_t *number_ldexp_qfloat(const number_t *number, int exponent2);
number_t *number_log_same_double(const number_t *number);
number_t *number_log_same_mpfr(const number_t *number);
number_t *number_log_same_qcomplex(const number_t *number);
number_t *number_log_same_qfloat(const number_t *number);
number_t *number_mul_pow10_double(const number_t *number, int exponent10);
number_t *number_mul_pow10_mpfr(const number_t *number, int exponent10);
number_t *number_mul_pow10_qfloat(const number_t *number, int exponent10);
number_t *number_mul_same_double(const number_t *a, const number_t *b);
number_t *number_mul_same_mpfr(const number_t *a, const number_t *b);
number_t *number_mul_same_mpz(const number_t *a, const number_t *b);
number_t *number_mul_same_mpq(const number_t *a, const number_t *b);
number_t *number_mul_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_mul_same_qfloat(const number_t *a, const number_t *b);
number_t *number_neg_double(const number_t *number);
number_t *number_neg_mpfr(const number_t *number);
number_t *number_neg_mpz(const number_t *number);
number_t *number_neg_mpq(const number_t *number);
number_t *number_neg_qcomplex(const number_t *number);
number_t *number_neg_qfloat(const number_t *number);
number_t *number_pow_int_double(const number_t *number, int exponent);
number_t *number_pow_int_mpfr(const number_t *number, int exponent);
number_t *number_pow_int_mpz(const number_t *number, int exponent);
number_t *number_pow_int_mpq(const number_t *number, int exponent);
number_t *number_pow_int_qcomplex(const number_t *number, int exponent);
number_t *number_pow_int_qfloat(const number_t *number, int exponent);
size_t number_precision_fixed106(const number_t *number);
size_t number_precision_fixed53(const number_t *number);
size_t number_precision_zero(const number_t *number);
number_t *number_real_qcomplex(const number_t *number);
int number_set_precision_mpfr(number_t *number, size_t precision_bits);
int number_set_precision_noop(number_t *number, size_t precision_bits);
int number_sign_double(const number_t *number);
int number_sign_mpfr(const number_t *number);
int number_sign_mpz(const number_t *number);
int number_sign_mpq(const number_t *number);
int number_sign_qfloat(const number_t *number);
int number_sign_zero(const number_t *number);
int number_sincos_double(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_mpfr(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_qfloat(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sincos_real_mpfr(const number_t *number, number_t *sin_out, number_t *cos_out);
int number_sinhcosh_double(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_mpfr(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_qfloat(const number_t *number, number_t *sinh_out, number_t *cosh_out);
int number_sinhcosh_real_mpfr(const number_t *number, number_t *sinh_out, number_t *cosh_out);
void *number_scope_payload_mpfr(const number_t *number);
void *number_scope_payload_mpz(const number_t *number);
void *number_scope_payload_mpq(const number_t *number);
void *number_scope_payload_none(const number_t *number);
number_t *number_sqrt_same_double(const number_t *number);
number_t *number_sqrt_same_mpfr(const number_t *number);
number_t *number_sqrt_same_qcomplex(const number_t *number);
number_t *number_sqrt_same_qfloat(const number_t *number);
number_t *number_sub_same_double(const number_t *a, const number_t *b);
number_t *number_sub_same_mpfr(const number_t *a, const number_t *b);
number_t *number_sub_same_mpz(const number_t *a, const number_t *b);
number_t *number_sub_same_mpq(const number_t *a, const number_t *b);
number_t *number_sub_same_qcomplex(const number_t *a, const number_t *b);
number_t *number_sub_same_qfloat(const number_t *a, const number_t *b);
double number_to_double_double(const number_t *number);
double number_to_double_mpfr(const number_t *number);
double number_to_double_qfloat(const number_t *number);
qfloat_t number_to_qfloat_double(const number_t *number);
qfloat_t number_to_qfloat_mpfr(const number_t *number);
qfloat_t number_to_qfloat_qfloat(const number_t *number);
char *number_to_string_double(const number_t *number);
char *number_to_string_mpfr(const number_t *number);
char *number_to_string_mpz(const number_t *number);
char *number_to_string_mpq(const number_t *number);
char *number_to_string_qcomplex(const number_t *number);
char *number_to_string_qfloat(const number_t *number);
bool number_immortal_id_mpfr(const number_t *number, number_const_id_t *id_out);
bool number_immortal_id_cdouble(const number_t *number,
                                    number_const_id_t *id_out);
bool number_immortal_id_mpz(const number_t *number, number_const_id_t *id_out);
bool number_immortal_id_mpq(const number_t *number, number_const_id_t *id_out);
bool number_value_is_immortal_double(const number_t *number);
bool number_value_is_immortal_mpfr(const number_t *number);
bool number_value_is_immortal_mpz(const number_t *number);
bool number_value_is_immortal_mpq(const number_t *number);
bool number_value_is_immortal_qcomplex(const number_t *number);
bool number_value_is_immortal_qfloat(const number_t *number);

number_t *number_abs_cdouble(const number_t *number);
number_t *number_add_same_cdouble(const number_t *a, const number_t *b);
number_t *number_arg_cdouble(const number_t *number);
number_t *number_clone_cdouble(const number_t *number);
number_t *number_const_prec_cdouble(const number_t *number,
                                        size_t precision_bits);
int number_cmp_same_cdouble(const number_t *a, const number_t *b);
number_t *number_conj_cdouble(const number_t *number);
number_t number_const_like_cdouble(const number_t *like, number_const_id_t id);
number_t number_imag_const_like_cdouble(const number_t *like, number_const_id_t id);
number_t *number_div_same_cdouble(const number_t *a, const number_t *b);
bool number_eq_same_cdouble(const number_t *a, const number_t *b);
bool number_eq_same_tol_cdouble(const number_t *a, const number_t *b);
number_t *number_exp_same_cdouble(const number_t *number);
number_t *number_floor_cdouble(const number_t *number);
char *number_format_cdouble(const number_t *number, bool scientific, int precision);
number_t *number_imag_cdouble(const number_t *number);
number_t *number_inv_cdouble(const number_t *number);
bool number_is_finite_cdouble(const number_t *number);
bool number_is_inf_cdouble(const number_t *number);
bool number_is_integer_cdouble(const number_t *number);
bool number_is_nan_cdouble(const number_t *number);
bool number_is_one_cdouble(const number_t *number);
bool number_is_real_cdouble(const number_t *number);
bool number_is_zero_cdouble(const number_t *number);
number_t *number_ldexp_cdouble(const number_t *number, int exponent2);
number_t *number_log_same_cdouble(const number_t *number);
number_t *number_mul_pow10_cdouble(const number_t *number, int exponent10);
number_t *number_mul_same_cdouble(const number_t *a, const number_t *b);
number_t *number_neg_cdouble(const number_t *number);
number_t *number_pow_int_cdouble(const number_t *number, int exponent);
number_t *number_real_cdouble(const number_t *number);
number_t *number_sqrt_same_cdouble(const number_t *number);
number_t *number_sub_same_cdouble(const number_t *a, const number_t *b);
char *number_to_string_cdouble(const number_t *number);
bool number_value_is_immortal_cdouble(const number_t *number);

void number_destroy_complex(number_t *number);
void *number_scope_payload_complex(const number_t *number);
void number_destroy_scope_complex(void *payload);
number_t *number_clone_complex(const number_t *number);
number_t *number_const_prec_complex(const number_t *number, size_t precision_bits);
char *number_to_string_complex(const number_t *number);
bool number_value_is_immortal_complex(const number_t *number);
bool number_immortal_id_complex(const number_t *number, number_const_id_t *id_out);
bool number_is_real_complex(const number_t *number);
bool number_is_zero_complex(const number_t *number);
bool number_is_one_complex(const number_t *number);
bool number_is_finite_complex(const number_t *number);
bool number_is_nan_complex(const number_t *number);
bool number_is_inf_complex(const number_t *number);
bool number_eq_same_complex(const number_t *a, const number_t *b);
bool number_eq_same_tol_complex(const number_t *a, const number_t *b);
int number_cmp_same_complex(const number_t *a, const number_t *b);
number_t number_const_like_complex(const number_t *like, number_const_id_t id);
char *number_format_complex(const number_t *number, bool scientific, int precision);
int number_set_precision_complex(number_t *number, size_t precision_bits);
size_t number_get_precision_complex(const number_t *number);
bool number_is_integer_complex(const number_t *number);
size_t number_get_mantissa_bits_complex(const number_t *number);
bool number_get_mantissa_u64_complex(const number_t *number, uint64_t *out);
number_t *number_neg_complex(const number_t *number);
number_t *number_abs_complex(const number_t *number);
number_t *number_inv_complex(const number_t *number);
number_t *number_conj_complex(const number_t *number);
number_t *number_real_complex(const number_t *number);
number_t *number_imag_complex(const number_t *number);
number_t *number_arg_complex(const number_t *number);
number_t *number_pow_int_complex(const number_t *number, int exponent);
number_t *number_ldexp_complex(const number_t *number, int exponent2);
number_t *number_floor_complex(const number_t *number);
number_t *number_add_same_complex(const number_t *a, const number_t *b);
number_t *number_sub_same_complex(const number_t *a, const number_t *b);
number_t *number_mul_same_complex(const number_t *a, const number_t *b);
number_t *number_div_same_complex(const number_t *a, const number_t *b);
number_t *number_exp_same_complex(const number_t *number);
number_t *number_log_same_complex(const number_t *number);
number_t *number_sqrt_same_complex(const number_t *number);

#endif
