#!/bin/sh

set -eu

repository_root=$(git rev-parse --show-toplevel)
make --no-print-directory -s -j1 -C "$repository_root" DEBUG=0 native-checks
"$repository_root/tools/mars_checks/build/release/mars_checks" public-distribution
exec "$repository_root/tools/mars_checks/build/release/mars_checks" compliance
