/**
 * @file test_cfg_locales.c
 * @brief Native calendar-locale generator contract and packaged-data regressions.
 *
 * Runs the configuration executable sequentially in disposable directories, without
 * installing a jurisdiction database or invoking the retired generator. Generated SQL
 * is compared with the packaged body and queried through the public encrypted SQLite
 * API. Invalid inputs must not publish partial SQL or replace an existing destination.
 * The documented check command registers separately, after all ordinary test groups.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "file.h"
#include "json.h"
#include "lab_process.h"
#include "sqlite.h"
#include "test_cfg_support.h"
#include "test_harness.h"

static const char *const test_cfg_locales_check_message =
    "Calendar locale seed matches Babel 2.17.0 / CLDR 46 and explicit supplements.\n";

static file_t *test_cfg_locales_file(const char *directory, const char *name)
{
    string_t *path = string_new();
    bool ok = path && string_append_utf8_exact(path, directory, strlen(directory)) == 0 &&
              string_append_utf8_exact(path, "/", 1) == 0 && string_append_utf8_exact(path, name, strlen(name)) == 0;
    file_t *file = ok ? file_new(path) : NULL;
    string_free(path);
    return file;
}

static bool test_cfg_locales_environment(void)
{
    return !setenv("MARS_ROOT", MARS_CONFIG_ROOT_DIR, 1);
}

static bool test_cfg_locales_run(const char *directory, const char *const *options, size_t count, int expected_status,
                                 string_t **output)
{
    const char *args[18] = {MARS_CONFIG_PROGRAM, "locales"};
    if (count > 15)
        return false;
    for (size_t i = 0; i < count; ++i)
        args[i + 2] = options[i];
    int status = -1;
    bool ran = lab_proc_run(args, directory, 60000, 4u * 1024u * 1024u, output, &status);
    bool ok = ran && status == expected_status;
    if (!ok)
        string_fprintf(stderr, "Locale generator: expected exit %d, got %d (collection %d): %S\n", expected_status,
                       status, ran, *output);
    return ok;
}

static bool test_cfg_locales_no_sql(const string_t *output)
{
    /* Diagnostics may be present in the merged stream, but no generated SQL may leak. */
    return output && string_find(output, "create table if not exists calendar_") < 0 &&
           string_find(output, "insert or replace into calendar_") < 0 && string_find(output, "-- Generated by ") < 0;
}

static bool test_cfg_locales_matches(file_t *file, const string_t *expected)
{
    string_t *actual = file ? file_read_all_text(file) : NULL;
    bool ok = actual && expected && string_view_equals_view(string_view_all(actual), string_view_all(expected));
    string_free(actual);
    return ok;
}

static bool test_cfg_locales_body_equal(const string_t *actual, const string_t *expected)
{
    /* Native provenance may differ; every byte from the first DDL statement must agree. */
    const char *first = "create table if not exists calendar_territory_locale (";
    string_offset_t a = actual ? string_find(actual, first) : -1;
    string_offset_t b = expected ? string_find(expected, first) : -1;
    bool ok = a >= 0 && b >= 0 &&
              string_view_equals_view(string_view(actual, (size_t)a, string_byte_length(actual) - (size_t)a),
                                      string_view(expected, (size_t)b, string_byte_length(expected) - (size_t)b));
    if (!ok)
        string_fprintf(stderr, "Native locale SQL body differs from the packaged reference\n");
    return ok;
}

static bool test_cfg_locales_query(sqlite_t *db, const char *sql, const char *expected)
{
    sqlite_stmt_t *stmt = sqlite_stmt_prepare(db, sql);
    bool ok = stmt && sqlite_stmt_step(stmt) == SQLITE_STEP_ROW;
    const char *raw = ok ? sqlite_stmt_column_text(stmt, 0) : NULL;
    string_t *value = raw ? string_new() : NULL;
    ok = ok && value && string_append_utf8_exact(value, raw, strlen(raw)) == 0 &&
         string_view_equals_literal(string_view_all(value), expected) && sqlite_stmt_step(stmt) == SQLITE_STEP_DONE;
    if (!ok)
        string_fprintf(stderr, "Generated locale query failed: %s; expected %s, got %S\n", sql, expected, value);
    string_free(value);
    sqlite_stmt_finalize(stmt);
    return ok;
}

static bool test_cfg_locales_parity_fixture(const char *directory)
{
    file_t *reference = file_new_cstr(MARS_CONFIG_ROOT_DIR "/packaging/jurisdiction-db/mars_calendar_locale_names.sql");
    string_t *expected = reference ? file_read_all_text(reference) : NULL;
    string_t *output = NULL;
    bool ok = expected && test_cfg_locales_environment() && test_cfg_locales_run(directory, NULL, 0, 0, &output) &&
              test_cfg_locales_body_equal(output, expected);
    string_t *path = string_sprintf("%s/generated.db", directory);
    string_t *key = string_new_with("locale-generator-regression-only");
    sqlite_t *db = ok && path && key ? sqlite_open_encrypted(path, key) : NULL;
    ok = ok && db && sqlite_exec(db, output) &&
         test_cfg_locales_query(db, "SELECT locale FROM calendar_territory_locale WHERE territory='CA-QC'", "fr_CA") &&
         test_cfg_locales_query(db, "SELECT native_name FROM calendar_language_name WHERE language='haw'",
                                "ʻŌlelo Hawaiʻi") &&
         test_cfg_locales_query(db, "SELECT full_name FROM calendar_locale_month WHERE locale='ar_DZ' AND month_no=1",
                                "جانفي") &&
         test_cfg_locales_query(db, "SELECT full_name FROM calendar_locale_month WHERE locale='la_VA' AND month_no=6",
                                "Iunii") &&
         test_cfg_locales_query(
             db, "SELECT full_name FROM calendar_locale_month_standalone WHERE locale='la_VA' AND month_no=6",
             "Iunius") &&
         test_cfg_locales_query(db, "SELECT cldr_pattern FROM calendar_locale_date_pattern WHERE locale='gd_GB'",
                                "d'mh' MMMM y") &&
         test_cfg_locales_query(
             db,
             "SELECT literal FROM calendar_date_pattern_part p JOIN "
             "calendar_locale_date_pattern l USING(pattern_id) WHERE l.locale='fr_CA' AND p.field='first_day_suffix'",
             "ᵉʳ");
    sqlite_close(db);
    string_free(key);
    string_free(path);
    string_free(output);
    string_free(expected);
    file_free(reference);
    return ok;
}

static bool test_cfg_locales_output_fixture(const char *directory)
{
    file_t *destination = test_cfg_locales_file(directory, "locale output 'é.sql");
    string_t *sentinel = string_new_with("existing output must survive failures\n");
    const char *args[] = {"--output", destination ? file_path(destination) : ""};
    string_t *stdout_sql = NULL, *messages = NULL;
    bool ok = destination && sentinel && file_write_all_text(destination, sentinel) && test_cfg_locales_environment() &&
              test_cfg_locales_run(directory, NULL, 0, 0, &stdout_sql) &&
              test_cfg_locales_run(directory, args, 2, 0, &messages) && test_cfg_locales_no_sql(messages) &&
              test_cfg_locales_matches(destination, stdout_sql);
    string_free(messages);
    messages = NULL;
    ok = ok && test_cfg_locales_run(directory, args, 2, 0, &messages) &&
         test_cfg_locales_matches(destination, stdout_sql);
    string_free(messages);
    messages = NULL;
    const char *bad_destination[] = {"--output", directory};
    ok = ok && test_cfg_locales_run(directory, bad_destination, 2, 1, &messages) && test_cfg_locales_no_sql(messages) &&
         test_cfg_locales_matches(destination, stdout_sql);
    string_free(messages);
    string_free(stdout_sql);
    string_free(sentinel);
    file_free(destination);
    return ok;
}

static bool test_cfg_locales_cli_fixture(const char *directory)
{
    const struct {
        size_t count;
        const char *args[5];
    } invalid[] = {{1, {"--unknown"}},
                   {1, {"--patch"}},
                   {1, {"--output"}},
                   {1, {"--data-dir"}},
                   {1, {"unexpected"}},
                   {2, {"--output", ""}},
                   {2, {"--data-dir", ""}},
                   {3, {"--check", "--output", "untouched.sql"}},
                   {2, {"--check", "--check"}},
                   {4, {"--output", "one.sql", "--output", "two.sql"}},
                   {4, {"--data-dir", "one", "--data-dir", "two"}}};
    bool ok = test_cfg_locales_environment();
    for (size_t i = 0; ok && i < sizeof invalid / sizeof *invalid; ++i) {
        string_t *output = NULL;
        ok = test_cfg_locales_run(directory, invalid[i].args, invalid[i].count, 2, &output) &&
             test_cfg_locales_no_sql(output);
        string_free(output);
    }
    const char *names[] = {"untouched.sql", "one.sql", "two.sql", "config", "jurisdiction"};
    for (size_t i = 0; ok && i < sizeof names / sizeof *names; ++i) {
        file_t *file = test_cfg_locales_file(directory, names[i]);
        ok = file && !file_exists(file);
        file_free(file);
    }
    return ok;
}

static bool test_cfg_locales_missing_fixture(const char *directory)
{
    file_t *empty = test_cfg_locales_file(directory, "empty-data");
    file_t *output_file = test_cfg_locales_file(directory, "preserved.sql");
    string_t *sentinel = string_new_with("preserved previous generation\n");
    bool ok = empty && output_file && sentinel && test_cfg_locales_environment() &&
              file_create_directory(empty, 0700, false) && file_write_all_text(output_file, sentinel);
    const char *data_paths[] = {"missing-data", "empty-data"};
    for (size_t i = 0; ok && i < 2; ++i) {
        const char *args[] = {"--data-dir", data_paths[i], "--output", "preserved.sql"};
        string_t *output = NULL;
        ok = test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(output_file, sentinel);
        string_free(output);
        output = NULL;
        ok = ok && test_cfg_locales_run(directory, args, 2, 1, &output) && test_cfg_locales_no_sql(output);
        string_free(output);
    }
    string_t *output = NULL;
    const char *new_args[] = {"--data-dir", "missing-data", "--output", "not-created.sql"};
    file_t *new_file = test_cfg_locales_file(directory, "not-created.sql");
    ok = ok && new_file && test_cfg_locales_run(directory, new_args, 4, 1, &output) &&
         test_cfg_locales_no_sql(output) && !file_exists(new_file);
    string_free(output);
    file_free(new_file);
    string_free(sentinel);
    file_free(output_file);
    file_free(empty);
    return ok;
}

static const json_t *test_cfg_locales_member(const json_t *object, const char *name)
{
    string_t *key = string_new_with(name);
    const json_t *value = key ? json_object_get(object, key) : NULL;
    string_free(key);
    return value;
}

static bool test_cfg_locales_copy_input(const char *directory, const char *name)
{
    file_t *source = test_cfg_locales_file(MARS_CONFIG_ROOT_DIR "/tools/mars_config/data/locales", name);
    file_t *target = test_cfg_locales_file(directory, name);
    bool ok = source && target && file_copy(source, target, true);
    file_free(target);
    file_free(source);
    return ok;
}

static bool test_cfg_locales_copy_data(const char *directory)
{
    file_t *folder = file_new_cstr(directory);
    bool ok = folder && file_create_directory(folder, 0700, false) &&
              test_cfg_locales_copy_input(directory, "cldr46.json") &&
              test_cfg_locales_copy_input(directory, "supplements.json");
    file_t *manifest_file = test_cfg_locales_file(directory, "cldr46.json");
    string_t *text = ok && manifest_file ? file_read_all_text(manifest_file) : NULL;
    json_t *manifest = text ? json_from_text(text) : NULL;
    const json_t *files = manifest ? test_cfg_locales_member(manifest, "locale_files") : NULL;
    size_t count = files ? json_array_size(files) : 0;
    ok = ok && count > 0 && count <= 32;
    for (size_t i = 0; ok && i < count; ++i) {
        const string_t *name = json_string_value(json_array_get(files, i));
        ok = name && string_find(name, "/") < 0 && string_find(name, "..") < 0 &&
             test_cfg_locales_copy_input(directory, string_c_str(name));
    }
    json_free(manifest);
    string_free(text);
    file_free(manifest_file);
    file_free(folder);
    return ok;
}

static void test_cfg_locales_space(string_view_t view, string_pos_t *at)
{
    unsigned char ch;
    while (string_view_peek_ascii(view, *at, &ch) && (ch == ' ' || ch == '\n' || ch == '\r' || ch == '\t'))
        ++*at;
}

static bool test_cfg_locales_value_end(string_view_t view, string_pos_t *at, unsigned depth)
{
    /* Structural scanning of the checked-in JSON; generated invalid inputs go only to the engine. */
    if (depth > 32)
        return false;
    test_cfg_locales_space(view, at);
    unsigned char ch;
    if (!string_view_peek_ascii(view, *at, &ch))
        return false;
    if (ch == '"') {
        ++*at;
        uint32_t scalar;
        string_pos_t next;
        while (string_view_peek_rune_value(view, *at, &scalar, &next)) {
            *at = next;
            if (scalar == '"')
                return true;
            if (scalar == '\\') {
                if (!string_view_peek_rune_value(view, *at, &scalar, &next))
                    return false;
                *at = next;
            }
        }
        return false;
    }
    if (ch == '{' || ch == '[') {
        unsigned char close = ch == '{' ? '}' : ']';
        ++*at;
        while (*at < string_view_length(view)) {
            test_cfg_locales_space(view, at);
            if (!string_view_peek_ascii(view, *at, &ch))
                return false;
            if (ch == close) {
                ++*at;
                return true;
            }
            if (ch == ',' || ch == ':')
                ++*at;
            else if (!test_cfg_locales_value_end(view, at, depth + 1))
                return false;
        }
        return false;
    }
    string_pos_t start = *at;
    while (string_view_peek_ascii(view, *at, &ch) && ch != ',' && ch != '}' && ch != ']' && ch != ' ' && ch != '\n' &&
           ch != '\r' && ch != '\t')
        ++*at;
    return *at > start;
}

static bool test_cfg_locales_field(const string_t *text, string_pos_t at, const char *const *path, size_t depth,
                                   string_pos_t *start, string_pos_t *end)
{
    string_view_t view = string_view_all(text);
    unsigned char ch;
    test_cfg_locales_space(view, &at);
    if (!depth || depth > 8 || !string_view_peek_ascii(view, at, &ch) || ch != '{')
        return false;
    ++at;
    while (at < string_view_length(view)) {
        test_cfg_locales_space(view, &at);
        string_pos_t key_start = at;
        if (!string_view_peek_ascii(view, at, &ch) || ch != '"' || !test_cfg_locales_value_end(view, &at, 0))
            return false;
        string_t *encoded_key = string_substr(text, key_start, at - key_start);
        json_t *key = encoded_key ? json_from_text(encoded_key) : NULL;
        const string_t *name = key ? json_string_value(key) : NULL;
        bool match = name && string_view_equals_literal(string_view_all(name), path[0]);
        json_free(key);
        string_free(encoded_key);
        test_cfg_locales_space(view, &at);
        if (!string_view_peek_ascii(view, at, &ch) || ch != ':')
            return false;
        ++at;
        test_cfg_locales_space(view, &at);
        string_pos_t value_start = at;
        if (!test_cfg_locales_value_end(view, &at, 0))
            return false;
        if (match) {
            *start = value_start;
            *end = at;
            return depth == 1 || test_cfg_locales_field(text, value_start, path + 1, depth - 1, start, end);
        }
        test_cfg_locales_space(view, &at);
        if (!string_view_peek_ascii(view, at, &ch) || ch != ',')
            return false;
        ++at;
    }
    return false;
}

static bool test_cfg_locales_replace(const char *directory, const char *file_name, const char *const *path,
                                     size_t depth, const char *replacement)
{
    file_t *file = test_cfg_locales_file(directory, file_name);
    string_t *text = file ? file_read_all_text(file) : NULL;
    string_pos_t start = 0, end = 0;
    string_t *changed = string_new();
    bool ok = text && changed && test_cfg_locales_field(text, 0, path, depth, &start, &end) &&
              string_append_utf8_exact(changed, string_c_str(text), start) == 0 &&
              string_append_utf8_exact(changed, replacement, strlen(replacement)) == 0 &&
              string_append_utf8_exact(changed, string_c_str(text) + end, string_byte_length(text) - end) == 0 &&
              file_write_all_text(file, changed);
    string_free(changed);
    string_free(text);
    file_free(file);
    return ok;
}

static bool test_cfg_locales_fragment_paths(const char *directory, const char *data, file_t *destination,
                                            const string_t *sentinel)
{
    file_t *manifest_file = test_cfg_locales_file(data, "cldr46.json");
    string_t *text = manifest_file ? file_read_all_text(manifest_file) : NULL;
    json_t *manifest = text ? json_from_text(text) : NULL;
    const json_t *files = manifest ? test_cfg_locales_member(manifest, "locale_files") : NULL;
    const string_t *first = files ? json_string_value(json_array_get(files, 0)) : NULL;
    file_t *source = first ? test_cfg_locales_file(data, string_c_str(first)) : NULL;
    file_t *outside = test_cfg_locales_file(directory, "outside.json");
    bool ok = source && outside && file_copy(source, outside, true);
    const char *invalid[] = {"missing-fragment.json", "../outside.json", outside ? file_path(outside) : ""};
    const char *field[] = {"locale_files"};
    for (size_t i = 0; ok && i < sizeof invalid / sizeof *invalid; ++i) {
        json_t *list = json_new_array();
        string_t *name = string_new_with(invalid[i]);
        json_t *item = name ? json_new_string(name) : NULL;
        ok = list && item && json_array_append(list, item);
        for (size_t j = 1; ok && j < json_array_size(files); ++j)
            ok = json_array_append(list, json_array_get(files, j));
        /* A few ASCII filenames only; never re-serialise the large source tree. */
        string_t *replacement = ok ? json_to_string(list) : NULL;
        ok = ok && replacement && test_cfg_locales_replace(data, "cldr46.json", field, 1, string_c_str(replacement));
        string_t *output = NULL;
        const char *args[] = {"--data-dir", data, "--output", "preserved.sql"};
        ok = ok && test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(destination, sentinel);
        string_free(output);
        string_free(replacement);
        json_free(item);
        string_free(name);
        json_free(list);
        ok = test_cfg_locales_copy_input(data, "cldr46.json") && ok;
    }
    file_free(outside);
    file_free(source);
    json_free(manifest);
    string_free(text);
    file_free(manifest_file);
    return ok;
}

static bool test_cfg_locales_validation_fixture(const char *directory)
{
    string_t *data = string_sprintf("%s/source", directory);
    file_t *destination = test_cfg_locales_file(directory, "preserved.sql");
    string_t *sentinel = string_new_with("previous valid SQL must remain unchanged\n");
    bool ok = data && destination && sentinel && test_cfg_locales_environment() &&
              test_cfg_locales_copy_data(string_c_str(data)) && file_write_all_text(destination, sentinel) &&
              test_cfg_locales_fragment_paths(directory, string_c_str(data), destination, sentinel);
    const struct {
        const char *file;
        size_t depth;
        const char *path[3];
        const char *replacement;
    } cases[] = {{"cldr46.json", 1, {"format"}, "\"mars-cldr-resolved-99\""},
                 {"cldr46.json", 1, {"babel"}, "\"0.0.0\""},
                 {"cldr46.json", 1, {"cldr"}, "\"99\""},
                 {"cldr46.json", 1, {"territories"}, "{}"},
                 {"cldr46.json", 1, {"locale_files"}, "[]"},
                 {"cldr46.json", 1, {"locale_files"}, "[\"../outside.json\"]"},
                 {"supplements.json", 1, {"format"}, "\"mars-calendar-supplements-99\""},
                 {"supplements.json", 2, {"locales", "frc"}, "{}"},
                 {"supplements.json", 3, {"locales", "frc", "months"}, "[]"},
                 {"supplements.json", 3, {"locales", "frc", "weekdays"}, "[]"},
                 {"cldr46-locales-00.json", 2, {"aa", "months"}, "[]"},
                 {"supplements.json", 3, {"locales", "frc", "date_pattern"}, "\"d MMMM yyyy\""},
                 {"supplements.json", 3, {"locales", "frc", "date_pattern"}, "\"EEEE, d MMMM y\""},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"a\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"zz\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"00\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"c0af\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"eda080\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"e282\"}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":null}"},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "{\"utf8_hex\":\"61\",\"extra\":true}"},
                 /* These files remain ASCII: decoded strings must not bypass the lossless hex representation. */
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "\"Caf\\u00e9\""},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "\"Cafe\\u0301\""},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "\"before\\u0000after\""},
                 {"supplements.json", 3, {"locales", "frc", "native_name"}, "\"\\ud83d\\ude00\""}};
    for (size_t i = 0; ok && i < sizeof cases / sizeof *cases; ++i) {
        string_fprintf(stderr, "Locale validation fixture %zu: %s/%s\n", i, cases[i].file, cases[i].path[0]);
        ok = test_cfg_locales_replace(string_c_str(data), cases[i].file, cases[i].path, cases[i].depth,
                                      cases[i].replacement);
        const char *args[] = {"--data-dir", string_c_str(data), "--output", "preserved.sql"};
        string_t *output = NULL;
        ok = ok && test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(destination, sentinel);
        string_free(output);
        ok = test_cfg_locales_copy_input(string_c_str(data), cases[i].file) && ok;
    }
    /* Exercise amplification guards with tiny inputs, without constructing a large generated SQL result. */
    const struct {
        size_t length;
        size_t depth;
        const char *path[3];
        const char *unit;
    } limits[] = {{1025, 3, {"locales", "frc", "date_pattern"}, "d"}, {257, 2, {"first_day_suffixes", "fr"}, "s"}};
    for (size_t i = 0; ok && i < sizeof limits / sizeof *limits; ++i) {
        string_fprintf(stderr, "Locale validation limit: %s, %zu ASCII bytes\n", limits[i].path[limits[i].depth - 1],
                       limits[i].length);
        string_t *replacement = string_new_with("\"");
        ok = replacement != NULL;
        for (size_t j = 0; ok && j < limits[i].length; ++j)
            ok = string_append_utf8_exact(replacement, limits[i].unit, 1) == 0;
        ok = ok && string_append_utf8_exact(replacement, "\"", 1) == 0 &&
             test_cfg_locales_replace(string_c_str(data), "supplements.json", limits[i].path, limits[i].depth,
                                      string_c_str(replacement));
        const char *args[] = {"--data-dir", string_c_str(data), "--output", "preserved.sql"};
        string_t *output = NULL;
        ok = ok && test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(destination, sentinel);
        string_free(output);
        string_free(replacement);
        ok = test_cfg_locales_copy_input(string_c_str(data), "supplements.json") && ok;
    }
    const char *malformed[] = {"{", "{}", "[]", "null", "{\"format\":\"mars-cldr-resolved-1\",\"babel\":}"};
    file_t *manifest = data ? test_cfg_locales_file(string_c_str(data), "cldr46.json") : NULL;
    for (size_t i = 0; ok && i < sizeof malformed / sizeof *malformed; ++i) {
        string_t *text = string_new_with(malformed[i]), *output = NULL;
        const char *args[] = {"--data-dir", string_c_str(data), "--output", "preserved.sql"};
        ok = text && manifest && file_write_all_text(manifest, text) &&
             test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(destination, sentinel);
        string_free(output);
        output = NULL;
        ok = ok && test_cfg_locales_run(directory, args, 2, 1, &output) && test_cfg_locales_no_sql(output);
        string_free(output);
        string_free(text);
    }
    /* Far below the 4 MiB byte limit, but deep enough to expose a post-parse-only depth check. */
    string_t *nested = string_new_with("{\"format\":\"mars-cldr-resolved-1\",\"padding\":");
    for (size_t i = 0; ok && nested && i < 32768; ++i)
        ok = string_append_utf8_exact(nested, "[", 1) == 0;
    ok = ok && nested && string_append_utf8_exact(nested, "0", 1) == 0;
    for (size_t i = 0; ok && i < 32768; ++i)
        ok = string_append_utf8_exact(nested, "]", 1) == 0;
    ok = ok && string_append_utf8_exact(nested, "}", 1) == 0 && string_byte_length(nested) < 4u * 1024u * 1024u;
    for (size_t truncated = 0; ok && truncated < 2; ++truncated) {
        string_t *output = NULL;
        const char *args[] = {"--data-dir", string_c_str(data), "--output", "preserved.sql"};
        string_fprintf(stderr, "Locale validation: 32768 nested arrays, truncated=%zu\n", truncated);
        ok = file_write_all_bytes(manifest, string_c_str(nested), string_byte_length(nested) - truncated) &&
             test_cfg_locales_run(directory, args, 4, 1, &output) && test_cfg_locales_no_sql(output) &&
             test_cfg_locales_matches(destination, sentinel);
        string_free(output);
    }
    string_free(nested);
    file_free(manifest);
    string_free(sentinel);
    file_free(destination);
    string_free(data);
    return ok;
}

static string_t *test_cfg_locales_hex_literal(const char *text)
{
    static const char digits[] = "0123456789abcdef";
    string_t *literal = string_new_with("{\"utf8_hex\":\"");
    bool ok = literal != NULL;
    size_t length = strlen(text);
    for (size_t i = 0; ok && i < length; ++i) {
        unsigned char byte = (unsigned char)text[i];
        char pair[] = {digits[byte >> 4], digits[byte & 15]};
        ok = string_append_utf8_exact(literal, pair, sizeof pair) == 0;
    }
    ok = ok && string_append_utf8_exact(literal, "\"}", 2) == 0;
    if (!ok) {
        string_free(literal);
        literal = NULL;
    }
    return literal;
}

static bool test_cfg_locales_quoting_fixture(const char *directory)
{
    string_t *data = string_new();
    /* Preserve a decomposed path too: a normalising formatter would accidentally test a different directory. */
    const char *suffix = "/source-Cafe\u0301";
    if (!data || string_append_utf8_exact(data, directory, strlen(directory)) != 0 ||
        string_append_utf8_exact(data, suffix, strlen(suffix)) != 0) {
        string_free(data);
        return false;
    }
    const char *name_path[] = {"locales", "frc", "native_name"};
    const char *pattern_path[] = {"locales", "frc", "date_pattern"};
    /* Encode exact decomposed bytes using the generator's lossless pinned-input representation. */
    const char *label = "Cafe\u0301'); DROP TABLE calendar_language_name; -- 日本語";
    string_t *encoded_name = test_cfg_locales_hex_literal(label);
    string_t *encoded_pattern = test_cfg_locales_hex_literal("d 'U l''été' MMMM y");
    bool ok =
        data && encoded_name && encoded_pattern && test_cfg_locales_environment() &&
        test_cfg_locales_copy_data(string_c_str(data)) &&
        test_cfg_locales_replace(string_c_str(data), "supplements.json", name_path, 3, string_c_str(encoded_name)) &&
        test_cfg_locales_replace(string_c_str(data), "supplements.json", pattern_path, 3,
                                 string_c_str(encoded_pattern));
    string_free(encoded_pattern);
    string_free(encoded_name);
    const char *args[] = {"--data-dir", data ? string_c_str(data) : ""};
    string_t *output = NULL;
    ok = ok && test_cfg_locales_run(directory, args, 2, 0, &output);
    string_t *path = string_sprintf("%s/quoting.db", directory), *key = string_new_with("generator-quoting-only");
    sqlite_t *db = ok && path && key ? sqlite_open_encrypted(path, key) : NULL;
    ok = ok && db && sqlite_exec(db, output) &&
         test_cfg_locales_query(db, "SELECT native_name FROM calendar_language_name WHERE language='frc'", label) &&
         test_cfg_locales_query(
             db,
             "SELECT group_concat(literal,'') FROM (SELECT p.literal FROM calendar_date_pattern_part p "
             "JOIN calendar_locale_date_pattern l USING(pattern_id) WHERE l.locale='frc' AND p.field='literal' "
             "ORDER BY p.position)",
             " U l'été  ");
    string_free(output);
    output = NULL;
    const char *town_path[] = {"towns", "GB", "jam"};
    string_t *encoded_town = test_cfg_locales_hex_literal("  École  Park  ");
    string_t *towns = string_new_with("[");
    ok = ok && encoded_town && towns &&
         string_append_utf8_exact(towns, string_c_str(encoded_town), string_byte_length(encoded_town)) == 0 &&
         string_append_utf8_exact(towns, "]", 1) == 0 &&
         test_cfg_locales_replace(string_c_str(data), "supplements.json", town_path, 3, string_c_str(towns));
    /* Town keys must use the installer's accent folding and whitespace collapse, not ASCII-only lowering. */
#ifdef HAVE_UNISTRING
    ok = ok && test_cfg_locales_run(directory, args, 2, 0, &output) &&
         sqlite_exec_cstr(db, "DELETE FROM calendar_town_language") && sqlite_exec(db, output) &&
         test_cfg_locales_query(db, "SELECT town_key FROM calendar_town_language WHERE country='GB' AND language='jam'",
                                "ecole park");
#else
    /* Without Unicode folding support, reject the input explicitly rather than emitting a mismatched key. */
    ok = ok && test_cfg_locales_run(directory, args, 2, 1, &output) && test_cfg_locales_no_sql(output);
#endif
    string_free(towns);
    string_free(encoded_town);
    sqlite_close(db);
    string_free(key);
    string_free(path);
    string_free(output);
    output = NULL;
    const char *check[] = {"--check", "--data-dir", data ? string_c_str(data) : ""};
    ok = ok && test_cfg_locales_run(directory, check, 3, 1, &output) && test_cfg_locales_no_sql(output);
    string_free(output);
    string_free(data);
    return ok;
}

static bool test_cfg_locales_check_fixture(const char *directory)
{
    string_t *generated = NULL;
    bool ok = test_cfg_locales_environment() && test_cfg_locales_run(directory, NULL, 0, 0, &generated);
    file_t *packaging = test_cfg_locales_file(directory, "packaging/jurisdiction-db");
    file_t *countries = file_new_cstr(MARS_CONFIG_ROOT_DIR "/packaging/jurisdiction-db/mars_country_jurisdictions.sql");
    file_t *copied = test_cfg_locales_file(directory, "packaging/jurisdiction-db/mars_country_jurisdictions.sql");
    file_t *reference = test_cfg_locales_file(directory, "packaging/jurisdiction-db/mars_calendar_locale_names.sql");
    ok = ok && packaging && countries && copied && reference && file_create_directory(packaging, 0700, true) &&
         file_copy(countries, copied, false) && file_write_all_text(reference, generated) &&
         !setenv("MARS_ROOT", directory, 1);
    const char *args[] = {"--check", "--data-dir", MARS_CONFIG_ROOT_DIR "/tools/mars_config/data/locales"};
    string_t *output = NULL;
    ok = ok && test_cfg_locales_run(directory, args, 3, 0, &output) && output &&
         string_view_equals_literal(string_view_all(output), test_cfg_locales_check_message) &&
         test_cfg_locales_matches(reference, generated);
    string_free(output);
    output = NULL;
    /* BOMs are bytes in the reference contract, not an ignorable text-file decoration. */
    string_t *bom_reference = string_new();
    ok = ok && bom_reference && string_append_utf8_exact(bom_reference, "\xef\xbb\xbf", 3) == 0 &&
         string_append_utf8_exact(bom_reference, string_c_str(generated), string_byte_length(generated)) == 0 &&
         file_write_all_bytes(reference, string_c_str(bom_reference), string_byte_length(bom_reference)) &&
         test_cfg_locales_run(directory, args, 3, 1, &output) && test_cfg_locales_no_sql(output);
    unsigned char prefix[3] = {0};
    size_t read_count = 0;
    ok = ok && file_open_read(reference) && file_read(reference, prefix, sizeof prefix, &read_count) &&
         read_count == sizeof prefix && prefix[0] == 0xef && prefix[1] == 0xbb && prefix[2] == 0xbf;
    if (reference && file_is_open(reference))
        ok = file_close(reference) && ok;
    /* Text reading strips the BOM; together with the raw prefix check, this verifies every byte was preserved. */
    ok = ok && test_cfg_locales_matches(reference, generated);
    string_free(bom_reference);
    string_free(output);
    output = NULL;
    string_t *changed = string_new_with("-- Deliberately stale attribution; SQL body is identical.\n");
    ok = ok && changed &&
         string_append_utf8_exact(changed, string_c_str(generated), string_byte_length(generated)) == 0 &&
         file_write_all_text(reference, changed) && test_cfg_locales_run(directory, args, 3, 1, &output) &&
         test_cfg_locales_no_sql(output) && test_cfg_locales_matches(reference, changed);
    string_free(output);
    output = NULL;
    ok = ok && file_delete(reference) && test_cfg_locales_run(directory, args, 3, 1, &output) &&
         test_cfg_locales_no_sql(output) && !file_exists(reference);
    string_free(output);
    string_free(changed);
    file_free(reference);
    file_free(copied);
    file_free(countries);
    file_free(packaging);
    string_free(generated);
    return ok;
}

static bool test_cfg_locales_readme_fixture(const char *directory)
{
    file_t *guide_file = file_new_cstr(MARS_CONFIG_ROOT_DIR "/docs/jurisdiction.md");
    string_t *guide = guide_file ? file_read_all_text(guide_file) : NULL;
    const char *args[] = {"--check"};
    string_t *output = NULL;
    bool ok = guide && string_find(guide, "tools/mars_config/build/release/mars_config locales --check") >= 0 &&
              string_find(guide, test_cfg_locales_check_message) >= 0 && test_cfg_locales_environment() &&
              test_cfg_locales_run(directory, args, 1, 0, &output) && output &&
              string_view_equals_literal(string_view_all(output), test_cfg_locales_check_message);
    if (ok)
        string_printf("README example: mars_config locales --check\n%S", output);
    string_free(output);
    string_free(guide);
    file_free(guide_file);
    return ok;
}

static void test_cfg_locales_parity(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_parity_fixture),
                     "native SQL body, Unicode and date-pattern parity");
}

static void test_cfg_locales_output(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_output_fixture),
                     "deterministic output to a literal Unicode path");
}

static void test_cfg_locales_cli(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_cli_fixture), "invalid generator arguments do not publish SQL");
}

static void test_cfg_locales_missing(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_missing_fixture),
                     "missing source data preserves existing output");
}

static void test_cfg_locales_readme(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_readme_fixture),
                     "README native locale check and exact success text");
}

static void test_cfg_locales_validation(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_validation_fixture),
                     "malformed/versioned/incomplete data and bad patterns preserve previous output");
}

static void test_cfg_locales_quoting(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_quoting_fixture),
                     "Unicode SQL quoting and LDML apostrophe literals");
}

static void test_cfg_locales_check(void)
{
    TEST_ASSERT_TRUE(test_cfg_isolated(test_cfg_locales_check_fixture),
                     "check honours MARS_ROOT and rejects header drift or missing reference without writing");
}

/* Register ordinary generator checks before every README group. */
void test_cfg_locales_cases(void)
{
    TEST_RUN_IN_GROUP(test_cfg_locales_parity, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_output, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_cli, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_missing, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_validation, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_quoting, tests, NULL);
    TEST_RUN_IN_GROUP(test_cfg_locales_check, tests, NULL);
}

/* Register the documented check command in the final README section. */
void test_cfg_locales_readme_cases(void)
{
    TEST_RUN_IN_GROUP(test_cfg_locales_readme, readme_examples, NULL);
}
