/**
 * @file lab_memory.c
 * @brief Module-local memory operations for freestanding WebAssembly builds.
 *
 * Clang may emit these calls for aggregate operations even with -fno-builtin.
 * Providing them here keeps compiler-version differences out of the browser
 * bridge. Volatile byte accesses prevent optimisation from replacing the loops
 * with calls to the same routines. No allocation or host imports are required.
 */
#include <stdint.h>

#include "lab_memory.h"

/* Supply compiler-generated byte initialisation without a host dependency. */
void *memset(void *destination, int value, size_t length)
{
    volatile unsigned char *output = destination;
    for (size_t i = 0; i < length; ++i)
        output[i] = (unsigned char)value;
    return destination;
}

/* Supply compiler-generated copies of non-overlapping objects. */
void *memcpy(void *destination, const void *source, size_t length)
{
    volatile unsigned char *output = destination;
    const volatile unsigned char *input = source;
    for (size_t i = 0; i < length; ++i)
        output[i] = input[i];
    return destination;
}

/* Preserve source bytes when moving overlapping ranges in either direction. */
void *memmove(void *destination, const void *source, size_t length)
{
    volatile unsigned char *output = destination;
    const volatile unsigned char *input = source;
    if ((uintptr_t)destination < (uintptr_t)source) {
        for (size_t i = 0; i < length; ++i)
            output[i] = input[i];
    } else if (destination != source) {
        while (length) {
            --length;
            output[length] = input[length];
        }
    }
    return destination;
}

/* Compare unsigned bytes rather than implementation-defined signed characters. */
int memcmp(const void *left, const void *right, size_t length)
{
    const volatile unsigned char *a = left, *b = right;
    for (size_t i = 0; i < length; ++i)
        if (a[i] != b[i])
            return (int)a[i] - (int)b[i];
    return 0;
}
