#ifndef MATRIX_VTABLE_DEFS_H
#define MATRIX_VTABLE_DEFS_H

#define MARS_MATRIX_INTERNAL_ACCESS
#include "matrix_internal.h"

extern const struct store_vtable dense_store;
extern const struct store_vtable sparse_store;
extern const struct store_vtable identity_store;
extern const struct store_vtable diagonal_store;
extern const struct store_vtable upper_triangular_store;
extern const struct store_vtable lower_triangular_store;
bool dense_alloc(struct matrix_t *A);
void dense_free(struct matrix_t *A);
void dense_get(const struct matrix_t *A, size_t i, size_t j, void *out);
bool dense_is_diagonal(const struct matrix_t *A);
bool dense_is_sparse_like(const struct matrix_t *A);
bool dense_is_sparse_storage(const struct matrix_t *A);
size_t dense_nonzero_count(const struct matrix_t *A);
void dense_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start, const void *factor);
void dense_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void dense_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
bool diagonal_alloc(struct matrix_t *A);
void diagonal_free(struct matrix_t *A);
void diagonal_get(const struct matrix_t *A, size_t i, size_t j, void *out);
bool diagonal_is_sparse_like(const struct matrix_t *A);
bool diagonal_is_sparse_storage(const struct matrix_t *A);
void diagonal_materialise(struct matrix_t *A);
size_t diagonal_nonzero_count(const struct matrix_t *A);
void diagonal_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start,
                                 const void *factor);
void diagonal_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void diagonal_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
void expr_add_wrap(void *o, const void *a, const void *b);
void expr_conj_elem(void *o, const void *a);
void expr_copy_value(void *dst, const void *src);
void expr_destroy_value(void *slot);
void expr_init_zero_slot(void *slot);
void expr_inv_wrap(void *o, const void *a);
bool expr_is_structural_zero(const void *val);
void expr_mul_wrap(void *o, const void *a, const void *b);
void expr_scalar_acos(void *out, const void *a);
void expr_scalar_acosh(void *out, const void *a);
void expr_scalar_asin(void *out, const void *a);
void expr_scalar_asinh(void *out, const void *a);
void expr_scalar_atan(void *out, const void *a);
void expr_scalar_atanh(void *out, const void *a);
void expr_scalar_cos(void *out, const void *a);
void expr_scalar_cosh(void *out, const void *a);
void expr_scalar_digamma(void *out, const void *a);
void expr_scalar_e1(void *out, const void *a);
void expr_scalar_ei(void *out, const void *a);
void expr_scalar_erf(void *out, const void *a);
void expr_scalar_erfc(void *out, const void *a);
void expr_scalar_erfcinv(void *out, const void *a);
void expr_scalar_erfinv(void *out, const void *a);
void expr_scalar_exp(void *out, const void *a);
void expr_scalar_gamma(void *out, const void *a);
void expr_scalar_gammainv(void *out, const void *a);
void expr_scalar_lambert_w0(void *out, const void *a);
void expr_scalar_lambert_wm1(void *out, const void *a);
void expr_scalar_lgamma(void *out, const void *a);
void expr_scalar_log(void *out, const void *a);
void expr_scalar_normal_cdf(void *out, const void *a);
void expr_scalar_normal_logpdf(void *out, const void *a);
void expr_scalar_normal_pdf(void *out, const void *a);
void expr_scalar_productlog(void *out, const void *a);
void expr_scalar_sin(void *out, const void *a);
void expr_scalar_sinh(void *out, const void *a);
void expr_scalar_sqrt(void *out, const void *a);
void expr_scalar_tan(void *out, const void *a);
void expr_scalar_tanh(void *out, const void *a);
void expr_scalar_trigamma(void *out, const void *a);
void expr_simplify_value(void *slot);
void expr_sub_wrap(void *o, const void *a, const void *b);
int expr_cmp_wrap(const void *a, const void *b);
bool generic_is_lower_triangular(const struct matrix_t *A);
bool generic_is_upper_triangular(const struct matrix_t *A);
bool ident_alloc(struct matrix_t *A);
void ident_free(struct matrix_t *A);
void ident_get(const struct matrix_t *A, size_t i, size_t j, void *out);
void ident_materialise(struct matrix_t *A);
void ident_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start, const void *factor);
void ident_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void ident_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
bool identity_is_sparse_like(const struct matrix_t *A);
bool identity_is_sparse_storage(const struct matrix_t *A);
size_t identity_nonzero_count(const struct matrix_t *A);
const struct store_vtable *identity_unary_store(const struct matrix_t *A);
bool lower_triangular_alloc(struct matrix_t *A);
void lower_triangular_get(const struct matrix_t *A, size_t i, size_t j, void *out);
bool lower_triangular_is_diagonal(const struct matrix_t *A);
bool lower_triangular_is_sparse_like(const struct matrix_t *A);
bool lower_triangular_is_sparse_storage(const struct matrix_t *A);
void lower_triangular_materialise(struct matrix_t *A);
size_t lower_triangular_nonzero_count(const struct matrix_t *A);
void lower_triangular_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start,
                                         const void *factor);
void lower_triangular_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void lower_triangular_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
const struct store_vtable *lower_triangular_transpose_store(const struct matrix_t *A);
void num_add_wrap(void *o, const void *a, const void *b);
void num_conj_elem(void *o, const void *a);
void num_copy_value(void *dst, const void *src);
void num_destroy_value(void *slot);
string_t *num_format_scalar_text(const void *v, int scientific);
void num_init_zero_slot(void *slot);
void num_inv_wrap(void *o, const void *a);
bool num_is_structural_zero(const void *val);
void num_mul_wrap(void *o, const void *a, const void *b);
void num_scalar_acos(void *out, const void *a);
void num_scalar_acosh(void *out, const void *a);
void num_scalar_asin(void *out, const void *a);
void num_scalar_asinh(void *out, const void *a);
void num_scalar_atan(void *out, const void *a);
void num_scalar_atanh(void *out, const void *a);
void num_scalar_cos(void *out, const void *a);
void num_scalar_cosh(void *out, const void *a);
void num_scalar_digamma(void *out, const void *a);
void num_scalar_e1(void *out, const void *a);
void num_scalar_ei(void *out, const void *a);
void num_scalar_erf(void *out, const void *a);
void num_scalar_erfc(void *out, const void *a);
void num_scalar_erfcinv(void *out, const void *a);
void num_scalar_erfinv(void *out, const void *a);
void num_scalar_exp(void *out, const void *a);
void num_scalar_gamma(void *out, const void *a);
void num_scalar_gammainv(void *out, const void *a);
void num_scalar_lambert_w0(void *out, const void *a);
void num_scalar_lambert_wm1(void *out, const void *a);
void num_scalar_lgamma(void *out, const void *a);
void num_scalar_log(void *out, const void *a);
void num_scalar_normal_cdf(void *out, const void *a);
void num_scalar_normal_logpdf(void *out, const void *a);
void num_scalar_normal_pdf(void *out, const void *a);
void num_scalar_productlog(void *out, const void *a);
void num_scalar_sin(void *out, const void *a);
void num_scalar_sinh(void *out, const void *a);
void num_scalar_sqrt(void *out, const void *a);
void num_scalar_tan(void *out, const void *a);
void num_scalar_tanh(void *out, const void *a);
void num_scalar_tetragamma(void *out, const void *a);
void num_scalar_trigamma(void *out, const void *a);
void num_sub_wrap(void *o, const void *a, const void *b);
int number_cmp_wrap(const void *a, const void *b);
bool sparse_alloc(struct matrix_t *A);
void sparse_free(struct matrix_t *A);
void sparse_get(const struct matrix_t *A, size_t i, size_t j, void *out);
bool sparse_is_diagonal(const struct matrix_t *A);
bool sparse_is_sparse_like(const struct matrix_t *A);
bool sparse_is_sparse_storage(const struct matrix_t *A);
void sparse_materialise(struct matrix_t *A);
size_t sparse_nonzero_count(const struct matrix_t *A);
void sparse_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start,
                               const void *factor);
void sparse_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void sparse_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
struct matrix_t *store_create_dense(size_t rows, size_t cols, const struct elem_vtable *elem);
struct matrix_t *store_create_diagonal(size_t rows, size_t cols, const struct elem_vtable *elem);
struct matrix_t *store_create_identity(size_t rows, size_t cols, const struct elem_vtable *elem);
struct matrix_t *store_create_lower_triangular(size_t rows, size_t cols, const struct elem_vtable *elem);
struct matrix_t *store_create_sparse(size_t rows, size_t cols, const struct elem_vtable *elem);
struct matrix_t *store_create_upper_triangular(size_t rows, size_t cols, const struct elem_vtable *elem);
const struct store_vtable *store_self_transpose(const struct matrix_t *A);
const struct store_vtable *store_self_unary(const struct matrix_t *A);
bool store_true(const struct matrix_t *A);
void triangular_free(struct matrix_t *A);
bool upper_triangular_alloc(struct matrix_t *A);
void upper_triangular_get(const struct matrix_t *A, size_t i, size_t j, void *out);
bool upper_triangular_is_diagonal(const struct matrix_t *A);
bool upper_triangular_is_sparse_like(const struct matrix_t *A);
bool upper_triangular_is_sparse_storage(const struct matrix_t *A);
void upper_triangular_materialise(struct matrix_t *A);
size_t upper_triangular_nonzero_count(const struct matrix_t *A);
void upper_triangular_row_eliminate_from(struct matrix_t *A, size_t dst_row, size_t src_row, size_t col_start,
                                         const void *factor);
void upper_triangular_set(struct matrix_t *A, size_t i, size_t j, const void *val);
void upper_triangular_swap_rows(struct matrix_t *A, size_t r1, size_t r2);
const struct store_vtable *upper_triangular_transpose_store(const struct matrix_t *A);

#endif
