/* Generated by tools/generate_almanac_spice_oracle.py.
 * Oracle: SPICE DE440 apparent target vector from Earth (LT+S),
 * rotated to true equator/equinox of date with ERFA IAU 2006/2000A.
 * Dates are interpreted as MARS civil GMT, including the Julian/Gregorian switch.
 */
#ifndef TESTS_ALMANAC_SPICE_ORACLE_H
#define TESTS_ALMANAC_SPICE_ORACLE_H

typedef struct almanac_spice_oracle_case_t {
    const char *body_code;
    int year;
    int month;
    int day;
    int hour;
    int minute;
    double second;
    double sha_degrees;
    double declination_degrees;
    double geocentric_distance_au;
} almanac_spice_oracle_case_t;

static const almanac_spice_oracle_case_t ALMANAC_SPICE_ORACLE_CASES[] = {
    {"SUN", 1551, 1, 1, 0, 0, 0.0, 68.290438431811, -21.992374060714, 0.983673714840},
    {"MOON", 1551, 1, 1, 0, 0, 0.0, 143.696719144545, -10.307678197204, 0.002506653761},
    {"MARS", 1551, 1, 1, 0, 0, 0.0, 265.544685186833, 27.323362298384, 0.651240675958},
    {"JUPITER", 1551, 1, 1, 0, 0, 0.0, 277.931835196136, 23.066295845654, 4.260172786074},
    {"SUN", 1850, 1, 2, 0, 0, 0.0, 77.704326383265, -22.974849936747, 0.983238773368},
    {"MOON", 1850, 1, 2, 0, 0, 0.0, 208.721725772909, 12.212319644547, 0.002451518779},
    {"MARS", 1850, 1, 2, 0, 0, 0.0, 279.894897746823, 26.474044693192, 0.625898818262},
    {"JUPITER", 1850, 1, 2, 0, 0, 0.0, 185.898118554681, 3.939116351788, 5.030347772618},
    {"SUN", 2002, 1, 1, 22, 0, 0.0, 77.694204079161, -22.956704224551, 0.983291204251},
    {"MOON", 2002, 1, 1, 22, 0, 0.0, 221.880223626877, 20.197987436003, 0.002443053403},
    {"MARS", 2002, 1, 1, 22, 0, 0.0, 11.181368945022, -5.547397818044, 1.502488960377},
    {"JUPITER", 2002, 1, 1, 22, 0, 0.0, 258.532998485424, 23.024964027217, 4.188017301103},
    {"SUN", 2400, 1, 1, 0, 0, 0.0, 79.356484971898, -23.028527794195, 0.983715649617},
    {"MOON", 2400, 1, 1, 0, 0, 0.0, 33.483281581758, -11.762081790166, 0.002699292746},
    {"MARS", 2400, 1, 1, 0, 0, 0.0, 112.703934834920, -21.698862566003, 2.330063681382},
    {"JUPITER", 2400, 1, 1, 0, 0, 0.0, 66.858423617802, -21.859304746760, 6.135604816335},
    {"SUN", 2649, 1, 1, 0, 0, 0.0, 78.729068774229, -22.948789569428, 0.983998916944},
    {"MOON", 2649, 1, 1, 0, 0, 0.0, 136.871641344963, -12.278036946492, 0.002456677673},
    {"MARS", 2649, 1, 1, 0, 0, 0.0, 9.940447826134, -5.103836961575, 1.434116433092},
    {"JUPITER", 2649, 1, 1, 0, 0, 0.0, 66.214798520382, -21.692903102504, 6.151378466750},
};

static const unsigned int ALMANAC_SPICE_ORACLE_CASE_COUNT =
    (unsigned int)(sizeof(ALMANAC_SPICE_ORACLE_CASES) / sizeof(ALMANAC_SPICE_ORACLE_CASES[0]));

#endif
