/**
 * @file cfg_weather.c
 * @brief Native weather-account opt-in, private key persistence and terminal prompts.
 *
 * Replaces the weather installer script without contacting the provider. File I/O
 * uses file.h; terminal interaction uses stdio and termios. Literal string parsing
 * never executes configuration. A private exclusive temporary file is synced then
 * renamed, so a failed write cannot truncate the previous configuration.
 */
#include <errno.h>
#include <signal.h>
#include <sodium.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <termios.h>
#include <unistd.h>

#include "cfg_prompt.h"
#include "cfg_storage.h"
#include "cfg_weather.h"
#include "ustring.h"

static string_t *cfg_weather_text(const char *text)
{
    return cfg_storage_value(text);
}

static bool cfg_weather_valid(const string_t *key)
{
    size_t length = string_byte_length(key);
    if (!length || length > 4096)
        return false;
    string_view_t view = string_view_all(key);
    for (size_t i = 0; i < length; ++i) {
        unsigned char ch;
        if (!string_view_peek_ascii(view, i, &ch) || ch < 32 || ch > 126 || ch == '\'')
            return false;
    }
    return true;
}

static string_t *cfg_weather_stored(file_t *file)
{
    string_t *key = cfg_storage_setting(file, "MARS_WEATHER_API_KEY");
    if (key && !string_byte_length(key)) {
        string_free(key);
        key = cfg_storage_setting(file, "WEATHERAPI_KEY");
    }
    return key;
}

static bool cfg_weather_yes(const char *prompt)
{
    string_t *answer = cfg_prompt_read(prompt, false);
    string_view_t view = string_view_all(answer);
    bool yes = answer && (string_view_equals_literal(view, "y") || string_view_equals_literal(view, "yes") ||
                          string_view_equals_literal(view, "Y") || string_view_equals_literal(view, "YES"));
    string_free(answer);
    return yes;
}

/* Configure only weather credentials; never initialise a cache, browser or listener. */
int cfg_weather_run(const char *explicit_key, bool interactive)
{
    string_t *base = cfg_storage_home();
    string_t *directory = base ? string_sprintf("%s/config", string_c_str(base)) : NULL;
    string_t *path = directory ? string_sprintf("%s/weather.env", string_c_str(directory)) : NULL;
    file_t *file = path ? file_new(path) : NULL;
    string_t *key = cfg_weather_text(explicit_key);
    const char *names[] = {"MARS_WEATHER_API_KEY", "WEATHERAPI_KEY"};
    for (size_t i = 0; key && !string_byte_length(key) && i < 2; ++i) {
        string_free(key);
        key = cfg_weather_text(getenv(names[i]));
    }
    if (key && !string_byte_length(key)) {
        string_free(key);
        key = file ? cfg_weather_stored(file) : NULL;
    }
    bool ok = file && key;
    if (ok && interactive) {
        puts("Optional weather setup: use your own WeatherAPI account; no shared key is supplied.\n"
             "Weather stays disabled without a key. Sign up at https://www.weatherapi.com/signup.aspx\n"
             "The local server sends the key, date, latitude and longitude over HTTPS to WeatherAPI.com.\n"
             "The key is not sent to the browser. Weather responses are not cached or persisted.\n"
             "Date and location remain in private Lab state, not weather-specific logs.\n"
             "Weather is probabilistic: do not rely on it alone for safety-critical decisions.\n"
             "Terms: https://www.weatherapi.com/terms.aspx\nPrivacy: https://www.weatherapi.com/privacy.aspx");
        if (!cfg_weather_yes("Configure weather now? [y/N]: ")) {
            string_free(key);
            key = string_new();
        } else if (!string_byte_length(key) || cfg_weather_yes("A key is configured. Replace it? [y/N]: ")) {
            string_free(key);
            key = NULL;
            for (;;) {
                key = cfg_prompt_read("WeatherAPI key (blank skips setup): ", true);
                if (!key || !string_byte_length(key))
                    break;
                string_t *repeat = cfg_prompt_read("Confirm WeatherAPI key: ", true);
                bool cancelled = repeat == NULL;
                bool matches = repeat && !string_compare(key, repeat);
                string_free(repeat);
                if (matches)
                    break;
                string_free(key);
                key = NULL;
                if (cancelled)
                    break;
                puts("Keys did not match. Please try again.");
            }
        }
        ok = key != NULL;
    }
    if (ok && string_byte_length(key)) {
        bool exists = false;
        ok = cfg_weather_valid(key) && sodium_init() >= 0 && cfg_storage_safe_regular(file, &exists) &&
             cfg_storage_private_directory(directory, true);
        string_t *body = ok ? string_sprintf("# Generated by mars_config weather\n"
                                             "export MARS_WEATHER_API_KEY='%s'\n",
                                             string_c_str(key))
                            : NULL;
        ok = ok && body && cfg_storage_publish(file, directory, body);
        string_free(body);
        if (ok)
            puts("Weather API configuration saved.");
    }
    if (!ok)
        fputs("Cannot save weather configuration; check the key and private configuration path.\n", stderr);
    string_free(key);
    file_free(file);
    string_free(path);
    string_free(directory);
    string_free(base);
    return ok ? 0 : 1;
}
