#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include "test_number.h"

static void assert_number_close_text(const char *label, number_t got, const char *want_text,
                                     const char *tolerance_text)
{
    number_t want = num_create_from_string(want_text);
    number_t diff = num_sub(got, want);
    number_t error = num_abs(diff);
    number_t tolerance = num_create_from_string(tolerance_text);
    string_t *error_text = num_to_string(error);

    printf(C_WHITE C_BOLD "%s" C_RESET "\n", label ? label : "<unspecified>");
    printf("    want = %s\n", want_text);
    printf("    tolerance = %s\n", tolerance_text);
    printf("    error    = %s\n\n", error_text ? string_c_str(error_text) : "(num_to_string failed)");
    string_free(error_text);
    ASSERT_TRUE(num_lt(error, tolerance));
    num_destroy(&tolerance);
    num_destroy(&error);
    num_destroy(&diff);
    num_destroy(&want);
}

static void assert_number_close_number(const char *label, number_t got, number_t want, const char *tolerance_text)
{
    number_t diff = num_sub(got, want);
    number_t error = num_abs(diff);
    number_t tolerance = num_create_from_string(tolerance_text);
    string_t *want_text = num_to_string(want);
    string_t *error_text = num_to_string(error);

    printf(C_WHITE C_BOLD "%s" C_RESET "\n", label ? label : "<unspecified>");
    printf("    want = %s\n", want_text ? string_c_str(want_text) : "(num_to_string failed)");
    printf("    tolerance = %s\n", tolerance_text);
    printf("    error    = %s\n\n", error_text ? string_c_str(error_text) : "(num_to_string failed)");
    string_free(error_text);
    string_free(want_text);
    ASSERT_TRUE(num_lt(error, tolerance));
    num_destroy(&tolerance);
    num_destroy(&error);
    num_destroy(&diff);
}

static void test_number_clausen(void)
{
    NUM_SCOPE(scope);
    size_t saved_precision = num_get_default_prec_bits();
    number_t fixed_inputs[] = {num_create_from_double(1.0), num_create_from_qfloat(QF_ONE),
                               num_create_from_qcomplex(QC_ONE), num_create_from_long(1),
                               num_create_from_frac(1, 1)};

    for (size_t k = 0u; k < sizeof(fixed_inputs) / sizeof(fixed_inputs[0]); ++k) {
        number_t result = num_clausen2(fixed_inputs[k]);
        number_t general = num_clausen(2ul, fixed_inputs[k]);

        ASSERT_TRUE(num_is_real(result));
        assert_number_close_text("Cl2 real backend dispatch", result,
                                 "1.0139591323607685042945743388859146875611792800777", "1e-15");
        assert_number_close_number("Cl2 unary/general agreement", result, general, "1e-30");
        assert_number_close_text("Clausen preserves its input", fixed_inputs[k], "1", "1e-30");
    }
    ASSERT_TRUE(num_is_nan(num_clausen(0ul, NUM_ONE)));
    ASSERT_TRUE(num_is_nan(num_clausen2(NUM_NAN)));
    ASSERT_TRUE(num_is_nan(num_clausen2(NUM_INF)));
    ASSERT_TRUE(num_is_inf(num_clausen(1ul, NUM_ZERO)));

    ASSERT_EQ_INT(num_set_default_prec_bits(640u), 0);
    {
        number_t one = num_create_from_string("1.0");
        number_t two = num_create_from_long(2);
        number_t pi = num_const_prec(NUM_PI, 640u);
        number_t period = num_mul(two, pi);
        number_t angle = num_div(pi, two);
        number_t result = num_clausen2(angle);
        number_t tiny = num_create_from_string("1e-150");
        number_t tiny_result = num_div(num_clausen2(tiny), tiny);
        number_t tiny_reference = num_sub(one, num_log(tiny));
        number_t near_pi = num_sub(pi, num_create_from_string("1e-120"));
        number_t near_pi_reference = num_mul(num_sub(pi, near_pi), num_log(two));

        ASSERT_TRUE(num_get_prec_bits(result) >= 640u);
        ASSERT_TRUE(num_is_real(result));
        /* Catalan's constant, independently generated by Euler acceleration of its alternating series. */
        assert_number_close_text("640-bit Cl2(pi/2) = Catalan", result,
            "0.9159655941772190150546035149323841107741493742816721342664981196217630197762547694793565129261151062485744"
            "22619196199579035898803325859059431594737481158406995332028773319460519038727478164087865909024706484152",
            "1e-185");
        assert_number_close_number("640-bit Cl2 tiny-angle asymptote", tiny_result, tiny_reference, "1e-180");
        assert_number_close_number("640-bit Cl2 near pi", num_clausen2(near_pi), near_pi_reference, "1e-185");
        assert_number_close_number("640-bit Cl2 periodicity", num_clausen2(num_add(angle, period)), result, "1e-185");
        assert_number_close_number("640-bit Cl2 oddness", num_clausen2(num_neg(angle)), num_neg(result), "1e-185");
        assert_number_close_number("640-bit input preserved", num_mul(angle, two), pi, "1e-185");
        ASSERT_TRUE(num_is_real(num_clausen(1ul, num_neg(one))));

        for (unsigned long order = 3ul; order <= 7ul; order += 2ul) {
            number_t n = num_create_from_long((long)order);
            number_t zeta = num_zeta(n);
            number_t eta = num_mul(num_sub(one, num_pow_int(two, 1 - (int)order)), zeta);
            number_t expected = num_neg(num_mul(num_pow_int(two, -(int)order), eta));

            assert_number_close_number("640-bit odd Clausen at zero", num_clausen(order, NUM_ZERO), zeta, "1e-185");
            assert_number_close_number("640-bit odd Clausen at pi/2", num_clausen(order, angle), expected, "1e-185");
        }
        assert_number_close_number("large-order Clausen sine limit", num_clausen(1024ul, one), num_sin(one), "1e-185");
        assert_number_close_number("large-order Clausen cosine limit", num_clausen(1025ul, one), num_cos(one), "1e-185");

        for (unsigned int region = 0u; region < 2u; ++region) {
            number_t z = num_create_from_string(region == 0u ? "1 + 1i" : "1 + 4i");
            number_t h = num_create_from_string("1e-55");
            number_t two_h = num_mul(two, h);
            number_t iz = num_mul(num_const_prec(NUM_I, 640u), z);
            number_t difference = num_sub(num_dilog(num_exp(iz)), num_dilog(num_exp(num_neg(iz))));
            number_t reference = num_div(difference, num_mul(two, num_const_prec(NUM_I, 640u)));
            number_t cl2 = num_clausen2(z);

            ASSERT_TRUE(!num_is_real(cl2));
            ASSERT_TRUE(num_get_prec_bits(cl2) >= 640u);
            assert_number_close_number("640-bit holomorphic Cl2 dilogarithm identity", cl2, reference, "1e-180");
            assert_number_close_number("640-bit Cl1 branch", num_clausen(1ul, z),
                                       num_neg(num_log(num_mul(two, num_sin(num_div(z, two))))), "1e-180");
            for (unsigned long order = 2ul; order <= 6ul; ++order) {
                number_t value = num_clausen(order, z);
                number_t plus = num_clausen(order, num_add(z, h));
                number_t minus = num_clausen(order, num_sub(z, h));
                number_t derivative = num_div(num_sub(plus, minus), two_h);
                number_t previous = num_clausen(order - 1ul, z);
                number_t expected = (order & 1ul) ? num_neg(previous) : num_clone(previous);

                assert_number_close_number("640-bit Clausen derivative recurrence", derivative, expected, "1e-105");
                assert_number_close_number("640-bit Clausen conjugation", num_clausen(order, num_conj(z)),
                                           num_conj(value), "1e-180");
                assert_number_close_number("640-bit Clausen complex periodicity", num_clausen(order, num_add(z, period)),
                                           value, "1e-180");
            }
        }
        ASSERT_TRUE(num_is_nan(num_clausen2(num_create_from_string("1i"))));
    }
    ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
}

static void restore_modified_test_precision(size_t *precision)
{
    (void)num_set_default_prec_bits(*precision);
}

static void test_number_bessel_i(void)
{
    NUM_SCOPE(scope);
    __attribute__((cleanup(restore_modified_test_precision))) size_t saved_precision = num_get_default_prec_bits();
    ASSERT_EQ_INT(num_set_default_prec_digits(90u), 0);
    size_t precision = num_get_default_prec_bits();
    number_t x = num_create_from_string("1.25");
    number_t pi = num_const_prec(NUM_PI, precision);
    number_t scale = num_sqrt(num_div(NUM_TWO, num_mul(pi, x)));
    number_t half = num_create_from_frac(1, 2);
    number_t value = num_bessel_i(half, x);
    ASSERT_TRUE(num_get_prec_bits(value) >= precision);
    assert_number_close_number("80-digit Bessel I_1/2", value, num_mul(scale, num_sinh(x)), "1e-80");
    assert_number_close_number("80-digit Bessel I_-1/2", num_bessel_i(num_neg(half), x),
                               num_mul(scale, num_cosh(x)), "1e-80");
    assert_number_close_number("80-digit Bessel I0/I1 Wronskian",
                               num_add(num_mul(num_bessel_i(NUM_ZERO, x), num_bessel_k(NUM_ONE, x)),
                                       num_mul(num_bessel_i(NUM_ONE, x), num_bessel_k(NUM_ZERO, x))),
                               num_div(NUM_ONE, x), "1e-80");
    assert_number_close_number("80-digit I0 imaginary-axis cancellation",
                               num_bessel_i(NUM_ZERO, num_create_from_string("80i")),
                               num_bessel_j(NUM_ZERO, num_create_from_long(80)), "1e-80");
    number_t complex_z = num_create_from_string("1.25 + 0.75i");
    for (long n = 0; n <= 6; ++n) {
        number_t order = num_create_from_long(n);
        number_t positive = num_bessel_i(order, complex_z);
        assert_number_close_number("80-digit I_-n = I_n", num_bessel_i(num_neg(order), complex_z),
                                   positive, "1e-80");
        assert_number_close_number("80-digit integral Bessel I parity", num_bessel_i(order, num_neg(complex_z)),
                                   n % 2 ? num_neg(positive) : positive, "1e-80");
        ASSERT_TRUE(num_eq(num_bessel_i(num_neg(order), NUM_ZERO), n ? NUM_ZERO : NUM_ONE));
    }
    /* A 10^120 denominator exceeds the 90-digit rational budget. Keep construction and evaluation
     * at 160 digits so the displacement survives before the guarded kernel receives the order. */
    ASSERT_EQ_INT(num_set_default_prec_digits(160u), 0);
    number_t epsilon = num_pow_int(num_create_from_long(10), -120);
    number_t tiny = num_create_from_string("1e-100");
    number_t above_order = num_add(NUM_NEG_ONE, epsilon);
    number_t below_order = num_sub(NUM_NEG_ONE, epsilon);
    ASSERT_TRUE(num_is_exact(epsilon));
    ASSERT_TRUE(num_is_exact(above_order) && num_is_exact(below_order));
    ASSERT_TRUE(num_eq(num_sub(above_order, NUM_NEG_ONE), epsilon));
    ASSERT_TRUE(num_eq(num_sub(NUM_NEG_ONE, below_order), epsilon));
    number_t leading = num_div(num_mul(NUM_TWO, epsilon), tiny);
    assert_number_close_number("Bessel I near negative integer retains first coefficient",
                               num_div(num_bessel_i(above_order, tiny), leading), NUM_ONE, "1e-75");
    assert_number_close_number("Bessel I opposite side of negative integer",
                               num_div(num_bessel_i(below_order, tiny), leading), NUM_NEG_ONE, "1e-75");
    ASSERT_EQ_INT(num_set_default_prec_bits(precision), 0);

    number_t nu = num_create_from_string("0.25 + 0.375i");
    number_t small_z = num_create_from_string("1e-60");
    number_t left = num_bessel_i(nu, small_z);
    number_t right = num_bessel_i(num_neg(nu), small_z);
    number_t pi_nu = num_mul(pi, nu);
    ASSERT_TRUE(num_get_prec_bits(left) >= precision);
    /* Gamma reflection yields an elementary reference; omitted terms are O(z^2). */
    assert_number_close_number("80-digit complex-order Bessel I gamma reflection", num_mul(left, right),
                               num_div(num_sin(pi_nu), pi_nu), "1e-80");
    number_t complex_value = num_bessel_i(nu, complex_z);
    assert_number_close_number("80-digit Bessel I complex-order recurrence",
                               num_sub(num_bessel_i(num_sub(nu, NUM_ONE), complex_z),
                                       num_bessel_i(num_add(nu, NUM_ONE), complex_z)),
                               num_mul(num_div(num_mul(NUM_TWO, nu), complex_z), complex_value), "1e-80");
    assert_number_close_number("80-digit Bessel I conjugation", num_bessel_i(num_conj(nu), num_conj(complex_z)),
                               num_conj(complex_value), "1e-80");
    number_t phase = num_exp(num_mul(num_create_from_string("i"), pi_nu));
    number_t positive = num_bessel_i(nu, x);
    assert_number_close_number("80-digit Bessel I upper bank", num_bessel_i(nu, num_neg(x)),
                               num_mul(phase, positive), "1e-80");
    number_t below_cut = num_sub(num_neg(x), num_create_from_string("1e-85i"));
    assert_number_close_number("80-digit Bessel I lower bank", num_bessel_i(nu, below_cut),
                               num_div(positive, phase), "1e-80");
    number_t backends[] = {num_create_from_double(1.0), num_create_from_qfloat(QF_ONE),
                           num_create_from_qcomplex(QC_ONE), num_create_from_long(1), num_create_from_frac(1, 1)};
    for (size_t k = 0; k < sizeof(backends) / sizeof(backends[0]); ++k) {
        number_t result = num_bessel_i(num_create_from_qfloat(QF_ZERO), backends[k]);
        assert_number_close_text("I0 backend promotion", result, "1.2660658777520083355982446252147175", "1e-28");
        ASSERT_TRUE(num_is_real(result));
        ASSERT_TRUE(num_eq(backends[k], NUM_ONE));
    }
    ASSERT_TRUE(num_is_zero(num_bessel_i(nu, NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(num_create_from_string("i"), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(num_neg(half), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(NUM_NAN, x)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(NUM_ZERO, NUM_INF)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(num_create_from_long(1001), x)));
    ASSERT_TRUE(num_is_nan(num_bessel_i(NUM_ZERO, num_create_from_long(1001))));
    ASSERT_TRUE(num_eq(nu, num_create_from_string("0.25 + 0.375i")));
    ASSERT_TRUE(num_eq(x, num_create_from_string("1.25")));
    ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
}

static void test_number_struve_l(void)
{
    NUM_SCOPE(scope);
    __attribute__((cleanup(restore_modified_test_precision))) size_t saved_precision = num_get_default_prec_bits();
    ASSERT_EQ_INT(num_set_default_prec_digits(90u), 0);
    size_t precision = num_get_default_prec_bits();
    number_t x = num_create_from_string("1.25");
    number_t pi = num_const_prec(NUM_PI, precision);
    number_t scale = num_sqrt(num_div(NUM_TWO, num_mul(pi, x)));
    number_t minus_half = num_create_from_frac(-1, 2);
    number_t minus_three_halves = num_create_from_frac(-3, 2);
    number_t actual = num_struve_l(minus_half, x);
    ASSERT_TRUE(num_get_prec_bits(actual) >= precision);
    assert_number_close_number("80-digit Struve L_-1/2", actual, num_mul(scale, num_sinh(x)), "1e-80");
    assert_number_close_number("80-digit Struve L_1/2", num_struve_l(NUM_HALF, x),
                               num_mul(scale, num_sub(num_cosh(x), NUM_ONE)), "1e-80");
    number_t previous = num_mul(scale, num_sinh(x));
    number_t current = num_mul(scale, num_sub(num_cosh(x), num_div(num_sinh(x), x)));
    for (long j = 1; j <= 6; ++j) {
        number_t alpha = num_create_from_frac(2 * j + 1, 2);
        number_t value = num_struve_l(num_neg(alpha), x);
        assert_number_close_number("80-digit negative half-integer Struve L", value, current, "1e-80");
        number_t next = num_sub(previous, num_mul(num_div(num_mul(NUM_TWO, alpha), x), current));
        previous = current;
        current = next;
    }

    /* A tiny displacement from a reciprocal-gamma zero dominates at a sufficiently small argument.
     * Its 10^120 denominator needs a larger rational budget than the surrounding 90-digit checks. */
    ASSERT_EQ_INT(num_set_default_prec_digits(160u), 0);
    number_t epsilon = num_pow_int(num_create_from_long(10), -120);
    number_t tiny = num_create_from_string("1e-100");
    number_t near_order = num_add(minus_three_halves, epsilon);
    number_t below_order = num_sub(minus_three_halves, epsilon);
    ASSERT_TRUE(num_is_exact(epsilon));
    ASSERT_TRUE(num_is_exact(near_order) && num_is_exact(below_order));
    ASSERT_TRUE(num_eq(num_sub(near_order, minus_three_halves), epsilon));
    ASSERT_TRUE(num_eq(num_sub(minus_three_halves, below_order), epsilon));
    number_t leading = num_mul(num_mul(epsilon, num_sqrt(num_div(NUM_TWO, tiny))),
                               num_div(NUM_TWO, num_sqrt(pi)));
    number_t near_value = num_struve_l(near_order, tiny);
    assert_number_close_number("near gamma zero keeps the non-vanishing first term",
                               num_div(near_value, leading), NUM_ONE, "1e-75");
    number_t below = num_struve_l(below_order, tiny);
    assert_number_close_number("opposite side of gamma zero has the correct sign",
                               num_div(below, leading), NUM_NEG_ONE, "1e-75");
    ASSERT_TRUE(num_gt(num_struve_l(minus_three_halves, tiny), NUM_ZERO));
    ASSERT_EQ_INT(num_set_default_prec_bits(precision), 0);

    /* Gamma reflection supplies an independent elementary reference for genuinely complex orders.
     * Dividing by z keeps this a relative check: the neglected Struve terms are O(z^2). */
    number_t nu = num_create_from_string("0.25 + 0.375i");
    number_t z = num_create_from_string("1e-60");
    number_t b = num_add(nu, NUM_ONE_AND_HALF);
    number_t partner = num_sub(NUM_NEG_ONE, nu);
    number_t left = num_struve_l(nu, z);
    number_t right = num_struve_l(partner, z);
    number_t reflection = num_div(num_mul(NUM_TWO, num_sin(num_mul(pi, b))),
                                 num_mul(num_sub(NUM_ONE, b), num_mul(pi, pi)));
    ASSERT_TRUE(num_get_prec_bits(left) >= precision);
    ASSERT_TRUE(num_get_prec_bits(right) >= precision);
    assert_number_close_number("80-digit complex-order Struve gamma reflection",
                               num_div(num_mul(left, right), z), reflection, "1e-80");
    number_t complex_z = num_create_from_string("1.25 + 0.75i");
    number_t complex_value = num_struve_l(nu, complex_z);
    ASSERT_TRUE(num_get_prec_bits(complex_value) >= precision);
    assert_number_close_number("80-digit Struve complex-order conjugation",
                               num_struve_l(num_conj(nu), num_conj(complex_z)), num_conj(complex_value), "1e-80");
    number_t imaginary_pi = num_mul(num_create_from_string("i"), pi);
    number_t phase = num_exp(num_mul(imaginary_pi, num_add(nu, NUM_ONE)));
    number_t positive = num_struve_l(nu, x);
    assert_number_close_number("80-digit Struve upper bank", num_struve_l(nu, num_neg(x)),
                               num_mul(phase, positive), "1e-80");
    number_t cut_offset = num_create_from_string("1e-85i");
    assert_number_close_number("80-digit Struve lower bank", num_struve_l(nu, num_sub(num_neg(x), cut_offset)),
                               num_div(positive, phase), "1e-80");

    /* The imaginary axis makes the defining series alternate, exercising cancellation guards. */
    number_t imaginary_z = num_create_from_string("80i");
    number_t imaginary_scale = num_sqrt(num_div(NUM_TWO, num_mul(pi, imaginary_z)));
    assert_number_close_number("80-digit Struve imaginary-axis cancellation",
                               num_struve_l(minus_half, imaginary_z),
                               num_mul(imaginary_scale, num_sinh(imaginary_z)), "1e-80");
    number_t backends[] = {num_create_from_double(1.0), num_create_from_qfloat(QF_ONE),
                           num_create_from_qcomplex(QC_ONE), num_create_from_long(1),
                           num_create_from_frac(1, 1)};
    for (size_t k = 0; k < sizeof(backends) / sizeof(backends[0]); ++k) {
        number_t value = num_struve_l(num_create_from_qfloat(QF_ZERO), backends[k]);
        assert_number_close_text("Struve L backend promotion", value,
                                 "0.7102431859378908887385266778116507", "1e-28");
        ASSERT_TRUE(num_is_real(value));
        ASSERT_TRUE(num_eq(backends[k], NUM_ONE));
    }
    assert_number_close_number("Struve L_-1(0)", num_struve_l(NUM_NEG_ONE, NUM_ZERO),
                               num_div(NUM_TWO, pi), "1e-80");
    ASSERT_TRUE(num_is_zero(num_struve_l(minus_three_halves, NUM_ZERO)));
    ASSERT_TRUE(num_is_zero(num_struve_l(nu, NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_l(num_create_from_string("-1 + i"), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_l(num_create_from_long(-2), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_l(NUM_NAN, x)));
    ASSERT_TRUE(num_is_nan(num_struve_l(NUM_ZERO, NUM_INF)));
    ASSERT_TRUE(num_is_nan(num_struve_l(num_create_from_long(1001), x)));
    ASSERT_TRUE(num_is_nan(num_struve_l(NUM_ZERO, num_create_from_long(1001))));
    ASSERT_TRUE(num_eq(nu, num_create_from_string("0.25 + 0.375i")));
    ASSERT_TRUE(num_eq(x, num_create_from_string("1.25")));
    ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
}

static void test_number_struve_h(void)
{
    NUM_SCOPE(scope);
    __attribute__((cleanup(restore_modified_test_precision))) size_t saved_precision = num_get_default_prec_bits();
    ASSERT_EQ_INT(num_set_default_prec_digits(90u), 0);
    size_t precision = num_get_default_prec_bits();
    number_t x = num_create_from_string("1.25");
    number_t pi = num_const_prec(NUM_PI, precision);
    number_t scale = num_sqrt(num_div(NUM_TWO, num_mul(pi, x)));
    number_t minus_half = num_create_from_frac(-1, 2);
    number_t minus_three_halves = num_create_from_frac(-3, 2);
    number_t actual = num_struve_h(minus_half, x);
    ASSERT_TRUE(num_get_prec_bits(actual) >= precision);
    assert_number_close_number("80-digit H_-1/2", actual, num_mul(scale, num_sin(x)), "1e-80");
    assert_number_close_number("80-digit H_1/2", num_struve_h(NUM_HALF, x),
                               num_mul(scale, num_sub(NUM_ONE, num_cos(x))), "1e-80");
    number_t previous = num_mul(scale, num_sin(x));
    number_t current = num_mul(scale, num_sub(num_cos(x), num_div(num_sin(x), x)));
    for (long j = 1; j <= 6; ++j) {
        number_t alpha = num_create_from_frac(2 * j + 1, 2);
        assert_number_close_number("80-digit H negative half-integer", num_struve_h(num_neg(alpha), x),
                                   current, "1e-80");
        number_t next = num_sub(num_neg(previous), num_mul(num_div(num_mul(NUM_TWO, alpha), x), current));
        previous = current;
        current = next;
    }

    /* Retain the exact 10^120 denominator throughout construction and evaluation. */
    ASSERT_EQ_INT(num_set_default_prec_digits(160u), 0);
    number_t epsilon = num_pow_int(num_create_from_long(10), -120);
    number_t tiny = num_create_from_string("1e-100");
    number_t near_order = num_add(minus_three_halves, epsilon);
    number_t below_order = num_sub(minus_three_halves, epsilon);
    ASSERT_TRUE(num_is_exact(epsilon));
    ASSERT_TRUE(num_is_exact(near_order) && num_is_exact(below_order));
    ASSERT_TRUE(num_eq(num_sub(near_order, minus_three_halves), epsilon));
    ASSERT_TRUE(num_eq(num_sub(minus_three_halves, below_order), epsilon));
    number_t leading = num_mul(num_mul(epsilon, num_sqrt(num_div(NUM_TWO, tiny))),
                               num_div(NUM_TWO, num_sqrt(pi)));
    assert_number_close_number("H near reciprocal-gamma zero retains the first term",
                               num_div(num_struve_h(near_order, tiny), leading), NUM_ONE, "1e-75");
    assert_number_close_number("H opposite side of reciprocal-gamma zero",
                               num_div(num_struve_h(below_order, tiny), leading), NUM_NEG_ONE, "1e-75");
    ASSERT_TRUE(num_lt(num_struve_h(minus_three_halves, tiny), NUM_ZERO));
    ASSERT_EQ_INT(num_set_default_prec_bits(precision), 0);

    /* Independent complex gamma reflection reference; neglected terms are O(z^2). */
    number_t nu = num_create_from_string("0.25 + 0.375i");
    number_t z = num_create_from_string("1e-60");
    number_t b = num_add(nu, NUM_ONE_AND_HALF);
    number_t partner = num_sub(NUM_NEG_ONE, nu);
    number_t left = num_struve_h(nu, z);
    number_t right = num_struve_h(partner, z);
    number_t reflection = num_div(num_mul(NUM_TWO, num_sin(num_mul(pi, b))),
                                 num_mul(num_sub(NUM_ONE, b), num_mul(pi, pi)));
    ASSERT_TRUE(num_get_prec_bits(left) >= precision);
    ASSERT_TRUE(num_get_prec_bits(right) >= precision);
    assert_number_close_number("80-digit H complex-order gamma reflection",
                               num_div(num_mul(left, right), z), reflection, "1e-80");
    number_t complex_z = num_create_from_string("1.25 + 0.75i");
    number_t complex_value = num_struve_h(nu, complex_z);
    ASSERT_TRUE(num_get_prec_bits(complex_value) >= precision);
    assert_number_close_number("80-digit H complex-order conjugation",
                               num_struve_h(num_conj(nu), num_conj(complex_z)), num_conj(complex_value), "1e-80");
    number_t phase = num_exp(num_mul(num_mul(num_create_from_string("i"), pi), num_add(nu, NUM_ONE)));
    number_t positive = num_struve_h(nu, x);
    assert_number_close_number("80-digit H upper bank", num_struve_h(nu, num_neg(x)),
                               num_mul(phase, positive), "1e-80");
    number_t cut_offset = num_create_from_string("1e-85i");
    assert_number_close_number("80-digit H lower bank", num_struve_h(nu, num_sub(num_neg(x), cut_offset)),
                               num_div(positive, phase), "1e-80");
    const char *points[] = {"1.25 + 0.75i", "-1.25 + 0.75i", "-1.25 - 0.75i", "1.25 - 0.75i"};
    for (size_t k = 0; k < sizeof(points) / sizeof(points[0]); ++k) {
        number_t point = num_create_from_string(points[k]);
        number_t factor = num_sqrt(num_div(NUM_TWO, num_mul(pi, point)));
        assert_number_close_number("80-digit H complex half-order branch", num_struve_h(minus_half, point),
                                   num_mul(factor, num_sin(point)), "1e-80");
        assert_number_close_number("80-digit H complex exceptional order", num_struve_h(minus_three_halves, point),
                                   num_mul(factor, num_sub(num_cos(point), num_div(num_sin(point), point))), "1e-80");
    }
    number_t large = num_create_from_long(80);
    number_t large_scale = num_sqrt(num_div(NUM_TWO, num_mul(pi, large)));
    assert_number_close_number("80-digit H real-axis cancellation", num_struve_h(minus_half, large),
                               num_mul(large_scale, num_sin(large)), "1e-80");
    number_t backends[] = {num_create_from_double(1.0), num_create_from_qfloat(QF_ONE),
                           num_create_from_qcomplex(QC_ONE), num_create_from_long(1), num_create_from_frac(1, 1)};
    number_t reference = num_struve_h(NUM_ZERO, NUM_ONE);
    for (size_t k = 0; k < sizeof(backends) / sizeof(backends[0]); ++k) {
        number_t value = num_struve_h(num_create_from_qfloat(QF_ZERO), backends[k]);
        assert_number_close_number("H backend promotion", value, reference, "1e-28");
        ASSERT_TRUE(num_is_real(value));
        ASSERT_TRUE(num_eq(backends[k], NUM_ONE));
    }
    assert_number_close_number("H_-1(0)", num_struve_h(NUM_NEG_ONE, NUM_ZERO), num_div(NUM_TWO, pi), "1e-80");
    ASSERT_TRUE(num_is_zero(num_struve_h(minus_three_halves, NUM_ZERO)));
    ASSERT_TRUE(num_is_zero(num_struve_h(nu, NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_h(num_create_from_string("-1 + i"), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_h(num_create_from_long(-2), NUM_ZERO)));
    ASSERT_TRUE(num_is_nan(num_struve_h(NUM_NAN, x)));
    ASSERT_TRUE(num_is_nan(num_struve_h(NUM_ZERO, NUM_INF)));
    ASSERT_TRUE(num_is_nan(num_struve_h(num_create_from_long(1001), x)));
    ASSERT_TRUE(num_is_nan(num_struve_h(NUM_ZERO, num_create_from_long(1001))));
    ASSERT_TRUE(num_eq(nu, num_create_from_string("0.25 + 0.375i")));
    ASSERT_TRUE(num_eq(x, num_create_from_string("1.25")));
    ASSERT_EQ_INT(num_get_default_prec_bits(), precision);
}

void run_number_special_function_tests(void)
{
    printf(C_CYAN "Testing special functions and extended dispatch...\n" C_RESET);

    test_number_clausen();
    TEST_RUN_SUBTEST(test_number_struve_l, "number,struve,precision");
    TEST_RUN_SUBTEST(test_number_struve_h, "number,struve,precision");
    TEST_RUN_SUBTEST(test_number_bessel_i, "number,bessel,precision");
    TEST_RUN_SUBTEST(run_number_bessel_y_tests, "number,bessel-y,precision");

    {
        number_t zero = num_create_from_string("0");
        number_t one = num_create_from_string("1");
        number_t two = num_create_from_string("2");
        number_t three = num_create_from_string("3");
        number_t four = num_create_from_string("4");
        number_t five = num_create_from_string("5");
        number_t fifty_two = num_create_from_string("52");
        number_t lgamma5 = num_lgamma(five);
        number_t digamma1 = num_digamma(one);
        number_t trigamma1 = num_trigamma(one);
        number_t trigamma_inf = num_trigamma(NUM_INF);
        number_t tetragamma_inf = num_tetragamma(NUM_INF);
        number_t polygamma0_1 = num_polygamma(0u, one);
        number_t polygamma1_1 = num_polygamma(1u, one);
        number_t polygamma3_2 = num_polygamma(3u, two);
        number_t polygamma3_inf = num_polygamma(3u, NUM_INF);
        number_t neg_half = num_create_from_string("-1/2");
        number_t polygamma3_neg_half = num_polygamma(3u, neg_half);
        number_t fifteen = num_create_from_long(15);
        number_t six = num_create_from_long(6);
        number_t ninety_six = num_create_from_long(96);
        number_t pi4 = num_pow_int(NUM_PI, 4);
        number_t pi4_over_15 = num_div(pi4, fifteen);
        number_t polygamma3_2_want = num_sub(pi4_over_15, six);
        number_t polygamma3_neg_half_want = num_add(pi4, ninety_six);
        number_t erf1 = num_erf(one);
        number_t erfc1 = num_erfc(one);
        number_t w0_1 = num_lambert_w0(one);
        number_t neg_inv_e = num_neg(NUM_INV_E);
        number_t w0_branch = num_lambert_w0(NUM_NEG_INV_E);
        number_t wm1_branch = num_lambert_wm1(NUM_NEG_INV_E);
        number_t productlog_branch = num_productlog(NUM_NEG_INV_E);
        number_t neg_two = num_create_from_string("-2");
        number_t productlog_neg_two = num_productlog(neg_two);
        number_t productlog_exp = num_exp(productlog_neg_two);
        number_t productlog_check = num_mul(productlog_neg_two, productlog_exp);
        number_t lambert_wn_two = num_lambert_wn(two, neg_two);
        number_t lambert_wn_two_exp = num_exp(lambert_wn_two);
        number_t lambert_wn_two_check = num_mul(lambert_wn_two, lambert_wn_two_exp);
        number_t i_over_13 = num_create_from_string("1/13i");
        number_t exp_i_over_13 = num_exp(i_over_13);
        number_t productlog_inverse_arg = num_mul(i_over_13, exp_i_over_13);
        number_t productlog_inverse = num_productlog(productlog_inverse_arg);
        number_t beta22 = num_beta(two, two);
        number_t logbeta22 = num_logbeta(two, two);
        number_t binom = num_binomial(fifty_two, five);
        number_t normal_pdf0 = num_normal_pdf(zero);
        number_t normal_cdf0 = num_normal_cdf(zero);
        number_t e1_1 = num_E1(one);
        number_t pi_over_three = num_div(NUM_PI, three);
        number_t pi_over_six = num_div(NUM_PI, six);
        number_t one_half = num_div(one, two);
        number_t dilog_half = num_dilog(one_half);
        number_t polylog2_half = num_polylog(two, one_half);
        number_t harmonic4_half = num_harmonic_poly(four, one_half);
        number_t dilog_two = num_dilog(two);
        number_t three_halves = num_div(three, two);
        number_t one_quarter = num_div(one, four);
        number_t three_quarters = num_div(three, four);
        number_t versin_pi3 = num_versin(pi_over_three);
        number_t vercos_pi3 = num_vercos(pi_over_three);
        number_t coversin_pi6 = num_coversin(pi_over_six);
        number_t covercos_pi6 = num_covercos(pi_over_six);
        number_t haversin_pi3 = num_haversin(pi_over_three);
        number_t havercos_pi3 = num_havercos(pi_over_three);
        number_t hacoversin_pi6 = num_hacoversin(pi_over_six);
        number_t hacovercos_pi6 = num_hacovercos(pi_over_six);
        number_t arcversin_half = num_arcversin(one_half);
        number_t arcvercos_three_halves = num_arcvercos(three_halves);
        number_t arccoversin_half = num_arccoversin(one_half);
        number_t arccovercos_three_halves = num_arccovercos(three_halves);
        number_t archaversin_quarter = num_archaversin(one_quarter);
        number_t archavercos_three_quarters = num_archavercos(three_quarters);
        number_t archacoversin_quarter = num_archacoversin(one_quarter);
        number_t archacovercos_three_quarters = num_archacovercos(three_quarters);

        assert_number_string_prefix("num_lgamma(5)", lgamma5, "3.178053830347945619646941601297");
        assert_number_string_prefix("num_digamma(1)", digamma1, "-0.577215664901532860606512090082");
        assert_number_string_prefix("num_trigamma(1)", trigamma1, "1.644934066848226436472415166646");
        assert_number_string("num_trigamma(inf)", trigamma_inf, "0");
        assert_number_string("num_tetragamma(inf)", tetragamma_inf, "0");
        assert_number_close_text("num_polygamma(0, 1) = num_digamma(1)", polygamma0_1,
                                 "-0.577215664901532860606512090082", "1e-30");
        assert_number_close_text("num_polygamma(1, 1) = num_trigamma(1)", polygamma1_1,
                                 "1.644934066848226436472415166646", "1e-30");
        assert_number_close_number("num_polygamma(3, 2) = pi^4/15 - 6", polygamma3_2, polygamma3_2_want, "1e-25");
        assert_number_string("num_polygamma(3, inf)", polygamma3_inf, "0");
        assert_number_close_number("num_polygamma(3, -1/2) = pi^4 + 96", polygamma3_neg_half,
                                   polygamma3_neg_half_want, "1e-25");
        assert_number_string_prefix("num_erf(1)", erf1, "0.842700792949714869341220635082");
        assert_number_string_prefix("num_erfc(1)", erfc1, "0.157299207050285130658779364917");
        assert_number_string_prefix("num_lambert_w0(1)", w0_1, "0.567143290409783872999968662210");
        ASSERT_TRUE(num_eq(neg_inv_e, NUM_NEG_INV_E));
        assert_number_string("num_lambert_w0(-1/e)", w0_branch, "-1");
        assert_number_string("num_lambert_wm1(-1/e)", wm1_branch, "-1");
        assert_number_string("num_productlog(-1/e)", productlog_branch, "-1");
        ASSERT_TRUE(!num_is_real(productlog_neg_two));
        assert_number_close_text("num_productlog(-2) satisfies w*exp(w) = -2", productlog_check, "-2", "1e-25");
        assert_number_close_text("num_lambert_wn(2, -2) satisfies w*exp(w) = -2", lambert_wn_two_check, "-2", "1e-25");
        assert_number_close_text("num_productlog((i/13)*exp(i/13)) = i/13", productlog_inverse, "1/13i", "1e-30");
        assert_number_string_prefix("num_beta(2, 2)", beta22, "0.166666666666666666666666666666");
        assert_number_string_prefix("num_logbeta(2, 2)", logbeta22, "-1.791759469228055000812477358380");
        assert_number_string("num_binomial(52, 5)", binom, "2598960");
        assert_number_string_prefix("num_normal_pdf(0)", normal_pdf0, "0.398942280401432677939946059934");
        assert_number_string("num_normal_cdf(0)", normal_cdf0, "0.5");
        assert_number_string_prefix("num_E1(1)", e1_1, "0.219383934395520273677163775460");
        assert_number_close_text("num_dilog(1/2) = pi^2/12 - log(2)^2/2", dilog_half,
                                 "0.58224052646501250590265632015968", "1e-30");
        assert_number_close_text("num_polylog(2, 1/2) = num_dilog(1/2)", polylog2_half,
                                 "0.58224052646501250590265632015968", "1e-30");
        assert_number_string("num_harmonic_poly(4, 1/2)", harmonic4_half, "¹³¹⁄₁₉₂");
        ASSERT_TRUE(!num_is_real(dilog_two));
        assert_number_close_number("num_versin(pi/3) = 1/2", versin_pi3, one_half, "1e-30");
        assert_number_close_number("num_vercos(pi/3) = 3/2", vercos_pi3, three_halves, "1e-30");
        assert_number_close_number("num_coversin(pi/6) = 1/2", coversin_pi6, one_half, "1e-30");
        assert_number_close_number("num_covercos(pi/6) = 3/2", covercos_pi6, three_halves, "1e-30");
        assert_number_close_number("num_haversin(pi/3) = 1/4", haversin_pi3, one_quarter, "1e-30");
        assert_number_close_number("num_havercos(pi/3) = 3/4", havercos_pi3, three_quarters, "1e-30");
        assert_number_close_number("num_hacoversin(pi/6) = 1/4", hacoversin_pi6, one_quarter, "1e-30");
        assert_number_close_number("num_hacovercos(pi/6) = 3/4", hacovercos_pi6, three_quarters, "1e-30");
        assert_number_close_number("num_arcversin(1/2) = pi/3", arcversin_half, pi_over_three, "1e-30");
        assert_number_close_number("num_arcvercos(3/2) = pi/3", arcvercos_three_halves, pi_over_three, "1e-30");
        assert_number_close_number("num_arccoversin(1/2) = pi/6", arccoversin_half, pi_over_six, "1e-30");
        assert_number_close_number("num_arccovercos(3/2) = pi/6", arccovercos_three_halves, pi_over_six, "1e-30");
        assert_number_close_number("num_archaversin(1/4) = pi/3", archaversin_quarter, pi_over_three, "1e-30");
        assert_number_close_number("num_archavercos(3/4) = pi/3", archavercos_three_quarters, pi_over_three, "1e-30");
        assert_number_close_number("num_archacoversin(1/4) = pi/6", archacoversin_quarter, pi_over_six, "1e-30");
        assert_number_close_number("num_archacovercos(3/4) = pi/6", archacovercos_three_quarters, pi_over_six, "1e-30");

        ASSERT_TRUE(num_is_real(lgamma5));
        ASSERT_TRUE(num_is_real(digamma1));
        ASSERT_TRUE(num_is_real(trigamma1));
        ASSERT_TRUE(num_is_real(trigamma_inf));
        ASSERT_TRUE(num_is_real(tetragamma_inf));
        ASSERT_TRUE(num_is_real(polygamma3_2));
        ASSERT_TRUE(num_is_real(polygamma3_inf));
        ASSERT_TRUE(num_is_real(polygamma3_neg_half));
        ASSERT_TRUE(num_is_real(beta22));
        ASSERT_TRUE(num_is_real(logbeta22));

        num_destroy(&zero);
        num_destroy(&one);
        num_destroy(&two);
        num_destroy(&three);
        num_destroy(&four);
        num_destroy(&five);
        num_destroy(&fifty_two);
        num_destroy(&lgamma5);
        num_destroy(&digamma1);
        num_destroy(&trigamma1);
        num_destroy(&trigamma_inf);
        num_destroy(&tetragamma_inf);
        num_destroy(&polygamma0_1);
        num_destroy(&polygamma1_1);
        num_destroy(&polygamma3_2);
        num_destroy(&polygamma3_inf);
        num_destroy(&neg_half);
        num_destroy(&polygamma3_neg_half);
        num_destroy(&fifteen);
        num_destroy(&six);
        num_destroy(&ninety_six);
        num_destroy(&pi4);
        num_destroy(&pi4_over_15);
        num_destroy(&polygamma3_2_want);
        num_destroy(&polygamma3_neg_half_want);
        num_destroy(&erf1);
        num_destroy(&erfc1);
        num_destroy(&w0_1);
        num_destroy(&neg_inv_e);
        num_destroy(&w0_branch);
        num_destroy(&wm1_branch);
        num_destroy(&productlog_branch);
        num_destroy(&neg_two);
        num_destroy(&productlog_neg_two);
        num_destroy(&productlog_exp);
        num_destroy(&productlog_check);
        num_destroy(&lambert_wn_two);
        num_destroy(&lambert_wn_two_exp);
        num_destroy(&lambert_wn_two_check);
        num_destroy(&i_over_13);
        num_destroy(&exp_i_over_13);
        num_destroy(&productlog_inverse_arg);
        num_destroy(&productlog_inverse);
        num_destroy(&beta22);
        num_destroy(&logbeta22);
        num_destroy(&binom);
        num_destroy(&normal_pdf0);
        num_destroy(&normal_cdf0);
        num_destroy(&e1_1);
        num_destroy(&pi_over_three);
        num_destroy(&pi_over_six);
        num_destroy(&one_half);
        num_destroy(&dilog_half);
        num_destroy(&polylog2_half);
        num_destroy(&harmonic4_half);
        num_destroy(&dilog_two);
        num_destroy(&three_halves);
        num_destroy(&one_quarter);
        num_destroy(&three_quarters);
        num_destroy(&versin_pi3);
        num_destroy(&vercos_pi3);
        num_destroy(&coversin_pi6);
        num_destroy(&covercos_pi6);
        num_destroy(&haversin_pi3);
        num_destroy(&havercos_pi3);
        num_destroy(&hacoversin_pi6);
        num_destroy(&hacovercos_pi6);
        num_destroy(&arcversin_half);
        num_destroy(&arcvercos_three_halves);
        num_destroy(&arccoversin_half);
        num_destroy(&arccovercos_three_halves);
        num_destroy(&archaversin_quarter);
        num_destroy(&archavercos_three_quarters);
        num_destroy(&archacoversin_quarter);
        num_destroy(&archacovercos_three_quarters);
    }

    {
        size_t saved_precision = num_get_default_prec_bits();
        number_t z;
        number_t z_plus_one;
        number_t psi_z;
        number_t psi_z_plus_one;
        number_t reciprocal;
        number_t recurrence_lhs;
        number_t recurrence_difference;
        number_t conjugate_z;
        number_t psi_conjugate_z;
        number_t conjugate_psi_z;

        ASSERT_EQ_INT(num_set_default_prec_bits(1280u), 0);
        z = num_create_from_string("1+i");
        z_plus_one = num_add(z, NUM_ONE);
        psi_z = num_digamma(z);
        psi_z_plus_one = num_digamma(z_plus_one);
        reciprocal = num_inv(z);
        recurrence_lhs = num_sub(psi_z_plus_one, psi_z);
        recurrence_difference = num_sub(recurrence_lhs, reciprocal);
        conjugate_z = num_conj(z);
        psi_conjugate_z = num_digamma(conjugate_z);
        conjugate_psi_z = num_conj(psi_z);

        ASSERT_EQ_INT((int)num_get_prec_bits(psi_z), 1280);
        assert_number_close_text("1280-bit complex digamma recurrence", recurrence_difference, "0", "1e-380");
        assert_number_close_number("1280-bit complex digamma conjugation", psi_conjugate_z, conjugate_psi_z,
                                   "1e-380");

        num_destroy(&conjugate_psi_z);
        num_destroy(&psi_conjugate_z);
        num_destroy(&conjugate_z);
        num_destroy(&recurrence_difference);
        num_destroy(&recurrence_lhs);
        num_destroy(&reciprocal);
        num_destroy(&psi_z_plus_one);
        num_destroy(&psi_z);
        num_destroy(&z_plus_one);
        num_destroy(&z);
        ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
    }

    {
        size_t saved_precision = num_get_default_prec_bits();
        number_t order = num_create_from_string("0.5");
        number_t argument = num_create_from_string("1.25");
        number_t two;
        number_t pi;
        number_t pi_x;
        number_t quotient;
        number_t scale;
        number_t sine;
        number_t cosine;
        number_t scaled_cosine;
        number_t want_j;
        number_t want_y;
        number_t got_j;
        number_t got_y;
        number_t zero;
        number_t one;
        number_t lommel;
        number_t j0;
        number_t want_lommel;

        ASSERT_EQ_INT(num_set_default_prec_bits(384u), 0);
        ASSERT_EQ_INT(num_set_prec_bits(&order, 384u), 0);
        ASSERT_EQ_INT(num_set_prec_bits(&argument, 384u), 0);
        two = num_create_from_long(2);
        pi = num_const_prec(NUM_PI, 384u);
        pi_x = num_mul(pi, argument);
        quotient = num_div(two, pi_x);
        scale = num_sqrt(quotient);
        sine = num_sin(argument);
        cosine = num_cos(argument);
        want_j = num_mul(scale, sine);
        scaled_cosine = num_mul(scale, cosine);
        want_y = num_neg(scaled_cosine);
        got_j = num_bessel_j(order, argument);
        got_y = num_bessel_y(order, argument);
        zero = num_create_from_long(0);
        one = num_create_from_long(1);
        lommel = num_lommel_s(one, zero, argument);
        j0 = num_bessel_j(zero, argument);
        want_lommel = num_sub(one, j0);

        assert_number_close_number("high-precision num_bessel_j(1/2, x) half-order identity", got_j, want_j,
                                   "1e-100");
        assert_number_close_number("high-precision num_bessel_y(1/2, x) half-order identity", got_y, want_y,
                                   "1e-100");
        assert_number_close_number("high-precision num_lommel_s(1, 0, x) = 1 - J0(x)", lommel, want_lommel,
                                   "1e-100");
        num_destroy(&want_lommel);
        num_destroy(&j0);
        num_destroy(&lommel);
        num_destroy(&one);
        num_destroy(&zero);
        num_destroy(&got_y);
        num_destroy(&got_j);
        num_destroy(&want_y);
        num_destroy(&want_j);
        num_destroy(&scaled_cosine);
        num_destroy(&cosine);
        num_destroy(&sine);
        num_destroy(&scale);
        num_destroy(&quotient);
        num_destroy(&pi_x);
        num_destroy(&pi);
        num_destroy(&two);
        num_destroy(&argument);
        num_destroy(&order);
        ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
    }

    {
        size_t saved_precision = num_get_default_prec_bits();
        number_t one;
        number_t two;
        number_t half;
        number_t dilog_half;
        number_t polylog2_half;
        number_t pi;
        number_t pi2;
        number_t twelve;
        number_t pi2_over_12;
        number_t log2;
        number_t log2_sq;
        number_t log2_sq_half;
        number_t dilog_half_want;
        number_t dilog_two;
        number_t dilog_two_real;
        number_t dilog_two_imag;
        number_t four;
        number_t pi2_over_4;
        number_t pi_log2;
        number_t neg_pi_log2;

        ASSERT_EQ_INT(num_set_default_prec_bits(640u), 0);
        one = num_create_from_long(1);
        two = num_create_from_long(2);
        four = num_create_from_long(4);
        twelve = num_create_from_long(12);
        half = num_div(one, two);
        pi = num_const_prec(NUM_PI, 640u);
        pi2 = num_mul(pi, pi);
        pi2_over_12 = num_div(pi2, twelve);
        log2 = num_log(two);
        log2_sq = num_mul(log2, log2);
        log2_sq_half = num_div(log2_sq, two);
        dilog_half_want = num_sub(pi2_over_12, log2_sq_half);
        dilog_half = num_dilog(half);
        polylog2_half = num_polylog(two, half);
        dilog_two = num_dilog(two);
        dilog_two_real = num_real_part(dilog_two);
        dilog_two_imag = num_imag_part(dilog_two);
        pi2_over_4 = num_div(pi2, four);
        pi_log2 = num_mul(pi, log2);
        neg_pi_log2 = num_neg(pi_log2);

        assert_number_close_number("high-precision num_dilog(1/2)", dilog_half, dilog_half_want, "1e-180");
        assert_number_close_number("high-precision num_polylog(2, 1/2)", polylog2_half, dilog_half_want, "1e-180");
        ASSERT_TRUE(!num_is_real(dilog_two));
        assert_number_close_number("high-precision Re num_dilog(2) = pi^2/4", dilog_two_real, pi2_over_4, "1e-180");
        assert_number_close_number("high-precision Im num_dilog(2) = -pi ln 2", dilog_two_imag, neg_pi_log2, "1e-180");

        num_destroy(&neg_pi_log2);
        num_destroy(&pi_log2);
        num_destroy(&pi2_over_4);
        num_destroy(&dilog_two_imag);
        num_destroy(&dilog_two_real);
        num_destroy(&dilog_two);
        num_destroy(&polylog2_half);
        num_destroy(&dilog_half);
        num_destroy(&dilog_half_want);
        num_destroy(&log2_sq_half);
        num_destroy(&log2_sq);
        num_destroy(&log2);
        num_destroy(&pi2_over_12);
        num_destroy(&twelve);
        num_destroy(&pi2);
        num_destroy(&pi);
        num_destroy(&half);
        num_destroy(&four);
        num_destroy(&two);
        num_destroy(&one);
        ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
    }

    {
        size_t saved_precision = num_get_default_prec_bits();
        number_t five;
        number_t gamma_inv_5;
        number_t lgamma_gamma_inv_5;
        number_t log_5;
        number_t residual;
        number_t residual_mag;
        number_t tolerance;
        string_t *residual_text;
        bool within_tolerance;

        ASSERT_EQ_INT(num_set_default_prec_digits(201u), 0);
        five = num_create_from_string("5");
        gamma_inv_5 = num_gammainv(five);
        lgamma_gamma_inv_5 = num_lgamma(gamma_inv_5);
        log_5 = num_log(five);
        residual = num_sub(lgamma_gamma_inv_5, log_5);
        residual_mag = num_abs(residual);
        tolerance = num_pow10(-193);
        residual_text = num_to_string(residual_mag);

        printf(C_WHITE C_BOLD "lgamma(gammainv(5)) - ln(5) at 193 displayed digits" C_RESET "\n");
        printf("    tolerance = 1e-193\n");
        printf("    residual  = %s\n\n", residual_text ? string_c_str(residual_text) : "(num_to_string failed)");
        within_tolerance = num_lt(residual_mag, tolerance);

        string_free(residual_text);
        num_destroy(&tolerance);
        num_destroy(&residual_mag);
        num_destroy(&residual);
        num_destroy(&log_5);
        num_destroy(&lgamma_gamma_inv_5);
        num_destroy(&gamma_inv_5);
        num_destroy(&five);
        ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
        ASSERT_TRUE(within_tolerance);
    }

    {
        size_t saved_precision = num_get_default_prec_bits();
        number_t one = num_create_from_long(1);
        number_t six = num_create_from_long(6);
        number_t fifteen = num_create_from_long(15);
        number_t z;
        number_t z_plus_one;
        number_t z4;
        number_t psi3_1;
        number_t pi;
        number_t pi4;
        number_t pi4_over_15;
        number_t psi3_z;
        number_t psi3_z_plus_one;
        number_t lhs;
        number_t rhs;
        number_t residual;
        number_t residual_mag;
        number_t tolerance;
        string_t *residual_text;
        bool within_tolerance;

        ASSERT_EQ_INT(num_set_default_prec_bits(640u), 0);
        z = num_create_from_string("1.25 + 0.75i");
        z_plus_one = num_add(z, one);
        z4 = num_pow_int(z, 4);
        psi3_1 = num_polygamma(3u, one);
        pi = num_const_prec(NUM_PI, 640u);
        pi4 = num_pow_int(pi, 4);
        pi4_over_15 = num_div(pi4, fifteen);
        psi3_z = num_polygamma(3u, z);
        psi3_z_plus_one = num_polygamma(3u, z_plus_one);
        lhs = num_sub(psi3_z, psi3_z_plus_one);
        rhs = num_div(six, z4);
        residual = num_sub(lhs, rhs);
        residual_mag = num_abs(residual);
        tolerance = num_pow10(-180);
        residual_text = num_to_string(residual_mag);

        assert_number_close_number("high-precision num_polygamma(3, 1) = pi^4/15", psi3_1, pi4_over_15, "1e-180");
        printf(C_WHITE C_BOLD "high-precision complex recurrence: ψ⁽³⁾(z)-ψ⁽³⁾(z+1)=6/z^4" C_RESET "\n");
        printf("    tolerance = 1e-180\n");
        printf("    residual  = %s\n\n", residual_text ? string_c_str(residual_text) : "(num_to_string failed)");
        within_tolerance = num_lt(residual_mag, tolerance);

        string_free(residual_text);
        num_destroy(&tolerance);
        num_destroy(&residual_mag);
        num_destroy(&residual);
        num_destroy(&rhs);
        num_destroy(&lhs);
        num_destroy(&psi3_z_plus_one);
        num_destroy(&psi3_z);
        num_destroy(&pi4_over_15);
        num_destroy(&pi4);
        num_destroy(&pi);
        num_destroy(&psi3_1);
        num_destroy(&z4);
        num_destroy(&z_plus_one);
        num_destroy(&z);
        num_destroy(&fifteen);
        num_destroy(&six);
        num_destroy(&one);
        ASSERT_EQ_INT(num_set_default_prec_bits(saved_precision), 0);
        ASSERT_TRUE(within_tolerance);
    }

    {
        number_t z = num_create_from_string("0.2 + 0.1i");
        number_t hypergeometric = num_hypergeometric_pFq(NULL, 0u, NULL, 0u, z);
        number_t want_hypergeometric = num_exp(z);
        number_t a = num_create_from_string("1.25");
        number_t b[] = {num_create_from_string("0.5"), num_create_from_string("1.5"), num_create_from_string("2")};
        number_t c = num_clone(a);
        number_t variables[] = {num_create_from_string("0.1"), num_create_from_string("0.2"),
                                num_create_from_string("0.15")};
        number_t lauricella = num_lauricella_f(a, b, c, variables, 3u);
        number_t want_lauricella = num_create_from_long(1);

        for (size_t i = 0u; i < 3u; ++i) {
            number_t one_minus = num_sub(NUM_ONE, variables[i]);
            number_t negative_b = num_neg(b[i]);
            number_t factor = num_pow(one_minus, negative_b);
            number_t next = num_mul(want_lauricella, factor);

            num_destroy(&want_lauricella);
            want_lauricella = next;
            num_destroy(&factor);
            num_destroy(&negative_b);
            num_destroy(&one_minus);
        }

        assert_number_close_number("num 0F0(z) = exp(z)", hypergeometric, want_hypergeometric, "1e-27");
        assert_number_close_number("general num Lauricella FD product identity", lauricella, want_lauricella,
                                   "1e-26");

        num_destroy(&want_lauricella);
        num_destroy(&lauricella);
        for (size_t i = 0u; i < 3u; ++i) {
            num_destroy(&variables[i]);
            num_destroy(&b[i]);
        }
        num_destroy(&c);
        num_destroy(&a);
        num_destroy(&want_hypergeometric);
        num_destroy(&hypergeometric);
        num_destroy(&z);
    }


    {
        number_t three = num_create_from_long(3);
        number_t zero = num_create_from_long(0);
        number_t complex_argument = num_create_from_string("2 + 3i");
        number_t zeta_three = num_zeta(three);
        number_t zeta_complex = num_zeta(complex_argument);
        number_t derivative_zero = num_zetap(zero);
        number_t derivative_nan = num_zetap(NUM_NAN);
        number_t two_and_half = num_create_from_string("2.5");
        number_t one_hundred_and_one = num_create_from_long(101);
        number_t hurwitz = num_zetah(two_and_half, one_hundred_and_one);
        number_t hurwitz_derivative = num_zatahp(two_and_half, one_hundred_and_one);

        assert_number_string_prefix("num_zeta(3)", zeta_three, "1.2020569031595942853997381615114499");
        assert_number_close_text("num_zeta(2 + 3i)", zeta_complex,
                                 "0.798021985146275720622294500724813 - 0.113744308052938500215913365857315i",
                                 "1e-30");
        assert_number_string_prefix("num_zetap(0)", derivative_zero,
                                    "-0.9189385332046727417803297364056176");
        TEST_ASSERT_TRUE(num_is_nan(derivative_nan), "num_zetap(NaN) remains NaN");
        assert_number_string_prefix("num_zetah(2.5, 101)", hurwitz,
                                    "0.000661687499453171542062211501479711744239330816315948606222019");
        assert_number_string_prefix("num_zatahp(2.5, 101)", hurwitz_derivative,
                                    "-0.00349161965653033810674455840434715303797124292360183374983833");

        num_destroy(&hurwitz_derivative);
        num_destroy(&hurwitz);
        num_destroy(&one_hundred_and_one);
        num_destroy(&two_and_half);
        num_destroy(&derivative_nan);
        num_destroy(&derivative_zero);
        num_destroy(&zeta_complex);
        num_destroy(&zeta_three);
        num_destroy(&complex_argument);
        num_destroy(&zero);
        num_destroy(&three);
    }

    {
        number_t q = num_create_from_string("1/2");
        number_t one = num_create_from_long(1L);
        number_t two = num_create_from_long(2L);
        number_t psi_two = number_qdigamma(q, two);
        number_t psi_one = num_qdigamma(q, one);
        number_t recurrence = num_sub(psi_two, psi_one);

        assert_number_close_text("number_qdigamma recurrence", recurrence,
                                 "0.69314718055994530941723212145817656807550013436026", "1e-29");
        num_destroy(&recurrence);
        num_destroy(&psi_one);
        num_destroy(&psi_two);
        num_destroy(&two);
        num_destroy(&one);
        num_destroy(&q);
    }
}
