#!/usr/bin/env python3
"""
Configure the private almanac database for the current user.
"""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path
import shlex
import stat
import subprocess
import sys
import threading


ROOT = Path(__file__).resolve().parents[1]
ALMANAC_DB_SOURCE_DIR = ROOT / "packaging" / "almanac-db"
ALMANAC_SQL = ALMANAC_DB_SOURCE_DIR / "mars_almanac.sql"
DB_PATH_ENV = "MARS_ALMANAC_DB_PATH"
DB_KEY_ENV = "MARS_ALMANAC_DB_KEY"
SQLCIPHER = os.environ.get("SQLCIPHER", "sqlcipher").strip() or "sqlcipher"


def mars_home() -> Path:
    custom = os.environ.get("MARS_HOME", "").strip()
    if custom:
        return Path(custom).expanduser()
    return Path.home() / ".mars"


def config_path() -> Path:
    return mars_home() / "config" / "almanac-db.env"


def default_db_path() -> Path:
    return mars_home() / "almanac" / "almanac.db"


def legacy_default_db_path() -> Path:
    return mars_home() / "almanac.db"


def normalize_db_path(raw_path: str) -> str:
    text = raw_path.strip()

    if not text:
        return ""
    try:
        expanded = Path(text).expanduser()
    except RuntimeError:
        return text
    if expanded == legacy_default_db_path():
        return str(default_db_path())
    return text


def parse_existing_config(path: Path) -> tuple[str, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return "", ""

    db_path = ""
    db_key = ""
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        try:
            value = shlex.split(raw_value)[0] if raw_value else ""
        except ValueError:
            value = raw_value.strip("'\"")
        if key == DB_PATH_ENV:
            db_path = value
        elif key == DB_KEY_ENV:
            db_key = value
    return normalize_db_path(db_path), db_key


def prompt_secret(prompt: str, default: str, *, confirm: bool) -> str:
    suffix = " [leave blank to keep current key]" if default else ""
    while True:
        response = getpass.getpass(f"{prompt}{suffix}: ").strip()
        if not response and default:
            return default
        if not response:
            print("An almanac database password is required.", file=sys.stderr)
            continue
        if not confirm and not default:
            return response
        repeat = getpass.getpass("Confirm password: ").strip()
        if response == repeat:
            return response
        print("Passwords did not match. Please try again.", file=sys.stderr)


def shell_export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def ensure_private_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)


class Spinner:
    def __init__(self, message: str, *, stream=None) -> None:
        self.message = message
        self.stream = stream if stream is not None else sys.stderr
        self.enabled = hasattr(self.stream, "isatty") and self.stream.isatty()
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def __enter__(self) -> "Spinner":
        if not self.enabled:
            print(f"{self.message}...", file=self.stream, flush=True)
            return self
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if not self.enabled:
            if exc_type is None:
                print(f"{self.message}: done", file=self.stream, flush=True)
            return
        self._stop.set()
        if self._thread is not None:
            self._thread.join()
        status = "done" if exc_type is None else "failed"
        print(f"\r{self.message}: {status}   ", file=self.stream, flush=True)

    def _run(self) -> None:
        frames = "|/-\\"
        index = 0
        while not self._stop.wait(0.1):
            frame = frames[index % len(frames)]
            print(f"\r{self.message}... {frame}", end="", file=self.stream, flush=True)
            index += 1


def write_config(path: Path, db_path: str, db_key: str) -> None:
    ensure_private_dir(path.parent)
    body = "\n".join(
        [
            "# Generated by tools/configure_mars_lab_almanac_db.py",
            shell_export(DB_PATH_ENV, db_path),
            shell_export(DB_KEY_ENV, db_key),
            "",
        ]
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_almanac_database(db_path: Path, db_key: str) -> None:
    with Spinner("Preparing private MARS storage"):
        ensure_private_dir(mars_home())
        ensure_private_dir(db_path.parent)

    if not ALMANAC_SQL.exists():
        raise RuntimeError(f"missing packaged almanac schema SQL: {ALMANAC_SQL}")

    script_lines = [
        ".bail on",
        f"PRAGMA key = {sql_quote(db_key)};",
        "PRAGMA foreign_keys = ON;",
        f".read {ALMANAC_SQL.relative_to(ROOT)}",
    ]
    script_lines.append("")
    script = "\n".join(script_lines)

    with Spinner("Building encrypted almanac database"):
        completed = subprocess.run(
            [SQLCIPHER, str(db_path)],
            cwd=ROOT,
            input=script,
            text=True,
            capture_output=True,
        )
    if completed.returncode != 0:
        raise RuntimeError((completed.stderr or completed.stdout or "sqlcipher failed").strip())
    db_path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db-path", default="", help="Almanac DB path to store.")
    parser.add_argument("--db-key", default="", help="Almanac DB key to store.")
    parser.add_argument("--noninteractive", action="store_true", help="Write config without prompting.")
    args = parser.parse_args()

    path = config_path()
    existing_path, existing_key = parse_existing_config(path)

    default_path = (
        normalize_db_path(args.db_path)
        or normalize_db_path(os.environ.get(DB_PATH_ENV, ""))
        or existing_path
        or str(default_db_path())
    )
    default_key = (
        args.db_key.strip()
        or os.environ.get(DB_KEY_ENV, "").strip()
        or existing_key
    )

    interactive = sys.stdin.isatty() and not args.noninteractive
    if interactive:
        print("Almanac database setup")
        print(f"Config file: {path}")
        db_path = default_path
        db_key = prompt_secret(
            "Choose a password to protect your private almanac database",
            default_key,
            confirm=not bool(default_key),
        )
    else:
        db_path = default_path
        db_key = default_key

    if not db_path:
        print("No almanac database path was provided.", file=sys.stderr)
        return 1
    if not db_key:
        print("No almanac database password was provided.", file=sys.stderr)
        return 1

    try:
        build_almanac_database(Path(db_path).expanduser(), db_key)
        with Spinner("Saving almanac database configuration"):
            write_config(path, db_path, db_key)
    except Exception as exc:
        print(f"Failed to configure the almanac database: {exc}", file=sys.stderr)
        return 1

    print(f"Built almanac database at {db_path}")
    print(f"Wrote almanac database configuration to {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
