#!/usr/bin/env python3
"""
Optionally configure the WeatherAPI key for the current user.
"""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path
import shlex
import stat
import sys


WEATHER_KEY_ENV = "MARS_WEATHER_API_KEY"
LEGACY_WEATHER_KEY_ENV = "WEATHERAPI_KEY"


def mars_home() -> Path:
    custom = os.environ.get("MARS_HOME", "").strip()
    if custom:
        return Path(custom).expanduser()
    return Path.home() / ".mars"


def config_path() -> Path:
    return mars_home() / "config" / "weather.env"


def display_config_path() -> str:
    custom = os.environ.get("MARS_HOME", "").strip()
    if custom:
        return str(config_path())
    return "~/.mars/config/weather.env"


def ensure_private_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)


def shell_export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def parse_existing_key(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""

    for line in text.splitlines():
        raw = line.strip()
        if raw.startswith("export "):
            raw = raw[7:].strip()
        if "=" not in raw:
            continue
        key, raw_value = raw.split("=", 1)
        if key.strip() not in (WEATHER_KEY_ENV, LEGACY_WEATHER_KEY_ENV):
            continue
        try:
            parts = shlex.split(raw_value.strip())
            return parts[0] if parts else ""
        except ValueError:
            return raw_value.strip().strip("'\"")
    return ""


def prompt_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        answer = input(f"{prompt} {suffix}: ").strip().lower()
        if not answer:
            return default
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print("Please answer yes or no.", file=sys.stderr)


def prompt_key(default_key: str) -> str:
    if default_key:
        print("A weather API key is already configured.")
        print("If you need a new key, create or manage one here:")
        print("  https://www.weatherapi.com/signup.aspx")
        if not prompt_yes_no("Would you like to replace it?", default=False):
            return default_key
        prompt = "Enter your new WeatherAPI key"
        suffix = " [leave blank to skip weather setup]"
    else:
        prompt = "Enter your WeatherAPI key"
        suffix = " [leave blank to skip weather setup]"

    while True:
        key = getpass.getpass(f"{prompt}{suffix}: ").strip()
        if not key:
            return ""
        repeat = getpass.getpass("Confirm WeatherAPI key: ").strip()
        if key == repeat:
            return key
        print("Keys did not match. Please try again.", file=sys.stderr)


def write_config(path: Path, weather_key: str) -> None:
    ensure_private_dir(path.parent)
    body = "\n".join(
        [
            "# Generated by tools/configure_mars_lab_weather.py",
            shell_export(WEATHER_KEY_ENV, weather_key),
            "",
        ]
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weather-key", default="", help="WeatherAPI key to store.")
    parser.add_argument(
        "--noninteractive",
        action="store_true",
        help="Write config without prompting, using args/env/current settings.",
    )
    args = parser.parse_args()

    path = config_path()
    existing_key = parse_existing_key(path)
    default_key = (
        args.weather_key.strip()
        or os.environ.get(WEATHER_KEY_ENV, "").strip()
        or os.environ.get(LEGACY_WEATHER_KEY_ENV, "").strip()
        or existing_key
    )

    interactive = sys.stdin.isatty() and not args.noninteractive
    if interactive:
        print("Optional weather setup")
        print("MARS Lab can show minimum and maximum temperature, and chance of rain, in datetime mode.")
        print("To enable this, create a free WeatherAPI account and copy your key from:")
        print("  https://www.weatherapi.com/signup.aspx")
        print("You can ignore this now and configure it later by creating:")
        print(f"  {display_config_path()}")
        if not prompt_yes_no("Would you like to configure a weather API key now?", default=False):
            print("Skipping weather API setup.")
            return 0
        weather_key = prompt_key(default_key)
        if not weather_key:
            print("Skipping weather API setup.")
            return 0
    else:
        weather_key = default_key
        if not weather_key:
            return 0

    try:
        write_config(path, weather_key)
    except Exception as exc:
        print(f"Failed to save weather API configuration: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote weather API configuration to {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
