#!/usr/bin/env python3
"""
Configure the private jurisdiction database for the current user.
"""

from __future__ import annotations

import argparse
import getpass
import os
from pathlib import Path
import shlex
import stat
import subprocess
import sys
import tempfile
import threading

from jurisdiction_calendar import LOCATION_ENV, LocationCatalogue, choose_location, populate_calendar
from jurisdiction_calendar_languages import LANGUAGE_ENV, choose_language


ROOT = Path(__file__).resolve().parents[1]
JURISDICTION_DB_SOURCE_DIR = ROOT / "packaging" / "jurisdiction-db"
JURISDICTION_RULES_SQL = JURISDICTION_DB_SOURCE_DIR / "mars_holiday_rules.sql"
DB_PATH_ENV = "MARS_JURISDICTION_DB_PATH"
DB_KEY_ENV = "MARS_JURISDICTION_DB_KEY"
SQLCIPHER = os.environ.get("SQLCIPHER", "sqlcipher").strip() or "sqlcipher"


def mars_home() -> Path:
    custom = os.environ.get("MARS_HOME", "").strip()
    if custom:
        return Path(custom).expanduser()
    return Path.home() / ".mars"


def config_path() -> Path:
    return mars_home() / "config" / "jurisdiction-db.env"


def weather_config_path() -> Path:
    return mars_home() / "config" / "weather.env"


def default_db_path() -> Path:
    return mars_home() / "jurisdiction" / "mars_jurisdiction_rules.db"


def read_config(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}

    values = {}
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        try:
            value = shlex.split(raw_value)[0] if raw_value else ""
        except ValueError:
            value = raw_value.strip("'\"")
        if key in (DB_PATH_ENV, DB_KEY_ENV, LOCATION_ENV, LANGUAGE_ENV):
            values[key] = value
    return values


def prompt_secret(prompt: str, default: str, *, confirm: bool) -> str:
    suffix = " [leave blank to keep current key]" if default else ""
    while True:
        response = getpass.getpass(f"{prompt}{suffix}: ").strip()
        if not response and default:
            return default
        if not response:
            print("A jurisdiction database password is required.", file=sys.stderr)
            continue
        if not confirm and not default:
            return response
        repeat = getpass.getpass("Confirm password: ").strip()
        if response == repeat:
            return response
        print("Passwords did not match. Please try again.", file=sys.stderr)


def shell_export(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def ensure_private_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)


class Spinner:
    def __init__(self, message: str, *, stream=None) -> None:
        self.message = message
        self.stream = stream if stream is not None else sys.stderr
        self.enabled = hasattr(self.stream, "isatty") and self.stream.isatty()
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def __enter__(self) -> "Spinner":
        if not self.enabled:
            print(f"{self.message}...", file=self.stream, flush=True)
            return self
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if not self.enabled:
            if exc_type is None:
                print(f"{self.message}: done", file=self.stream, flush=True)
            return
        self._stop.set()
        if self._thread is not None:
            self._thread.join()
        status = "done" if exc_type is None else "failed"
        print(f"\r{self.message}: {status}   ", file=self.stream, flush=True)

    def _run(self) -> None:
        frames = "|/-\\"
        index = 0
        while not self._stop.wait(0.1):
            frame = frames[index % len(frames)]
            print(f"\r{self.message}... {frame}", end="", file=self.stream, flush=True)
            index += 1


def prepare_private_storage(db_path: Path) -> None:
    home = mars_home()

    ensure_private_dir(home)
    ensure_private_dir(config_path().parent)
    ensure_private_dir(db_path.parent)


def write_config(path: Path, db_path: str, db_key: str, location: str, language: str) -> None:
    ensure_private_dir(path.parent)
    body = "\n".join(
        [
            "# Generated by tools/configure_mars_lab_jurisdiction_db.py",
            shell_export(DB_PATH_ENV, db_path),
            shell_export(DB_KEY_ENV, db_key),
            shell_export(LOCATION_ENV, location),
            shell_export(LANGUAGE_ENV, language),
            "",
        ]
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_jurisdiction_database(db_path: Path, db_key: str, requested: str = "",
                                saved: str = "", interactive: bool = False, language: str = "",
                                saved_language: str = "") -> tuple[str, str]:
    with Spinner("Preparing private MARS storage"):
        prepare_private_storage(db_path)

    script = "\n".join(
        [
            ".bail on",
            f"PRAGMA key = {sql_quote(db_key)};",
            "PRAGMA foreign_keys = ON;",
            f".read {JURISDICTION_RULES_SQL.relative_to(ROOT)}",
            "",
        ]
    )
    # Validate the location and finish the calendar before replacing an existing DB.
    with tempfile.TemporaryDirectory(prefix=".mars-jurisdiction-", dir=db_path.parent) as staging:
        temporary_db = Path(staging) / "jurisdiction.db"
        with Spinner("Building encrypted jurisdiction database"):
            completed = subprocess.run(
                [SQLCIPHER, str(temporary_db)], cwd=ROOT, input=script,
                text=True, capture_output=True, timeout=120,
            )
        if completed.returncode != 0:
            message = (completed.stderr or completed.stdout or "sqlcipher failed").strip()
            raise RuntimeError(message.replace(db_key, "<redacted>"))
        catalogue = LocationCatalogue(temporary_db, db_key, SQLCIPHER)
        location = choose_location(catalogue, requested, saved, interactive)
        locale = choose_language(temporary_db, db_key, location.jurisdiction, language,
                                 saved_language, interactive, SQLCIPHER, timezone=location.timezone, town=location.name)
        with Spinner(f"Preparing calendar_local for {location.label}"):
            populate_calendar(temporary_db, db_key, location, SQLCIPHER, locale)
        temporary_db.chmod(stat.S_IRUSR | stat.S_IWUSR)
        os.replace(temporary_db, db_path)
    return location.label, locale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("location", nargs="?", default=os.environ.get("MARS_CALENDAR_LOCATION_ARGUMENT", ""),
                        help="Calendar town, optionally qualified as 'town, jurisdiction'.")
    parser.add_argument("--db-path", default="", help="Jurisdiction DB path to store.")
    parser.add_argument("--language", default=os.environ.get("MARS_CALENDAR_LANGUAGE_ARGUMENT", ""),
                        help="Calendar language name, code or locale; otherwise selected from the menu.")
    parser.add_argument("--db-key", default="", help="Jurisdiction DB key to store.")
    parser.add_argument(
        "--noninteractive",
        action="store_true",
        help="Write config without prompting, using args/env/defaults.",
    )
    args = parser.parse_args()

    path = config_path()
    existing = read_config(path)
    existing_path, existing_key = existing.get(DB_PATH_ENV, ""), existing.get(DB_KEY_ENV, "")
    saved_location = os.environ.get(LOCATION_ENV, "").strip() or existing.get(LOCATION_ENV, "")
    saved_language = os.environ.get(LANGUAGE_ENV, "").strip() or existing.get(LANGUAGE_ENV, "")

    default_path = (
        args.db_path.strip()
        or os.environ.get(DB_PATH_ENV, "").strip()
        or existing_path
        or str(default_db_path())
    )
    default_key = (
        args.db_key.strip()
        or os.environ.get(DB_KEY_ENV, "").strip()
        or existing_key
    )

    interactive = sys.stdin.isatty() and not args.noninteractive
    if interactive:
        print("Jurisdiction database setup")
        print(f"Config file: {path}")
        db_path = default_path
        db_key = prompt_secret(
            "Choose a password to protect your private jurisdiction database",
            default_key,
            confirm=not bool(default_key),
        )
    else:
        db_path = default_path
        db_key = default_key

    if not db_path:
        print("No jurisdiction database path was provided.", file=sys.stderr)
        return 1
    if not db_key:
        print("No jurisdiction database password was provided.", file=sys.stderr)
        return 1

    try:
        location, language = build_jurisdiction_database(Path(db_path).expanduser(), db_key,
                                                         args.location, saved_location, interactive,
                                                         args.language, saved_language)
        with Spinner("Saving jurisdiction database configuration"):
            write_config(path, db_path, db_key, location, language)
    except Exception as exc:
        print(f"Failed to configure the jurisdiction database: {exc}", file=sys.stderr)
        return 1

    print(f"Built jurisdiction database at {db_path}")
    print(f"Wrote jurisdiction database configuration to {path}")
    print(f"calendar_local language: {language}")
    print(f"calendar_local location: {location}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
