#!/usr/bin/env python3
"""Generate compact frame-rotation Chebyshev rows for the almanac DB."""

from __future__ import annotations

import argparse
from pathlib import Path
import struct
import sys

try:
    import erfa
except ModuleNotFoundError as exc:  # pragma: no cover
    print(f"Missing ERFA dependency for frame rotation generation: {exc}", file=sys.stderr)
    raise SystemExit(1)

try:
    import numpy as np
except ModuleNotFoundError as exc:  # pragma: no cover
    print(f"Missing NumPy dependency for frame rotation generation: {exc}", file=sys.stderr)
    raise SystemExit(1)


J2000_JD = 2451545.0
J2000_OBLIQUITY_RAD = np.deg2rad(84381.448 / 3600.0)
FRAME_IDS = {
    "ECLIPJ2000": 1,
    "TRUE_EQUATOR_DATE": 2,
}


def jd_from_gregorian(year: int, month: int, day: int) -> float:
    a = (14 - month) // 12
    y = year + 4800 - a
    m = month + 12 * a - 3
    jdn = day + ((153 * m + 2) // 5) + 365 * y + y // 4 - y // 100 + y // 400 - 32045
    return float(jdn) - 0.5


def eclipj2000_to_j2000_equatorial() -> np.ndarray:
    c = np.cos(J2000_OBLIQUITY_RAD)
    s = np.sin(J2000_OBLIQUITY_RAD)
    return np.array(
        [
            [1.0, 0.0, 0.0],
            [0.0, c, -s],
            [0.0, s, c],
        ],
        dtype=float,
    )


def rotation_matrix(jd: float) -> np.ndarray:
    rbpn = np.array(erfa.pnm06a(2400000.5, jd - 2400000.5), dtype=float)
    return rbpn @ eclipj2000_to_j2000_equatorial()


def fit_record(start_jd: float,
               end_jd: float,
               degree: int,
               sample_count: int,
               validation_count: int) -> tuple[bytes, float]:
    mid_jd = 0.5 * (start_jd + end_jd)
    radius_days = 0.5 * (end_jd - start_jd)
    sample_jds = np.linspace(start_jd, end_jd, sample_count)
    x = (sample_jds - mid_jd) / radius_days
    samples = np.array([rotation_matrix(jd).reshape(9) for jd in sample_jds])
    coeff = [
        np.polynomial.chebyshev.chebfit(x, samples[:, component], degree)
        for component in range(9)
    ]

    max_residual = 0.0
    validation_jds = np.linspace(start_jd, end_jd, validation_count)
    validation_x = (validation_jds - mid_jd) / radius_days
    for jd, xx in zip(validation_jds, validation_x):
        truth = rotation_matrix(jd).reshape(9)
        fitted = np.array([
            np.polynomial.chebyshev.chebval(xx, coeff[component])
            for component in range(9)
        ])
        max_residual = max(max_residual, float(np.max(np.abs(fitted - truth))))

    packed = b"".join(
        struct.pack("<d", float(value))
        for component in range(9)
        for value in coeff[component]
    )
    return packed, max_residual


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--start-year", type=int, default=1550)
    parser.add_argument("--end-year", type=int, default=2649)
    parser.add_argument("--window-days", type=float, default=365.25)
    parser.add_argument("--degree", type=int, default=12)
    parser.add_argument("--sample-count", type=int, default=0)
    parser.add_argument("--validation-count", type=int, default=0)
    parser.add_argument("--model-id-base", type=int, default=1)
    parser.add_argument("--output", default="packaging/almanac-db/mars_almanac_frame_rotation.sql")
    args = parser.parse_args()

    start_jd = jd_from_gregorian(args.start_year, 1, 1)
    end_jd = jd_from_gregorian(args.end_year + 1, 1, 1)
    sample_count = max(args.degree + 3, args.sample_count or args.degree + 8)
    validation_count = max(args.degree + 5, args.validation_count or args.degree + 12)
    series_id = args.model_id_base
    segment_rows = []
    max_residual = 0.0
    jd = start_jd
    segment_index = 0

    while jd < end_jd - 1.0e-9:
        record_end = min(jd + args.window_days, end_jd)
        blob, residual = fit_record(jd, record_end, args.degree, sample_count, validation_count)
        max_residual = max(max_residual, residual)
        segment_rows.append(
            f"({series_id}, {segment_index}, X'{blob.hex()}')"
        )
        segment_index += 1
        jd = record_end

    out = Path(args.output)
    out.write_text(
        "-- Generated by tools/generate_almanac_frame_rotation_sql.py\n"
        "-- Chebyshev coefficients for ECLIPJ2000 to true equator/equinox of date.\n"
        "INSERT INTO almanac_frame_rotation_series "
        "(series_id, source_frame_id, target_frame_id, start_jd, end_jd, segment_span_days, "
        "segment_count, degree, component_count) VALUES\n"
        f"({series_id}, {FRAME_IDS['ECLIPJ2000']}, {FRAME_IDS['TRUE_EQUATOR_DATE']}, {start_jd:.8f}, {end_jd:.8f}, "
        f"{args.window_days:.8f}, {segment_index}, {args.degree}, 9);\n"
        "\n"
        "INSERT INTO almanac_frame_rotation_segment "
        "(series_id, segment_index, coefficient_blob) VALUES\n"
        + ",\n".join(segment_rows)
        + ";\n",
        encoding="utf-8",
    )
    print(
        f"Wrote {segment_index} frame-rotation rows to {out}; max matrix residual {max_residual:.6e}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
