#!/usr/bin/env python3
"""Generate ERFA-backed nutation coefficient inserts for the almanac seed DB."""

from __future__ import annotations

from dataclasses import dataclass
import struct

import erfa
import numpy as np

START_JD = 2287185.5
END_JD = 2688952.5
SEGMENT_DAYS = 365.25 * 5.0
DEGREE = 7
SAMPLES_PER_SEGMENT = 256


@dataclass
class Segment:
    model_id: int
    start_jd: float
    end_jd: float
    reference_jd: float
    span_days: float
    dpsi_coeffs: np.ndarray
    deps_coeffs: np.ndarray


def build_segments() -> list[Segment]:
    segments: list[Segment] = []
    start = START_JD
    model_id = 1

    while start < END_JD - 1.0e-9:
        end = min(start + SEGMENT_DAYS, END_JD)
        reference = 0.5 * (start + end)
        span = 0.5 * (end - start)
        xs = np.linspace(-1.0, 1.0, SAMPLES_PER_SEGMENT)
        jds = reference + xs * span
        nut = np.array(
            [erfa.nut00a(2451545.0, jd - 2451545.0) for jd in jds],
            dtype=float,
        )
        dpsi_coeffs = np.polynomial.chebyshev.chebfit(xs, nut[:, 0], DEGREE)
        deps_coeffs = np.polynomial.chebyshev.chebfit(xs, nut[:, 1], DEGREE)
        segments.append(
            Segment(
                model_id=model_id,
                start_jd=start,
                end_jd=end,
                reference_jd=reference,
                span_days=span,
                dpsi_coeffs=dpsi_coeffs,
                deps_coeffs=deps_coeffs,
            )
        )
        start = end
        model_id += 1

    return segments


def format_segment(segment: Segment) -> str:
    coeffs = [*segment.dpsi_coeffs.tolist(), *segment.deps_coeffs.tolist()]
    coeff_blob = b"".join(struct.pack("<d", float(value)) for value in coeffs)
    return (
        "INSERT INTO almanac_nutation_model "
        "(model_id, coefficient_blob, sort_order) "
        f"VALUES ({segment.model_id}, X'{coeff_blob.hex()}', {segment.model_id * 10});"
    )


def main() -> None:
    segments = build_segments()
    max_dpsi = 0.0
    max_deps = 0.0

    for segment in segments:
        xs = np.linspace(-1.0, 1.0, SAMPLES_PER_SEGMENT)
        jds = segment.reference_jd + xs * segment.span_days
        nut = np.array(
            [erfa.nut00a(2451545.0, jd - 2451545.0) for jd in jds],
            dtype=float,
        )
        dpsi_fit = np.polynomial.chebyshev.chebval(xs, segment.dpsi_coeffs)
        deps_fit = np.polynomial.chebyshev.chebval(xs, segment.deps_coeffs)
        max_dpsi = max(max_dpsi, float(np.max(np.abs(nut[:, 0] - dpsi_fit))))
        max_deps = max(max_deps, float(np.max(np.abs(nut[:, 1] - deps_fit))))

    print("-- Generated by tools/generate_almanac_nutation_sql.py")
    print(
        f"-- Max sampled dpsi residual: {max_dpsi * 206264.80624709636:.6f} arcsec"
    )
    print(
        f"-- Max sampled deps residual: {max_deps * 206264.80624709636:.6f} arcsec"
    )
    for segment in segments:
        print(format_segment(segment))


if __name__ == "__main__":
    main()
