/**
 * @file cfg_locales_sql.c
 * @brief Exact UTF-8 SQL rendering for derived calendar locale tables.
 *
 * Owns the stable schema and SQL literal escaping, not locale selection data.
 * Output is assembled entirely with exact appends so combining marks and token
 * boundaries survive unchanged. Publication belongs to the command unit.
 */
#include <string.h>

#include "cfg_locales_internal.h"

static const char cfg_locales_schema[] =
    "-- Generated by mars_config locales; do not edit by hand.\n"
    "-- Babel 2.17.0; Unicode CLDR 46. https://github.com/unicode-org/cldr/tree/release-46\n"
    "-- Copyright © 1991-2024 Unicode, Inc. Unicode Licence v3; see THIRD_PARTY_NOTICES.md.\n"
    "-- Territory defaults with explicit subdivision overrides; not town-level language detection.\n"
    "-- Breton and Cornish are explicit regional options supplementing CLDR official-language choices.\n"
    "-- Cajun French, Iñupiaq, Jamaican Patois, Ladino and Pennsylvania Dutch are supplements; Yiddish uses CLDR.\n"
    "-- Identical month and weekday sets are stored once; locale mappings preserve regional differences.\n"
    "create table if not exists calendar_territory_locale (\n"
    "    territory text primary key, locale text not null\n"
    ");\n"
    "create table if not exists calendar_language_name (\n"
    "    language text primary key, english_name text not null, native_name text not null\n"
    ");\n"
    "create table if not exists calendar_jurisdiction_language (\n"
    "    jurisdiction text not null, language text not null, locale text, status text not null,\n"
    "    primary key (jurisdiction, language)\n"
    ");\n"
    "create table if not exists calendar_town_language (\n"
    "    country text not null, town_key text not null, language text not null, locale text not null,\n"
    "    status text not null, primary key (country, town_key, language)\n"
    ");\n"
    "create table if not exists calendar_month_names (\n"
    "    name_set text not null, month_no integer not null check (month_no between 1 and 12),\n"
    "    short_name text not null, full_name text not null, primary key (name_set, month_no)\n"
    ");\n"
    "create table if not exists calendar_weekday_names (\n"
    "    name_set text not null, weekday_no integer not null check (weekday_no between 0 and 6),\n"
    "    day_name text not null, short_name text not null, primary key (name_set, weekday_no)\n"
    ");\n"
    "create table if not exists calendar_locale_name_set (\n"
    "    locale text primary key, month_set text not null, weekday_set text not null,\n"
    "    standalone_month_set text not null\n"
    ");\n"
    "create table if not exists calendar_locale_date_pattern (\n"
    "    locale text primary key, pattern_id integer not null, cldr_pattern text not null\n"
    ");\n"
    "create table if not exists calendar_date_pattern_part (\n"
    "    pattern_id integer not null, position integer not null, field text not null, literal text not null,\n"
    "    primary key (pattern_id, position)\n"
    ");\n"
    "create view if not exists calendar_locale_month as\n"
    "select l.locale, n.month_no, n.short_name, n.full_name\n"
    "from calendar_locale_name_set as l join calendar_month_names as n on n.name_set = l.month_set;\n"
    "create view if not exists calendar_locale_month_standalone as\n"
    "select l.locale, n.month_no, n.short_name, n.full_name\n"
    "from calendar_locale_name_set as l join calendar_month_names as n on n.name_set = l.standalone_month_set;\n"
    "create view if not exists calendar_locale_weekday as\n"
    "select l.locale, n.weekday_no, n.day_name, n.short_name\n"
    "from calendar_locale_name_set as l join calendar_weekday_names as n on n.name_set = l.weekday_set;\n";

static bool cfg_locales_output(string_t *out, const char *text, size_t length)
{
    size_t used = string_byte_length(out);
    return used <= CFG_LOCALES_OUTPUT_BYTES && length <= CFG_LOCALES_OUTPUT_BYTES - used &&
           !string_append_utf8_exact(out, text, length);
}

static bool cfg_locales_ascii(string_t *out, const char *text)
{
    return cfg_locales_output(out, text, strlen(text));
}

static bool cfg_locales_quote(string_t *out, const string_t *text)
{
    bool ok = cfg_locales_ascii(out, "'");
    string_view_t view = string_view_all(text);
    string_pos_t position = 0, next = 0, start = 0;
    while (ok && position < string_byte_length(text)) {
        uint32_t scalar = 0;
        ok = string_view_peek_rune_value(view, position, &scalar, &next) && scalar != 0;
        if (ok && scalar == '\'') {
            ok = cfg_locales_output(out, string_c_str(text) + start, position - start) && cfg_locales_ascii(out, "''");
            start = next;
        }
        position = next;
    }
    return ok && cfg_locales_output(out, string_c_str(text) + start, string_byte_length(text) - start) &&
           cfg_locales_ascii(out, "'");
}

/* Render generated rows, rejecting unexpected intermediate types. */
string_t *cfg_locales_sql(const cfg_locales_state *state)
{
    const char *tables[] = {"calendar_territory_locale",  "calendar_language_name",   "calendar_jurisdiction_language",
                            "calendar_town_language",     "calendar_locale_name_set", "calendar_locale_date_pattern",
                            "calendar_date_pattern_part", "calendar_month_names",     "calendar_weekday_names"};
    const size_t columns[] = {2, 3, 4, 5, 4, 3, 4, 4, 4};
    string_t *out = string_new();
    bool ok = out && cfg_locales_ascii(out, cfg_locales_schema);
    for (size_t i = 0; i < 9 && ok; ++i) {
        const json_t *rows = state->tables[i];
        size_t count = json_array_size(rows);
        ok = count && cfg_locales_ascii(out, "insert or replace into ") && cfg_locales_ascii(out, tables[i]) &&
             cfg_locales_ascii(out, " values\n");
        for (size_t j = 0; j < count && ok; ++j) {
            const json_t *row = json_array_get(rows, j);
            ok = json_array_size(row) == columns[i] && cfg_locales_ascii(out, "    (");
            for (size_t k = 0; k < columns[i] && ok; ++k) {
                const json_t *value = json_array_get(row, k);
                ok = !k || cfg_locales_ascii(out, ", ");
                if (!ok)
                    break;
                json_type_t type = json_type(value);
                if (type == JSON_STRING)
                    ok = cfg_locales_quote(out, json_string_value(value));
                else if (type == JSON_NUMBER) {
                    const string_t *number = json_number_text(value);
                    ok = number && cfg_locales_output(out, string_c_str(number), string_byte_length(number));
                } else
                    ok = type == JSON_NULL && cfg_locales_ascii(out, "null");
            }
            ok = ok && cfg_locales_ascii(out, j + 1 < count ? "),\n" : ");\n");
        }
    }
    if (!ok) {
        string_free(out);
        out = NULL;
    }
    return out;
}
