-- Target subdivision jurisdictions for bundled holiday rules.
-- Target subdivision jurisdictions for countries requested to carry deeper holiday coverage.

insert into jurisdiction(
    jurisdiction_id,
    parent_jurisdiction_id,
    jurisdiction_type,
    iso_country_code,
    iso_subdivision_code,
    cldr_region_code,
    name
) values
    ('AU-ACT', 'AU', 'subdivision', 'AU', 'AU-ACT', 'AU', 'Australian Capital Territory'),
    ('AU-NSW', 'AU', 'subdivision', 'AU', 'AU-NSW', 'AU', 'New South Wales'),
    ('AU-NT', 'AU', 'subdivision', 'AU', 'AU-NT', 'AU', 'Northern Territory'),
    ('AU-QLD', 'AU', 'subdivision', 'AU', 'AU-QLD', 'AU', 'Queensland'),
    ('AU-SA', 'AU', 'subdivision', 'AU', 'AU-SA', 'AU', 'South Australia'),
    ('AU-TAS', 'AU', 'subdivision', 'AU', 'AU-TAS', 'AU', 'Tasmania'),
    ('AU-VIC', 'AU', 'subdivision', 'AU', 'AU-VIC', 'AU', 'Victoria'),
    ('AU-WA', 'AU', 'subdivision', 'AU', 'AU-WA', 'AU', 'Western Australia'),
    ('CA-AB', 'CA', 'subdivision', 'CA', 'CA-AB', 'CA', 'Alberta'),
    ('CA-BC', 'CA', 'subdivision', 'CA', 'CA-BC', 'CA', 'British Columbia'),
    ('CA-MB', 'CA', 'subdivision', 'CA', 'CA-MB', 'CA', 'Manitoba'),
    ('CA-NB', 'CA', 'subdivision', 'CA', 'CA-NB', 'CA', 'New Brunswick'),
    ('CA-NL', 'CA', 'subdivision', 'CA', 'CA-NL', 'CA', 'Terre-Neuve-et-Labrador'),
    ('CA-NS', 'CA', 'subdivision', 'CA', 'CA-NS', 'CA', 'Nova Scotia'),
    ('CA-NT', 'CA', 'subdivision', 'CA', 'CA-NT', 'CA', 'Northwest Territories'),
    ('CA-NU', 'CA', 'subdivision', 'CA', 'CA-NU', 'CA', 'Nunavut'),
    ('CA-ON', 'CA', 'subdivision', 'CA', 'CA-ON', 'CA', 'Ontario'),
    ('CA-PE', 'CA', 'subdivision', 'CA', 'CA-PE', 'CA', 'Prince Edward Island'),
    ('CA-QC', 'CA', 'subdivision', 'CA', 'CA-QC', 'CA', 'Quebec'),
    ('CA-SK', 'CA', 'subdivision', 'CA', 'CA-SK', 'CA', 'Saskatchewan'),
    ('CA-YT', 'CA', 'subdivision', 'CA', 'CA-YT', 'CA', 'Yukon'),
    ('US-AK', 'US', 'subdivision', 'US', 'US-AK', 'US', 'Alaska'),
    ('US-AL', 'US', 'subdivision', 'US', 'US-AL', 'US', 'Alabama'),
    ('US-AR', 'US', 'subdivision', 'US', 'US-AR', 'US', 'Arkansas'),
    ('US-AS', 'US', 'subdivision', 'US', 'US-AS', 'US', 'American Samoa'),
    ('US-AZ', 'US', 'subdivision', 'US', 'US-AZ', 'US', 'Arizona'),
    ('US-CA', 'US', 'subdivision', 'US', 'US-CA', 'US', 'California'),
    ('US-CO', 'US', 'subdivision', 'US', 'US-CO', 'US', 'Colorado'),
    ('US-CT', 'US', 'subdivision', 'US', 'US-CT', 'US', 'Connecticut'),
    ('US-DC', 'US', 'subdivision', 'US', 'US-DC', 'US', 'District of Columbia'),
    ('US-DE', 'US', 'subdivision', 'US', 'US-DE', 'US', 'Delaware'),
    ('US-FL', 'US', 'subdivision', 'US', 'US-FL', 'US', 'Florida'),
    ('US-GA', 'US', 'subdivision', 'US', 'US-GA', 'US', 'Georgia'),
    ('US-GU', 'US', 'subdivision', 'US', 'US-GU', 'US', 'Guam'),
    ('US-HI', 'US', 'subdivision', 'US', 'US-HI', 'US', 'Hawaii'),
    ('US-IA', 'US', 'subdivision', 'US', 'US-IA', 'US', 'Iowa'),
    ('US-ID', 'US', 'subdivision', 'US', 'US-ID', 'US', 'Idaho'),
    ('US-IL', 'US', 'subdivision', 'US', 'US-IL', 'US', 'Illinois'),
    ('US-IN', 'US', 'subdivision', 'US', 'US-IN', 'US', 'Indiana'),
    ('US-KS', 'US', 'subdivision', 'US', 'US-KS', 'US', 'Kansas'),
    ('US-KY', 'US', 'subdivision', 'US', 'US-KY', 'US', 'Kentucky'),
    ('US-LA', 'US', 'subdivision', 'US', 'US-LA', 'US', 'Louisiana'),
    ('US-MA', 'US', 'subdivision', 'US', 'US-MA', 'US', 'Massachusetts'),
    ('US-MD', 'US', 'subdivision', 'US', 'US-MD', 'US', 'Maryland'),
    ('US-ME', 'US', 'subdivision', 'US', 'US-ME', 'US', 'Maine'),
    ('US-MI', 'US', 'subdivision', 'US', 'US-MI', 'US', 'Michigan'),
    ('US-MN', 'US', 'subdivision', 'US', 'US-MN', 'US', 'Minnesota'),
    ('US-MO', 'US', 'subdivision', 'US', 'US-MO', 'US', 'Missouri'),
    ('US-MP', 'US', 'subdivision', 'US', 'US-MP', 'US', 'Northern Mariana Islands'),
    ('US-MS', 'US', 'subdivision', 'US', 'US-MS', 'US', 'Mississippi'),
    ('US-MT', 'US', 'subdivision', 'US', 'US-MT', 'US', 'Montana'),
    ('US-NC', 'US', 'subdivision', 'US', 'US-NC', 'US', 'North Carolina'),
    ('US-ND', 'US', 'subdivision', 'US', 'US-ND', 'US', 'North Dakota'),
    ('US-NE', 'US', 'subdivision', 'US', 'US-NE', 'US', 'Nebraska'),
    ('US-NH', 'US', 'subdivision', 'US', 'US-NH', 'US', 'New Hampshire'),
    ('US-NJ', 'US', 'subdivision', 'US', 'US-NJ', 'US', 'New Jersey'),
    ('US-NM', 'US', 'subdivision', 'US', 'US-NM', 'US', 'New Mexico'),
    ('US-NV', 'US', 'subdivision', 'US', 'US-NV', 'US', 'Nevada'),
    ('US-NY', 'US', 'subdivision', 'US', 'US-NY', 'US', 'New York'),
    ('US-OH', 'US', 'subdivision', 'US', 'US-OH', 'US', 'Ohio'),
    ('US-OK', 'US', 'subdivision', 'US', 'US-OK', 'US', 'Oklahoma'),
    ('US-OR', 'US', 'subdivision', 'US', 'US-OR', 'US', 'Oregon'),
    ('US-PA', 'US', 'subdivision', 'US', 'US-PA', 'US', 'Pennsylvania'),
    ('US-PR', 'US', 'subdivision', 'US', 'US-PR', 'US', 'Puerto Rico'),
    ('US-RI', 'US', 'subdivision', 'US', 'US-RI', 'US', 'Rhode Island'),
    ('US-SC', 'US', 'subdivision', 'US', 'US-SC', 'US', 'South Carolina'),
    ('US-SD', 'US', 'subdivision', 'US', 'US-SD', 'US', 'South Dakota'),
    ('US-TN', 'US', 'subdivision', 'US', 'US-TN', 'US', 'Tennessee'),
    ('US-TX', 'US', 'subdivision', 'US', 'US-TX', 'US', 'Texas'),
    ('US-UM', 'US', 'subdivision', 'US', 'US-UM', 'US', 'United States Minor Outlying Islands'),
    ('US-UT', 'US', 'subdivision', 'US', 'US-UT', 'US', 'Utah'),
    ('US-VA', 'US', 'subdivision', 'US', 'US-VA', 'US', 'Virginia'),
    ('US-VI', 'US', 'subdivision', 'US', 'US-VI', 'US', 'Virgin Islands, U.S.'),
    ('US-VT', 'US', 'subdivision', 'US', 'US-VT', 'US', 'Vermont'),
    ('US-WA', 'US', 'subdivision', 'US', 'US-WA', 'US', 'Washington'),
    ('US-WI', 'US', 'subdivision', 'US', 'US-WI', 'US', 'Wisconsin'),
    ('US-WV', 'US', 'subdivision', 'US', 'US-WV', 'US', 'West Virginia'),
    ('US-WY', 'US', 'subdivision', 'US', 'US-WY', 'US', 'Wyoming'),
    ('GB-NIR', 'GB', 'subdivision', 'GB', 'GB-NIR', 'GB', 'Northern Ireland'),
    ('GB-SCT', 'GB', 'subdivision', 'GB', 'GB-SCT', 'GB', 'Scotland'),
    ('GB-WLS', 'GB', 'subdivision', 'GB', 'GB-WLS', 'GB', 'Wales'),
    ('NZ-AUK', 'NZ', 'subdivision', 'NZ', 'NZ-AUK', 'NZ', 'Auckland'),
    ('NZ-BOP', 'NZ', 'subdivision', 'NZ', 'NZ-BOP', 'NZ', 'Toi Moana'),
    ('NZ-CAN', 'NZ', 'subdivision', 'NZ', 'NZ-CAN', 'NZ', 'Waitaha'),
    ('NZ-CIT', 'NZ', 'subdivision', 'NZ', 'NZ-CIT', 'NZ', 'Wharekauri'),
    ('NZ-GIS', 'NZ', 'subdivision', 'NZ', 'NZ-GIS', 'NZ', 'Gisborne'),
    ('NZ-HKB', 'NZ', 'subdivision', 'NZ', 'NZ-HKB', 'NZ', 'Hawke''s Bay'),
    ('NZ-MBH', 'NZ', 'subdivision', 'NZ', 'NZ-MBH', 'NZ', 'Marlborough'),
    ('NZ-MWT', 'NZ', 'subdivision', 'NZ', 'NZ-MWT', 'NZ', 'Manawatū Whanganui'),
    ('NZ-NSN', 'NZ', 'subdivision', 'NZ', 'NZ-NSN', 'NZ', 'Nelson'),
    ('NZ-NTL', 'NZ', 'subdivision', 'NZ', 'NZ-NTL', 'NZ', 'Northland'),
    ('NZ-OTA', 'NZ', 'subdivision', 'NZ', 'NZ-OTA', 'NZ', 'Otago'),
    ('NZ-STL', 'NZ', 'subdivision', 'NZ', 'NZ-STL', 'NZ', 'Southland'),
    ('NZ-TAS', 'NZ', 'subdivision', 'NZ', 'NZ-TAS', 'NZ', 'Tasman'),
    ('NZ-TKI', 'NZ', 'subdivision', 'NZ', 'NZ-TKI', 'NZ', 'Taranaki'),
    ('NZ-WGN', 'NZ', 'subdivision', 'NZ', 'NZ-WGN', 'NZ', 'Wellington'),
    ('NZ-WKO', 'NZ', 'subdivision', 'NZ', 'NZ-WKO', 'NZ', 'Waikato'),
    ('NZ-WTC', 'NZ', 'subdivision', 'NZ', 'NZ-WTC', 'NZ', 'West Coast'),
    ('NZ-South Canterbury', 'NZ', 'subdivision', 'NZ', 'NZ-South Canterbury', 'NZ', 'NZ subdivision South Canterbury'),
    ('PT-01', 'PT', 'subdivision', 'PT', 'PT-01', 'PT', 'Aveiro'),
    ('PT-02', 'PT', 'subdivision', 'PT', 'PT-02', 'PT', 'Beja'),
    ('PT-03', 'PT', 'subdivision', 'PT', 'PT-03', 'PT', 'Braga'),
    ('PT-04', 'PT', 'subdivision', 'PT', 'PT-04', 'PT', 'Bragança'),
    ('PT-05', 'PT', 'subdivision', 'PT', 'PT-05', 'PT', 'Castelo Branco'),
    ('PT-06', 'PT', 'subdivision', 'PT', 'PT-06', 'PT', 'Coimbra'),
    ('PT-07', 'PT', 'subdivision', 'PT', 'PT-07', 'PT', 'Évora'),
    ('PT-08', 'PT', 'subdivision', 'PT', 'PT-08', 'PT', 'Faro'),
    ('PT-09', 'PT', 'subdivision', 'PT', 'PT-09', 'PT', 'Guarda'),
    ('PT-10', 'PT', 'subdivision', 'PT', 'PT-10', 'PT', 'Leiria'),
    ('PT-11', 'PT', 'subdivision', 'PT', 'PT-11', 'PT', 'Lisboa'),
    ('PT-12', 'PT', 'subdivision', 'PT', 'PT-12', 'PT', 'Portalegre'),
    ('PT-13', 'PT', 'subdivision', 'PT', 'PT-13', 'PT', 'Porto'),
    ('PT-14', 'PT', 'subdivision', 'PT', 'PT-14', 'PT', 'Santarém'),
    ('PT-15', 'PT', 'subdivision', 'PT', 'PT-15', 'PT', 'Setúbal'),
    ('PT-16', 'PT', 'subdivision', 'PT', 'PT-16', 'PT', 'Viana do Castelo'),
    ('PT-17', 'PT', 'subdivision', 'PT', 'PT-17', 'PT', 'Vila Real'),
    ('PT-18', 'PT', 'subdivision', 'PT', 'PT-18', 'PT', 'Viseu'),
    ('PT-20', 'PT', 'subdivision', 'PT', 'PT-20', 'PT', 'Região Autónoma dos Açores'),
    ('PT-30', 'PT', 'subdivision', 'PT', 'PT-30', 'PT', 'Região Autónoma da Madeira'),
    ('IT-AG', 'IT', 'subdivision', 'IT', 'IT-AG', 'IT', 'Agrigento'),
    ('IT-AL', 'IT', 'subdivision', 'IT', 'IT-AL', 'IT', 'Alessandria'),
    ('IT-AN', 'IT', 'subdivision', 'IT', 'IT-AN', 'IT', 'Ancona'),
    ('IT-AO', 'IT', 'subdivision', 'IT', 'IT-AO', 'IT', 'Aosta'),
    ('IT-AP', 'IT', 'subdivision', 'IT', 'IT-AP', 'IT', 'Ascoli Piceno'),
    ('IT-AQ', 'IT', 'subdivision', 'IT', 'IT-AQ', 'IT', 'L''Aquila'),
    ('IT-AR', 'IT', 'subdivision', 'IT', 'IT-AR', 'IT', 'Arezzo'),
    ('IT-AT', 'IT', 'subdivision', 'IT', 'IT-AT', 'IT', 'Asti'),
    ('IT-AV', 'IT', 'subdivision', 'IT', 'IT-AV', 'IT', 'Avellino'),
    ('IT-BA', 'IT', 'subdivision', 'IT', 'IT-BA', 'IT', 'Bari'),
    ('IT-BG', 'IT', 'subdivision', 'IT', 'IT-BG', 'IT', 'Bergamo'),
    ('IT-BI', 'IT', 'subdivision', 'IT', 'IT-BI', 'IT', 'Biella'),
    ('IT-BL', 'IT', 'subdivision', 'IT', 'IT-BL', 'IT', 'Belluno'),
    ('IT-BN', 'IT', 'subdivision', 'IT', 'IT-BN', 'IT', 'Benevento'),
    ('IT-BO', 'IT', 'subdivision', 'IT', 'IT-BO', 'IT', 'Bologna'),
    ('IT-BR', 'IT', 'subdivision', 'IT', 'IT-BR', 'IT', 'Brindisi'),
    ('IT-BS', 'IT', 'subdivision', 'IT', 'IT-BS', 'IT', 'Brescia'),
    ('IT-BT', 'IT', 'subdivision', 'IT', 'IT-BT', 'IT', 'Barletta-Andria-Trani'),
    ('IT-BZ', 'IT', 'subdivision', 'IT', 'IT-BZ', 'IT', 'Bolzano'),
    ('IT-CA', 'IT', 'subdivision', 'IT', 'IT-CA', 'IT', 'Cagliari'),
    ('IT-CB', 'IT', 'subdivision', 'IT', 'IT-CB', 'IT', 'Campobasso'),
    ('IT-CE', 'IT', 'subdivision', 'IT', 'IT-CE', 'IT', 'Caserta'),
    ('IT-CH', 'IT', 'subdivision', 'IT', 'IT-CH', 'IT', 'Chieti'),
    ('IT-CL', 'IT', 'subdivision', 'IT', 'IT-CL', 'IT', 'Caltanissetta'),
    ('IT-CN', 'IT', 'subdivision', 'IT', 'IT-CN', 'IT', 'Cuneo'),
    ('IT-CO', 'IT', 'subdivision', 'IT', 'IT-CO', 'IT', 'Como'),
    ('IT-CR', 'IT', 'subdivision', 'IT', 'IT-CR', 'IT', 'Cremona'),
    ('IT-CS', 'IT', 'subdivision', 'IT', 'IT-CS', 'IT', 'Cosenza'),
    ('IT-CT', 'IT', 'subdivision', 'IT', 'IT-CT', 'IT', 'Catania'),
    ('IT-CZ', 'IT', 'subdivision', 'IT', 'IT-CZ', 'IT', 'Catanzaro'),
    ('IT-EN', 'IT', 'subdivision', 'IT', 'IT-EN', 'IT', 'Enna'),
    ('IT-FC', 'IT', 'subdivision', 'IT', 'IT-FC', 'IT', 'Forli-Cesena'),
    ('IT-FE', 'IT', 'subdivision', 'IT', 'IT-FE', 'IT', 'Ferrara'),
    ('IT-FG', 'IT', 'subdivision', 'IT', 'IT-FG', 'IT', 'Foggia'),
    ('IT-FI', 'IT', 'subdivision', 'IT', 'IT-FI', 'IT', 'Firenze'),
    ('IT-FM', 'IT', 'subdivision', 'IT', 'IT-FM', 'IT', 'Fermo'),
    ('IT-FR', 'IT', 'subdivision', 'IT', 'IT-FR', 'IT', 'Frosinone'),
    ('IT-GE', 'IT', 'subdivision', 'IT', 'IT-GE', 'IT', 'Genova'),
    ('IT-GO', 'IT', 'subdivision', 'IT', 'IT-GO', 'IT', 'Gorizia'),
    ('IT-GR', 'IT', 'subdivision', 'IT', 'IT-GR', 'IT', 'Grosseto'),
    ('IT-IM', 'IT', 'subdivision', 'IT', 'IT-IM', 'IT', 'Imperia'),
    ('IT-IS', 'IT', 'subdivision', 'IT', 'IT-IS', 'IT', 'Isernia'),
    ('IT-KR', 'IT', 'subdivision', 'IT', 'IT-KR', 'IT', 'Crotone'),
    ('IT-LC', 'IT', 'subdivision', 'IT', 'IT-LC', 'IT', 'Lecco'),
    ('IT-LE', 'IT', 'subdivision', 'IT', 'IT-LE', 'IT', 'Lecce'),
    ('IT-LI', 'IT', 'subdivision', 'IT', 'IT-LI', 'IT', 'Livorno'),
    ('IT-LO', 'IT', 'subdivision', 'IT', 'IT-LO', 'IT', 'Lodi'),
    ('IT-LT', 'IT', 'subdivision', 'IT', 'IT-LT', 'IT', 'Latina'),
    ('IT-LU', 'IT', 'subdivision', 'IT', 'IT-LU', 'IT', 'Lucca'),
    ('IT-MB', 'IT', 'subdivision', 'IT', 'IT-MB', 'IT', 'Monza e Brianza'),
    ('IT-MC', 'IT', 'subdivision', 'IT', 'IT-MC', 'IT', 'Macerata'),
    ('IT-ME', 'IT', 'subdivision', 'IT', 'IT-ME', 'IT', 'Messina'),
    ('IT-MI', 'IT', 'subdivision', 'IT', 'IT-MI', 'IT', 'Milano'),
    ('IT-MN', 'IT', 'subdivision', 'IT', 'IT-MN', 'IT', 'Mantova'),
    ('IT-MO', 'IT', 'subdivision', 'IT', 'IT-MO', 'IT', 'Modena'),
    ('IT-MS', 'IT', 'subdivision', 'IT', 'IT-MS', 'IT', 'Massa-Carrara'),
    ('IT-MT', 'IT', 'subdivision', 'IT', 'IT-MT', 'IT', 'Matera'),
    ('IT-NA', 'IT', 'subdivision', 'IT', 'IT-NA', 'IT', 'Napoli'),
    ('IT-NO', 'IT', 'subdivision', 'IT', 'IT-NO', 'IT', 'Novara'),
    ('IT-NU', 'IT', 'subdivision', 'IT', 'IT-NU', 'IT', 'Nuoro'),
    ('IT-OR', 'IT', 'subdivision', 'IT', 'IT-OR', 'IT', 'Oristano'),
    ('IT-PA', 'IT', 'subdivision', 'IT', 'IT-PA', 'IT', 'Palermo'),
    ('IT-PC', 'IT', 'subdivision', 'IT', 'IT-PC', 'IT', 'Piacenza'),
    ('IT-PD', 'IT', 'subdivision', 'IT', 'IT-PD', 'IT', 'Padova'),
    ('IT-PE', 'IT', 'subdivision', 'IT', 'IT-PE', 'IT', 'Pescara'),
    ('IT-PG', 'IT', 'subdivision', 'IT', 'IT-PG', 'IT', 'Perugia'),
    ('IT-PI', 'IT', 'subdivision', 'IT', 'IT-PI', 'IT', 'Pisa'),
    ('IT-PN', 'IT', 'subdivision', 'IT', 'IT-PN', 'IT', 'Pordenone'),
    ('IT-PO', 'IT', 'subdivision', 'IT', 'IT-PO', 'IT', 'Prato'),
    ('IT-PR', 'IT', 'subdivision', 'IT', 'IT-PR', 'IT', 'Parma'),
    ('IT-PT', 'IT', 'subdivision', 'IT', 'IT-PT', 'IT', 'Pistoia'),
    ('IT-PU', 'IT', 'subdivision', 'IT', 'IT-PU', 'IT', 'Pesaro e Urbino'),
    ('IT-PV', 'IT', 'subdivision', 'IT', 'IT-PV', 'IT', 'Pavia'),
    ('IT-PZ', 'IT', 'subdivision', 'IT', 'IT-PZ', 'IT', 'Potenza'),
    ('IT-RA', 'IT', 'subdivision', 'IT', 'IT-RA', 'IT', 'Ravenna'),
    ('IT-RC', 'IT', 'subdivision', 'IT', 'IT-RC', 'IT', 'Reggio Calabria'),
    ('IT-RE', 'IT', 'subdivision', 'IT', 'IT-RE', 'IT', 'Reggio Emilia'),
    ('IT-RG', 'IT', 'subdivision', 'IT', 'IT-RG', 'IT', 'Ragusa'),
    ('IT-RI', 'IT', 'subdivision', 'IT', 'IT-RI', 'IT', 'Rieti'),
    ('IT-RM', 'IT', 'subdivision', 'IT', 'IT-RM', 'IT', 'Roma'),
    ('IT-RN', 'IT', 'subdivision', 'IT', 'IT-RN', 'IT', 'Rimini'),
    ('IT-RO', 'IT', 'subdivision', 'IT', 'IT-RO', 'IT', 'Rovigo'),
    ('IT-SA', 'IT', 'subdivision', 'IT', 'IT-SA', 'IT', 'Salerno'),
    ('IT-SI', 'IT', 'subdivision', 'IT', 'IT-SI', 'IT', 'Siena'),
    ('IT-SO', 'IT', 'subdivision', 'IT', 'IT-SO', 'IT', 'Sondrio'),
    ('IT-SP', 'IT', 'subdivision', 'IT', 'IT-SP', 'IT', 'La Spezia'),
    ('IT-SR', 'IT', 'subdivision', 'IT', 'IT-SR', 'IT', 'Siracusa'),
    ('IT-SS', 'IT', 'subdivision', 'IT', 'IT-SS', 'IT', 'Sassari'),
    ('IT-SU', 'IT', 'subdivision', 'IT', 'IT-SU', 'IT', 'Sud Sardegna'),
    ('IT-SV', 'IT', 'subdivision', 'IT', 'IT-SV', 'IT', 'Savona'),
    ('IT-TA', 'IT', 'subdivision', 'IT', 'IT-TA', 'IT', 'Taranto'),
    ('IT-TE', 'IT', 'subdivision', 'IT', 'IT-TE', 'IT', 'Teramo'),
    ('IT-TN', 'IT', 'subdivision', 'IT', 'IT-TN', 'IT', 'Trento'),
    ('IT-TO', 'IT', 'subdivision', 'IT', 'IT-TO', 'IT', 'Torino'),
    ('IT-TP', 'IT', 'subdivision', 'IT', 'IT-TP', 'IT', 'Trapani'),
    ('IT-TR', 'IT', 'subdivision', 'IT', 'IT-TR', 'IT', 'Terni'),
    ('IT-TS', 'IT', 'subdivision', 'IT', 'IT-TS', 'IT', 'Trieste'),
    ('IT-TV', 'IT', 'subdivision', 'IT', 'IT-TV', 'IT', 'Treviso'),
    ('IT-UD', 'IT', 'subdivision', 'IT', 'IT-UD', 'IT', 'Udine'),
    ('IT-VA', 'IT', 'subdivision', 'IT', 'IT-VA', 'IT', 'Varese'),
    ('IT-VB', 'IT', 'subdivision', 'IT', 'IT-VB', 'IT', 'Verbano-Cusio-Ossola'),
    ('IT-VC', 'IT', 'subdivision', 'IT', 'IT-VC', 'IT', 'Vercelli'),
    ('IT-VE', 'IT', 'subdivision', 'IT', 'IT-VE', 'IT', 'Venezia'),
    ('IT-VI', 'IT', 'subdivision', 'IT', 'IT-VI', 'IT', 'Vicenza'),
    ('IT-VR', 'IT', 'subdivision', 'IT', 'IT-VR', 'IT', 'Verona'),
    ('IT-VT', 'IT', 'subdivision', 'IT', 'IT-VT', 'IT', 'Viterbo'),
    ('IT-VV', 'IT', 'subdivision', 'IT', 'IT-VV', 'IT', 'Vibo Valentia'),
    ('IT-Andria', 'IT', 'subdivision', 'IT', 'IT-Andria', 'IT', 'IT subdivision Andria'),
    ('IT-Barletta', 'IT', 'subdivision', 'IT', 'IT-Barletta', 'IT', 'IT subdivision Barletta'),
    ('IT-Cesena', 'IT', 'subdivision', 'IT', 'IT-Cesena', 'IT', 'IT subdivision Cesena'),
    ('IT-Forli', 'IT', 'subdivision', 'IT', 'IT-Forli', 'IT', 'Forlì'),
    ('IT-Pesaro', 'IT', 'subdivision', 'IT', 'IT-Pesaro', 'IT', 'IT subdivision Pesaro'),
    ('IT-Trani', 'IT', 'subdivision', 'IT', 'IT-Trani', 'IT', 'IT subdivision Trani'),
    ('IT-Urbino', 'IT', 'subdivision', 'IT', 'IT-Urbino', 'IT', 'IT subdivision Urbino');
