-- Generated from /usr/share/zoneinfo/iso3166.tab
-- Source date in file header: current as of ISO/TC 46 N1127 (2024-02-29).

insert into jurisdiction(
    jurisdiction_id,
    jurisdiction_type,
    iso_country_code,
    cldr_region_code,
    name
) values
    ('AD', 'country', 'AD', 'AD', 'Andorra'),
    ('AE', 'country', 'AE', 'AE', 'United Arab Emirates'),
    ('AF', 'country', 'AF', 'AF', 'Afghanistan'),
    ('AG', 'country', 'AG', 'AG', 'Antigua & Barbuda'),
    ('AI', 'country', 'AI', 'AI', 'Anguilla'),
    ('AL', 'country', 'AL', 'AL', 'Albania'),
    ('AM', 'country', 'AM', 'AM', 'Armenia'),
    ('AO', 'country', 'AO', 'AO', 'Angola'),
    ('AQ', 'country', 'AQ', 'AQ', 'Antarctica'),
    ('AR', 'country', 'AR', 'AR', 'Argentina'),
    ('AS', 'country', 'AS', 'AS', 'Samoa (American)'),
    ('AT', 'country', 'AT', 'AT', 'Austria'),
    ('AU', 'country', 'AU', 'AU', 'Australia'),
    ('AW', 'country', 'AW', 'AW', 'Aruba'),
    ('AX', 'country', 'AX', 'AX', 'Åland Islands'),
    ('AZ', 'country', 'AZ', 'AZ', 'Azerbaijan'),
    ('BA', 'country', 'BA', 'BA', 'Bosnia & Herzegovina'),
    ('BB', 'country', 'BB', 'BB', 'Barbados'),
    ('BD', 'country', 'BD', 'BD', 'Bangladesh'),
    ('BE', 'country', 'BE', 'BE', 'Belgium'),
    ('BF', 'country', 'BF', 'BF', 'Burkina Faso'),
    ('BG', 'country', 'BG', 'BG', 'Bulgaria'),
    ('BH', 'country', 'BH', 'BH', 'Bahrain'),
    ('BI', 'country', 'BI', 'BI', 'Burundi'),
    ('BJ', 'country', 'BJ', 'BJ', 'Benin'),
    ('BL', 'country', 'BL', 'BL', 'St Barthelemy'),
    ('BM', 'country', 'BM', 'BM', 'Bermuda'),
    ('BN', 'country', 'BN', 'BN', 'Brunei'),
    ('BO', 'country', 'BO', 'BO', 'Bolivia'),
    ('BQ', 'country', 'BQ', 'BQ', 'Caribbean NL'),
    ('BR', 'country', 'BR', 'BR', 'Brazil'),
    ('BS', 'country', 'BS', 'BS', 'Bahamas'),
    ('BT', 'country', 'BT', 'BT', 'Bhutan'),
    ('BV', 'country', 'BV', 'BV', 'Bouvet Island'),
    ('BW', 'country', 'BW', 'BW', 'Botswana'),
    ('BY', 'country', 'BY', 'BY', 'Belarus'),
    ('BZ', 'country', 'BZ', 'BZ', 'Belize'),
    ('CA', 'country', 'CA', 'CA', 'Canada'),
    ('CC', 'country', 'CC', 'CC', 'Cocos (Keeling) Islands'),
    ('CD', 'country', 'CD', 'CD', 'Congo (Dem. Rep.)'),
    ('CF', 'country', 'CF', 'CF', 'Central African Rep.'),
    ('CG', 'country', 'CG', 'CG', 'Congo (Rep.)'),
    ('CH', 'country', 'CH', 'CH', 'Switzerland'),
    ('CI', 'country', 'CI', 'CI', 'Côte d’Ivoire'),
    ('CK', 'country', 'CK', 'CK', 'Cook Islands'),
    ('CL', 'country', 'CL', 'CL', 'Chile'),
    ('CM', 'country', 'CM', 'CM', 'Cameroon'),
    ('CN', 'country', 'CN', 'CN', 'China'),
    ('CO', 'country', 'CO', 'CO', 'Colombia'),
    ('CR', 'country', 'CR', 'CR', 'Costa Rica'),
    ('CU', 'country', 'CU', 'CU', 'Cuba'),
    ('CV', 'country', 'CV', 'CV', 'Cape Verde'),
    ('CW', 'country', 'CW', 'CW', 'Curaçao'),
    ('CX', 'country', 'CX', 'CX', 'Christmas Island'),
    ('CY', 'country', 'CY', 'CY', 'Cyprus'),
    ('CZ', 'country', 'CZ', 'CZ', 'Czech Republic'),
    ('DE', 'country', 'DE', 'DE', 'Germany'),
    ('DJ', 'country', 'DJ', 'DJ', 'Djibouti'),
    ('DK', 'country', 'DK', 'DK', 'Denmark'),
    ('DM', 'country', 'DM', 'DM', 'Dominica'),
    ('DO', 'country', 'DO', 'DO', 'Dominican Republic'),
    ('DZ', 'country', 'DZ', 'DZ', 'Algeria'),
    ('EC', 'country', 'EC', 'EC', 'Ecuador'),
    ('EE', 'country', 'EE', 'EE', 'Estonia'),
    ('EG', 'country', 'EG', 'EG', 'Egypt'),
    ('EH', 'country', 'EH', 'EH', 'Western Sahara'),
    ('ER', 'country', 'ER', 'ER', 'Eritrea'),
    ('ES', 'country', 'ES', 'ES', 'Spain'),
    ('ET', 'country', 'ET', 'ET', 'Ethiopia'),
    ('FI', 'country', 'FI', 'FI', 'Finland'),
    ('FJ', 'country', 'FJ', 'FJ', 'Fiji'),
    ('FK', 'country', 'FK', 'FK', 'Falkland Islands'),
    ('FM', 'country', 'FM', 'FM', 'Micronesia'),
    ('FO', 'country', 'FO', 'FO', 'Faroe Islands'),
    ('FR', 'country', 'FR', 'FR', 'France'),
    ('GA', 'country', 'GA', 'GA', 'Gabon'),
    ('GB', 'country', 'GB', 'GB', 'Britain (UK)'),
    ('GD', 'country', 'GD', 'GD', 'Grenada'),
    ('GE', 'country', 'GE', 'GE', 'Georgia'),
    ('GF', 'country', 'GF', 'GF', 'French Guiana'),
    ('GG', 'country', 'GG', 'GG', 'Guernsey'),
    ('GH', 'country', 'GH', 'GH', 'Ghana'),
    ('GI', 'country', 'GI', 'GI', 'Gibraltar'),
    ('GL', 'country', 'GL', 'GL', 'Greenland'),
    ('GM', 'country', 'GM', 'GM', 'Gambia'),
    ('GN', 'country', 'GN', 'GN', 'Guinea'),
    ('GP', 'country', 'GP', 'GP', 'Guadeloupe'),
    ('GQ', 'country', 'GQ', 'GQ', 'Equatorial Guinea'),
    ('GR', 'country', 'GR', 'GR', 'Greece'),
    ('GS', 'country', 'GS', 'GS', 'South Georgia & the South Sandwich Islands'),
    ('GT', 'country', 'GT', 'GT', 'Guatemala'),
    ('GU', 'country', 'GU', 'GU', 'Guam'),
    ('GW', 'country', 'GW', 'GW', 'Guinea-Bissau'),
    ('GY', 'country', 'GY', 'GY', 'Guyana'),
    ('HK', 'country', 'HK', 'HK', 'Hong Kong'),
    ('HM', 'country', 'HM', 'HM', 'Heard Island & McDonald Islands'),
    ('HN', 'country', 'HN', 'HN', 'Honduras'),
    ('HR', 'country', 'HR', 'HR', 'Croatia'),
    ('HT', 'country', 'HT', 'HT', 'Haiti'),
    ('HU', 'country', 'HU', 'HU', 'Hungary'),
    ('ID', 'country', 'ID', 'ID', 'Indonesia'),
    ('IE', 'country', 'IE', 'IE', 'Ireland'),
    ('IL', 'country', 'IL', 'IL', 'Israel'),
    ('IM', 'country', 'IM', 'IM', 'Isle of Man'),
    ('IN', 'country', 'IN', 'IN', 'India'),
    ('IO', 'country', 'IO', 'IO', 'British Indian Ocean Territory'),
    ('IQ', 'country', 'IQ', 'IQ', 'Iraq'),
    ('IR', 'country', 'IR', 'IR', 'Iran'),
    ('IS', 'country', 'IS', 'IS', 'Iceland'),
    ('IT', 'country', 'IT', 'IT', 'Italy'),
    ('JE', 'country', 'JE', 'JE', 'Jersey'),
    ('JM', 'country', 'JM', 'JM', 'Jamaica'),
    ('JO', 'country', 'JO', 'JO', 'Jordan'),
    ('JP', 'country', 'JP', 'JP', 'Japan'),
    ('KE', 'country', 'KE', 'KE', 'Kenya'),
    ('KG', 'country', 'KG', 'KG', 'Kyrgyzstan'),
    ('KH', 'country', 'KH', 'KH', 'Cambodia'),
    ('KI', 'country', 'KI', 'KI', 'Kiribati'),
    ('KM', 'country', 'KM', 'KM', 'Comoros'),
    ('KN', 'country', 'KN', 'KN', 'St Kitts & Nevis'),
    ('KP', 'country', 'KP', 'KP', 'Korea (North)'),
    ('KR', 'country', 'KR', 'KR', 'Korea (South)'),
    ('KW', 'country', 'KW', 'KW', 'Kuwait'),
    ('KY', 'country', 'KY', 'KY', 'Cayman Islands'),
    ('KZ', 'country', 'KZ', 'KZ', 'Kazakhstan'),
    ('LA', 'country', 'LA', 'LA', 'Laos'),
    ('LB', 'country', 'LB', 'LB', 'Lebanon'),
    ('LC', 'country', 'LC', 'LC', 'St Lucia'),
    ('LI', 'country', 'LI', 'LI', 'Liechtenstein'),
    ('LK', 'country', 'LK', 'LK', 'Sri Lanka'),
    ('LR', 'country', 'LR', 'LR', 'Liberia'),
    ('LS', 'country', 'LS', 'LS', 'Lesotho'),
    ('LT', 'country', 'LT', 'LT', 'Lithuania'),
    ('LU', 'country', 'LU', 'LU', 'Luxembourg'),
    ('LV', 'country', 'LV', 'LV', 'Latvia'),
    ('LY', 'country', 'LY', 'LY', 'Libya'),
    ('MA', 'country', 'MA', 'MA', 'Morocco'),
    ('MC', 'country', 'MC', 'MC', 'Monaco'),
    ('MD', 'country', 'MD', 'MD', 'Moldova'),
    ('ME', 'country', 'ME', 'ME', 'Montenegro'),
    ('MF', 'country', 'MF', 'MF', 'St Martin (French)'),
    ('MG', 'country', 'MG', 'MG', 'Madagascar'),
    ('MH', 'country', 'MH', 'MH', 'Marshall Islands'),
    ('MK', 'country', 'MK', 'MK', 'North Macedonia'),
    ('ML', 'country', 'ML', 'ML', 'Mali'),
    ('MM', 'country', 'MM', 'MM', 'Myanmar (Burma)'),
    ('MN', 'country', 'MN', 'MN', 'Mongolia'),
    ('MO', 'country', 'MO', 'MO', 'Macau'),
    ('MP', 'country', 'MP', 'MP', 'Northern Mariana Islands'),
    ('MQ', 'country', 'MQ', 'MQ', 'Martinique'),
    ('MR', 'country', 'MR', 'MR', 'Mauritania'),
    ('MS', 'country', 'MS', 'MS', 'Montserrat'),
    ('MT', 'country', 'MT', 'MT', 'Malta'),
    ('MU', 'country', 'MU', 'MU', 'Mauritius'),
    ('MV', 'country', 'MV', 'MV', 'Maldives'),
    ('MW', 'country', 'MW', 'MW', 'Malawi'),
    ('MX', 'country', 'MX', 'MX', 'Mexico'),
    ('MY', 'country', 'MY', 'MY', 'Malaysia'),
    ('MZ', 'country', 'MZ', 'MZ', 'Mozambique'),
    ('NA', 'country', 'NA', 'NA', 'Namibia'),
    ('NC', 'country', 'NC', 'NC', 'New Caledonia'),
    ('NE', 'country', 'NE', 'NE', 'Niger'),
    ('NF', 'country', 'NF', 'NF', 'Norfolk Island'),
    ('NG', 'country', 'NG', 'NG', 'Nigeria'),
    ('NI', 'country', 'NI', 'NI', 'Nicaragua'),
    ('NL', 'country', 'NL', 'NL', 'Netherlands'),
    ('NO', 'country', 'NO', 'NO', 'Norway'),
    ('NP', 'country', 'NP', 'NP', 'Nepal'),
    ('NR', 'country', 'NR', 'NR', 'Nauru'),
    ('NU', 'country', 'NU', 'NU', 'Niue'),
    ('NZ', 'country', 'NZ', 'NZ', 'New Zealand'),
    ('OM', 'country', 'OM', 'OM', 'Oman'),
    ('PA', 'country', 'PA', 'PA', 'Panama'),
    ('PE', 'country', 'PE', 'PE', 'Peru'),
    ('PF', 'country', 'PF', 'PF', 'French Polynesia'),
    ('PG', 'country', 'PG', 'PG', 'Papua New Guinea'),
    ('PH', 'country', 'PH', 'PH', 'Philippines'),
    ('PK', 'country', 'PK', 'PK', 'Pakistan'),
    ('PL', 'country', 'PL', 'PL', 'Poland'),
    ('PM', 'country', 'PM', 'PM', 'St Pierre & Miquelon'),
    ('PN', 'country', 'PN', 'PN', 'Pitcairn'),
    ('PR', 'country', 'PR', 'PR', 'Puerto Rico'),
    ('PS', 'country', 'PS', 'PS', 'Palestine'),
    ('PT', 'country', 'PT', 'PT', 'Portugal'),
    ('PW', 'country', 'PW', 'PW', 'Palau'),
    ('PY', 'country', 'PY', 'PY', 'Paraguay'),
    ('QA', 'country', 'QA', 'QA', 'Qatar'),
    ('RE', 'country', 'RE', 'RE', 'Réunion'),
    ('RO', 'country', 'RO', 'RO', 'Romania'),
    ('RS', 'country', 'RS', 'RS', 'Serbia'),
    ('RU', 'country', 'RU', 'RU', 'Russia'),
    ('RW', 'country', 'RW', 'RW', 'Rwanda'),
    ('SA', 'country', 'SA', 'SA', 'Saudi Arabia'),
    ('SB', 'country', 'SB', 'SB', 'Solomon Islands'),
    ('SC', 'country', 'SC', 'SC', 'Seychelles'),
    ('SD', 'country', 'SD', 'SD', 'Sudan'),
    ('SE', 'country', 'SE', 'SE', 'Sweden'),
    ('SG', 'country', 'SG', 'SG', 'Singapore'),
    ('SH', 'country', 'SH', 'SH', 'St Helena'),
    ('SI', 'country', 'SI', 'SI', 'Slovenia'),
    ('SJ', 'country', 'SJ', 'SJ', 'Svalbard & Jan Mayen'),
    ('SK', 'country', 'SK', 'SK', 'Slovakia'),
    ('SL', 'country', 'SL', 'SL', 'Sierra Leone'),
    ('SM', 'country', 'SM', 'SM', 'San Marino'),
    ('SN', 'country', 'SN', 'SN', 'Senegal'),
    ('SO', 'country', 'SO', 'SO', 'Somalia'),
    ('SR', 'country', 'SR', 'SR', 'Suriname'),
    ('SS', 'country', 'SS', 'SS', 'South Sudan'),
    ('ST', 'country', 'ST', 'ST', 'Sao Tome & Principe'),
    ('SV', 'country', 'SV', 'SV', 'El Salvador'),
    ('SX', 'country', 'SX', 'SX', 'St Maarten (Dutch)'),
    ('SY', 'country', 'SY', 'SY', 'Syria'),
    ('SZ', 'country', 'SZ', 'SZ', 'Eswatini (Swaziland)'),
    ('TC', 'country', 'TC', 'TC', 'Turks & Caicos Is'),
    ('TD', 'country', 'TD', 'TD', 'Chad'),
    ('TF', 'country', 'TF', 'TF', 'French S. Terr.'),
    ('TG', 'country', 'TG', 'TG', 'Togo'),
    ('TH', 'country', 'TH', 'TH', 'Thailand'),
    ('TJ', 'country', 'TJ', 'TJ', 'Tajikistan'),
    ('TK', 'country', 'TK', 'TK', 'Tokelau'),
    ('TL', 'country', 'TL', 'TL', 'East Timor'),
    ('TM', 'country', 'TM', 'TM', 'Turkmenistan'),
    ('TN', 'country', 'TN', 'TN', 'Tunisia'),
    ('TO', 'country', 'TO', 'TO', 'Tonga'),
    ('TR', 'country', 'TR', 'TR', 'Turkey'),
    ('TT', 'country', 'TT', 'TT', 'Trinidad & Tobago'),
    ('TV', 'country', 'TV', 'TV', 'Tuvalu'),
    ('TW', 'country', 'TW', 'TW', 'Taiwan'),
    ('TZ', 'country', 'TZ', 'TZ', 'Tanzania'),
    ('UA', 'country', 'UA', 'UA', 'Ukraine'),
    ('UG', 'country', 'UG', 'UG', 'Uganda'),
    ('UM', 'country', 'UM', 'UM', 'US minor outlying islands'),
    ('US', 'country', 'US', 'US', 'United States'),
    ('UY', 'country', 'UY', 'UY', 'Uruguay'),
    ('UZ', 'country', 'UZ', 'UZ', 'Uzbekistan'),
    ('VA', 'country', 'VA', 'VA', 'Vatican City'),
    ('VC', 'country', 'VC', 'VC', 'St Vincent'),
    ('VE', 'country', 'VE', 'VE', 'Venezuela'),
    ('VG', 'country', 'VG', 'VG', 'Virgin Islands (UK)'),
    ('VI', 'country', 'VI', 'VI', 'Virgin Islands (US)'),
    ('VN', 'country', 'VN', 'VN', 'Vietnam'),
    ('VU', 'country', 'VU', 'VU', 'Vanuatu'),
    ('WF', 'country', 'WF', 'WF', 'Wallis & Futuna'),
    ('WS', 'country', 'WS', 'WS', 'Samoa (western)'),
    ('YE', 'country', 'YE', 'YE', 'Yemen'),
    ('YT', 'country', 'YT', 'YT', 'Mayotte'),
    ('ZA', 'country', 'ZA', 'ZA', 'South Africa'),
    ('ZM', 'country', 'ZM', 'ZM', 'Zambia'),
    ('ZW', 'country', 'ZW', 'ZW', 'Zimbabwe');
